In [162]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"
import pandas as pd
import numpy as np
import pymysql as py
import pymysql as Python
import warnings
warnings.filterwarnings("ignore")

In [163]:
pd.set_option('display.max_columns',None)

# Import Files and Append all together -All Collated for all months

In [164]:
df7= pd.read_csv(r"E:\Analytics_Shared\Devika Patawari\Bot Analysis\Data\Webchat_whatspp_collated_new\collated_Jul.csv",encoding="utf8")
df7.head(5)
df7.shape
df7.dtypes

,Number,User Query,Bot,Bot Response,Time,Intent Recognized,User ID,Channel,User Feedback,Intent Feedback,Sentiment
0,1,Close Account,Kotak Securities,I&#39;m not sure if I can help you with your q...,Jul 01 2022 11:59 PM,NaN,9.20E+11,WhatsApp,NaN,NaN,Neutral
1,2,Existing Client,Kotak Securities,NaN,Jul 01 2022 11:59 PM,WA Self Service Authentication,9.20E+11,WhatsApp,NaN,NaN,Neutral
2,3,Update Accounts,Kotak Securities,Choose one from the following,Jul 01 2022 11:59 PM,Update Account,9.20E+11,WhatsApp,NaN,NaN,Neutral
3,4,Chat with our expert,Kotak Securities,Your LiveChat request has been registered with...,Jul 01 2022 11:58 PM,NaN,740a455f-b9aa-4b2c-94f4-aa1681ca3911,Web,NaN,NaN,Neutral
4,5,redirect,Kotak Securities,NaN,Jul 01 2022 11:58 PM,LiveChat Service for Web,740a455f-b9aa-4b2c-94f4-aa1681ca3911,Web,NaN,NaN,Neutral

(802069, 11)

Number                 int64
User Query            object
Bot                   object
Bot Response          object
Time                  object
Intent Recognized     object
User ID               object
Channel               object
User Feedback        float64
Intent Feedback       object
Sentiment             object
dtype: object

In [165]:
df8= pd.read_csv(r"E:\Analytics_Shared\Devika Patawari\Bot Analysis\Data\Webchat_whatspp_collated_new\collated_Aug.csv",encoding='"latin-1"')
df8.head(5)
df8.shape
df8.dtypes
df8.dropna(subset = ['Number'], inplace=True)
df8['Number'] = df8['Number'].astype(np.int64)
df8.dtypes
df8.head(2)
df8.shape

,Number,User Query,Bot,Bot Response,Time,Intent Recognized,User ID,Channel,User Feedback,Intent Feedback,Sentiment,Date,Time.1,Date & Time,&,T/F,Diff,Count,Neo,Unnamed: 19,0:10:00,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Date.1,Unnamed: 31,Unnamed: 32,Unnamed: 33
0,1.0,Other Requests,Kotak Securities,Choose one from the following,Aug 01 2022 03:38 PM,Other Requests,00004f96-117f-49f1-89ac-4b7b792762fa,Web,NaN,NaN,Negative,1-Aug-22,3:38 PM,8/1/2022 15:38,Web00004f96-117f-49f1-89ac-4b7b792762fa08/01/2...,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.0,11.0,2022.0,11-Jul-22
1,2.0,No,Kotak Securities,Sorry I wasn&rsquo;t able to help you. I am st...,Aug 01 2022 03:39 PM,NaN,00004f96-117f-49f1-89ac-4b7b792762fa,Web,NaN,NaN,Neutral,1-Aug-22,3:39 PM,8/1/2022 15:39,Web00004f96-117f-49f1-89ac-4b7b792762fa08/01/2...,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.0,11.0,2022.0,11-Jul-22
2,3.0,Demat account,Kotak Securities,"Due to high chat volumes, there may be a delay...",Aug 01 2022 03:40 PM,NaN,00004f96-117f-49f1-89ac-4b7b792762fa,Web,NaN,NaN,Neutral,1-Aug-22,3:40 PM,8/1/2022 15:40,Web00004f96-117f-49f1-89ac-4b7b792762fa08/01/2...,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.0,11.0,2022.0,11-Jul-22
3,4.0,Connect to expert,Kotak Securities,Please select a category from the following.,Aug 01 2022 03:40 PM,NaN,00004f96-117f-49f1-89ac-4b7b792762fa,Web,NaN,NaN,Neutral,1-Aug-22,3:40 PM,8/1/2022 15:40,Web00004f96-117f-49f1-89ac-4b7b792762fa08/01/2...,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5.0,redirect,Kotak Securities,NaN,Aug 01 2022 03:40 PM,LiveChat Service for Web,00004f96-117f-49f1-89ac-4b7b792762fa,Web,NaN,NaN,Neutral,1-Aug-22,3:40 PM,8/1/2022 15:40,Web00004f96-117f-49f1-89ac-4b7b792762fa08/01/2...,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

(1007952, 34)

Number               float64
User Query            object
Bot                   object
Bot Response          object
Time                  object
Intent Recognized     object
User ID               object
Channel               object
User Feedback        float64
Intent Feedback       object
Sentiment             object
Date                  object
Time.1                object
Date & Time           object
&                     object
T/F                   object
Diff                  object
Count                float64
Neo                  float64
Unnamed: 19          float64
0:10:00              float64
Unnamed: 21          float64
Unnamed: 22          float64
Unnamed: 23          float64
Unnamed: 24          float64
Unnamed: 25          float64
Unnamed: 26          float64
Unnamed: 27          float64
Unnamed: 28          float64
Unnamed: 29          float64
Date.1               float64
Unnamed: 31          float64
Unnamed: 32          float64
Unnamed: 33           object
dtype: object

Number                 int64
User Query            object
Bot                   object
Bot Response          object
Time                  object
Intent Recognized     object
User ID               object
Channel               object
User Feedback        float64
Intent Feedback       object
Sentiment             object
Date                  object
Time.1                object
Date & Time           object
&                     object
T/F                   object
Diff                  object
Count                float64
Neo                  float64
Unnamed: 19          float64
0:10:00              float64
Unnamed: 21          float64
Unnamed: 22          float64
Unnamed: 23          float64
Unnamed: 24          float64
Unnamed: 25          float64
Unnamed: 26          float64
Unnamed: 27          float64
Unnamed: 28          float64
Unnamed: 29          float64
Date.1               float64
Unnamed: 31          float64
Unnamed: 32          float64
Unnamed: 33           object
dtype: object

,Number,User Query,Bot,Bot Response,Time,Intent Recognized,User ID,Channel,User Feedback,Intent Feedback,Sentiment,Date,Time.1,Date & Time,&,T/F,Diff,Count,Neo,Unnamed: 19,0:10:00,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Date.1,Unnamed: 31,Unnamed: 32,Unnamed: 33
0,1,Other Requests,Kotak Securities,Choose one from the following,Aug 01 2022 03:38 PM,Other Requests,00004f96-117f-49f1-89ac-4b7b792762fa,Web,NaN,NaN,Negative,1-Aug-22,3:38 PM,8/1/2022 15:38,Web00004f96-117f-49f1-89ac-4b7b792762fa08/01/2...,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.0,11.0,2022.0,11-Jul-22
1,2,No,Kotak Securities,Sorry I wasn&rsquo;t able to help you. I am st...,Aug 01 2022 03:39 PM,NaN,00004f96-117f-49f1-89ac-4b7b792762fa,Web,NaN,NaN,Neutral,1-Aug-22,3:39 PM,8/1/2022 15:39,Web00004f96-117f-49f1-89ac-4b7b792762fa08/01/2...,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.0,11.0,2022.0,11-Jul-22

(761300, 34)

In [166]:
df9= pd.read_csv(r"E:\Analytics_Shared\Devika Patawari\Bot Analysis\Data\Webchat_whatspp_collated_new\collated_Sep.csv",encoding='"latin-1"')
df9.head(5)
df9.shape
df9.dtypes
df9.dropna(subset = ['Number'], inplace=True)
df9['Number'] = df9['Number'].astype(np.int64)
df9.dtypes
df9.head(2)
df9.shape

,Number,User Query,Bot,Bot Response,Time,Intent Recognized,User ID,Channel,User Feedback,Intent Feedback,Sentiment,Date,Time.1,Date & Time,&,T/F,Diff,Count,Neo,Unnamed: 19,0:10:00,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Date.1,Unnamed: 31,Unnamed: 32,Unnamed: 33
0,1.0,Update Account,Kotak Securities,Choose one from the following,Sep 29 2022 10:18 AM,Update Account,00003eae-9dad-49cd-8b3d-e14f4949b4fa,Web,NaN,NaN,Neutral,29-Sep-22,10:18 AM,9/29/2022 10:18,Web00003eae-9dad-49cd-8b3d-e14f4949b4fa09/29/2...,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2.0,Change Address,Kotak Securities,Please click below and select 'Service Request...,Sep 29 2022 10:19 AM,NaN,00003eae-9dad-49cd-8b3d-e14f4949b4fa,Web,NaN,NaN,Neutral,29-Sep-22,10:19 AM,9/29/2022 10:19,Web00003eae-9dad-49cd-8b3d-e14f4949b4fa09/29/2...,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3.0,Display Link,Kotak Securities,NaN,Sep 29 2022 10:19 AM,Change Address,00003eae-9dad-49cd-8b3d-e14f4949b4fa,Web,NaN,NaN,Neutral,29-Sep-22,10:19 AM,9/29/2022 10:19,Web00003eae-9dad-49cd-8b3d-e14f4949b4fa09/29/2...,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4.0,Update Address,Kotak Securities,You are authenticated successfully for client ...,Sep 29 2022 10:19 AM,NaN,00003eae-9dad-49cd-8b3d-e14f4949b4fa,Web,NaN,NaN,Neutral,29-Sep-22,10:19 AM,9/29/2022 10:19,Web00003eae-9dad-49cd-8b3d-e14f4949b4fa09/29/2...,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5.0,Client Authenticated by Login,Kotak Securities,NaN,Sep 29 2022 10:19 AM,Web Self Service Authentication,00003eae-9dad-49cd-8b3d-e14f4949b4fa,Web,NaN,NaN,Neutral,29-Sep-22,10:19 AM,9/29/2022 10:19,Web00003eae-9dad-49cd-8b3d-e14f4949b4fa09/29/2...,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

(1007953, 34)

Number               float64
User Query            object
Bot                   object
Bot Response          object
Time                  object
Intent Recognized     object
User ID               object
Channel               object
User Feedback        float64
Intent Feedback       object
Sentiment             object
Date                  object
Time.1                object
Date & Time           object
&                     object
T/F                   object
Diff                  object
Count                 object
Neo                  float64
Unnamed: 19          float64
0:10:00              float64
Unnamed: 21          float64
Unnamed: 22          float64
Unnamed: 23          float64
Unnamed: 24          float64
Unnamed: 25          float64
Unnamed: 26          float64
Unnamed: 27          float64
Unnamed: 28          float64
Unnamed: 29          float64
Date.1               float64
Unnamed: 31          float64
Unnamed: 32          float64
Unnamed: 33           object
dtype: object

Number                 int64
User Query            object
Bot                   object
Bot Response          object
Time                  object
Intent Recognized     object
User ID               object
Channel               object
User Feedback        float64
Intent Feedback       object
Sentiment             object
Date                  object
Time.1                object
Date & Time           object
&                     object
T/F                   object
Diff                  object
Count                 object
Neo                  float64
Unnamed: 19          float64
0:10:00              float64
Unnamed: 21          float64
Unnamed: 22          float64
Unnamed: 23          float64
Unnamed: 24          float64
Unnamed: 25          float64
Unnamed: 26          float64
Unnamed: 27          float64
Unnamed: 28          float64
Unnamed: 29          float64
Date.1               float64
Unnamed: 31          float64
Unnamed: 32          float64
Unnamed: 33           object
dtype: object

,Number,User Query,Bot,Bot Response,Time,Intent Recognized,User ID,Channel,User Feedback,Intent Feedback,Sentiment,Date,Time.1,Date & Time,&,T/F,Diff,Count,Neo,Unnamed: 19,0:10:00,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Date.1,Unnamed: 31,Unnamed: 32,Unnamed: 33
0,1,Update Account,Kotak Securities,Choose one from the following,Sep 29 2022 10:18 AM,Update Account,00003eae-9dad-49cd-8b3d-e14f4949b4fa,Web,NaN,NaN,Neutral,29-Sep-22,10:18 AM,9/29/2022 10:18,Web00003eae-9dad-49cd-8b3d-e14f4949b4fa09/29/2...,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,Change Address,Kotak Securities,Please click below and select 'Service Request...,Sep 29 2022 10:19 AM,NaN,00003eae-9dad-49cd-8b3d-e14f4949b4fa,Web,NaN,NaN,Neutral,29-Sep-22,10:19 AM,9/29/2022 10:19,Web00003eae-9dad-49cd-8b3d-e14f4949b4fa09/29/2...,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

(915682, 34)

In [167]:
df10= pd.read_csv(r"E:\Analytics_Shared\Devika Patawari\Bot Analysis\Data\Webchat_whatspp_collated_new\collated_Oct.csv",encoding='"latin-1"')
df10.head(5)
df10.shape
df10.dtypes

,Number,User Query,Bot,Bot Response,Time,Intent Recognized,User ID,Channel,User Feedback,Intent Feedback,Sentiment,Date,Time.1,Date & Time,&,T/F,Diff,Count,Neo,Unnamed: 19,0:10:00,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Date.1
0,1,Want to talk to agent directly,Kotak Securities,Please select a category from the following.,Oct 02 2022 03:18 AM,NaN,12012349824,WhatsApp,NaN,NaN,Positive,2-Oct-22,3:18 AM,10/2/2022 3:18,WhatsApp1201234982410/02/2022 03:18:00,False,0:00:00,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,Chat with our Expert,Kotak Securities,Your WhatsApp number is not registered with us...,Oct 02 2022 03:18 AM,NaN,12012349824,WhatsApp,NaN,NaN,Neutral,2-Oct-22,3:18 AM,10/2/2022 3:18,WhatsApp1201234982410/02/2022 03:18:00,True,0:00:00,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,unidentified client,Kotak Securities,NaN,Oct 02 2022 03:18 AM,LiveChat Service for WhatsApp,12012349824,WhatsApp,NaN,NaN,Neutral,2-Oct-22,3:18 AM,10/2/2022 3:18,WhatsApp1201234982410/02/2022 03:18:00,True,0:00:00,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,LiveChat Service for WhatsApp,Kotak Securities,NaN,Oct 02 2022 03:18 AM,Chat with our expert,12012349824,WhatsApp,NaN,NaN,Neutral,2-Oct-22,3:18 AM,10/2/2022 3:18,WhatsApp1201234982410/02/2022 03:18:00,True,0:00:00,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,4,Kotak Securities,I&#39;m not sure if I can help you with your q...,Oct 02 2022 03:18 AM,NaN,12012349824,WhatsApp,NaN,NaN,Neutral,2-Oct-22,3:18 AM,10/2/2022 3:18,WhatsApp1201234982410/02/2022 03:18:00,True,0:00:00,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

(462153, 31)

Number                 int64
User Query            object
Bot                   object
Bot Response          object
Time                  object
Intent Recognized     object
User ID                int64
Channel               object
User Feedback        float64
Intent Feedback       object
Sentiment             object
Date                  object
Time.1                object
Date & Time           object
&                     object
T/F                     bool
Diff                  object
Count                  int64
Neo                  float64
Unnamed: 19          float64
0:10:00              float64
Unnamed: 21          float64
Unnamed: 22          float64
Unnamed: 23          float64
Unnamed: 24          float64
Unnamed: 25          float64
Unnamed: 26          float64
Unnamed: 27          float64
Unnamed: 28          float64
Unnamed: 29          float64
Date.1               float64
dtype: object

In [168]:
df11= pd.read_csv(r"E:\Analytics_Shared\Devika Patawari\Bot Analysis\Data\Webchat_whatspp_collated_new\collated_Nov.csv",encoding='"latin-1"')
df11.head(5)
df11.shape
df11.dtypes

,Number,User Query,Bot,Bot Response,Time,Intent Recognized,User ID,Channel,User Feedback,Intent Feedback,Sentiment,Date,Time.1,Date & Time,&,T/F,Diff,Count
0,1,Main Menu,Kotak Securities,"Hi! I&rsquo;m Maya, your virtual assistant fro...",Nov 25 2022 10:15 AM,Greetings,12016204891,WhatsApp,NaN,NaN,Positive,25-Nov-22,10:15 AM,11/25/2022 10:15,WhatsApp1201620489111/25/2022 10:15:00,False,0:00:00,1
1,2,Hi,Kotak Securities,"Hi! I&rsquo;m Maya, your virtual assistant fro...",Nov 25 2022 10:15 AM,Hi,12016204891,WhatsApp,NaN,NaN,Neutral,25-Nov-22,10:15 AM,11/25/2022 10:15,WhatsApp1201620489111/25/2022 10:15:00,True,0:00:00,0
2,3,Talk to CSE,Kotak Securities,Your WhatsApp number is not registered with us...,Nov 25 2022 10:16 AM,NaN,12016204891,WhatsApp,NaN,NaN,Neutral,25-Nov-22,10:16 AM,11/25/2022 10:16,WhatsApp1201620489111/25/2022 10:16:00,True,0:01:00,0
3,4,unidentified client,Kotak Securities,NaN,Nov 25 2022 10:16 AM,LiveChat Service for WhatsApp,12016204891,WhatsApp,NaN,NaN,Neutral,25-Nov-22,10:16 AM,11/25/2022 10:16,WhatsApp1201620489111/25/2022 10:16:00,True,0:00:00,0
4,5,LiveChat Service for WhatsApp,Kotak Securities,NaN,Nov 25 2022 10:16 AM,Chat with our expert,12016204891,WhatsApp,NaN,NaN,Neutral,25-Nov-22,10:16 AM,11/25/2022 10:16,WhatsApp1201620489111/25/2022 10:16:00,True,0:00:00,0

(603825, 18)

Number                 int64
User Query            object
Bot                   object
Bot Response          object
Time                  object
Intent Recognized     object
User ID                int64
Channel               object
User Feedback        float64
Intent Feedback       object
Sentiment             object
Date                  object
Time.1                object
Date & Time           object
&                     object
T/F                     bool
Diff                  object
Count                 object
dtype: object

In [169]:
df12= pd.read_csv(r"E:\Analytics_Shared\Devika Patawari\Bot Analysis\Data\Webchat_whatspp_collated_new\collated_Dec.csv",encoding='"latin-1"')
df12.head(5)
df12.shape
df12.dtypes

,Number,User Query,Bot,Bot Response,Time,Intent Recognized,User ID,Channel,User Feedback,Intent Feedback,Sentiment,Date,Time.1,Date & Time,&,T/F,Diff,Count
0,1,LiveChat Service for WhatsApp,Kotak Securities,NaN,Dec 30 2022 10:44 PM,Chat with our expert,1.201238e+10,WhatsApp,NaN,NaN,Neutral,30-Dec-22,10:44 PM,12/30/2022 22:44,WhatsApp1201238422612/30/2022 22:44:00,False,#VALUE!,1
1,2,Update Accounts,Kotak Securities,Choose one from the following,Dec 30 2022 10:44 PM,Update Account,1.201238e+10,WhatsApp,NaN,NaN,Neutral,30-Dec-22,10:44 PM,12/30/2022 22:44,WhatsApp1201238422612/30/2022 22:44:00,True,0:00:00,0
2,3,Main Menu,Kotak Securities,"Hi! I&rsquo;m Maya, your virtual assistant fro...",Dec 30 2022 10:44 PM,Greetings,1.201238e+10,WhatsApp,NaN,NaN,Positive,30-Dec-22,10:44 PM,12/30/2022 22:44,WhatsApp1201238422612/30/2022 22:44:00,True,0:00:00,0
3,4,Hi,Kotak Securities,"Hi! I&rsquo;m Maya, your virtual assistant fro...",Dec 30 2022 10:44 PM,Hi,1.201238e+10,WhatsApp,NaN,NaN,Neutral,30-Dec-22,10:44 PM,12/30/2022 22:44,WhatsApp1201238422612/30/2022 22:44:00,True,0:00:00,0
4,5,Want to enter registered mobile number or clie...,Kotak Securities,Kindly enter your registered&nbsp;mobile numbe...,Dec 30 2022 10:45 PM,NaN,1.201238e+10,WhatsApp,NaN,NaN,Neutral,30-Dec-22,10:45 PM,12/30/2022 22:45,WhatsApp1201238422612/30/2022 22:45:00,True,0:01:00,0

(735179, 18)

Number                 int64
User Query            object
Bot                   object
Bot Response          object
Time                  object
Intent Recognized     object
User ID              float64
Channel               object
User Feedback        float64
Intent Feedback       object
Sentiment             object
Date                  object
Time.1                object
Date & Time           object
&                     object
T/F                     bool
Diff                  object
Count                  int64
dtype: object

In [170]:
df_queries = pd.concat([df7,df8,df9,df10,df11,df12])
df_queries.shape
df_queries.drop_duplicates(keep='first', inplace=True)
df_queries.shape

(4280208, 34)

(4280208, 34)

In [171]:
df_queries.head()

,Number,User Query,Bot,Bot Response,Time,Intent Recognized,User ID,Channel,User Feedback,Intent Feedback,Sentiment,Date,Time.1,Date & Time,&,T/F,Diff,Count,Neo,Unnamed: 19,0:10:00,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Date.1,Unnamed: 31,Unnamed: 32,Unnamed: 33
0,1,Close Account,Kotak Securities,I&#39;m not sure if I can help you with your q...,Jul 01 2022 11:59 PM,NaN,9.20E+11,WhatsApp,NaN,NaN,Neutral,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,Existing Client,Kotak Securities,NaN,Jul 01 2022 11:59 PM,WA Self Service Authentication,9.20E+11,WhatsApp,NaN,NaN,Neutral,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,Update Accounts,Kotak Securities,Choose one from the following,Jul 01 2022 11:59 PM,Update Account,9.20E+11,WhatsApp,NaN,NaN,Neutral,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,Chat with our expert,Kotak Securities,Your LiveChat request has been registered with...,Jul 01 2022 11:58 PM,NaN,740a455f-b9aa-4b2c-94f4-aa1681ca3911,Web,NaN,NaN,Neutral,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,redirect,Kotak Securities,NaN,Jul 01 2022 11:58 PM,LiveChat Service for Web,740a455f-b9aa-4b2c-94f4-aa1681ca3911,Web,NaN,NaN,Neutral,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [172]:
df_queries.dtypes

Number                 int64
User Query            object
Bot                   object
Bot Response          object
Time                  object
Intent Recognized     object
User ID               object
Channel               object
User Feedback        float64
Intent Feedback       object
Sentiment             object
Date                  object
Time.1                object
Date & Time           object
&                     object
T/F                   object
Diff                  object
Count                 object
Neo                  float64
Unnamed: 19          float64
0:10:00              float64
Unnamed: 21          float64
Unnamed: 22          float64
Unnamed: 23          float64
Unnamed: 24          float64
Unnamed: 25          float64
Unnamed: 26          float64
Unnamed: 27          float64
Unnamed: 28          float64
Unnamed: 29          float64
Date.1               float64
Unnamed: 31          float64
Unnamed: 32          float64
Unnamed: 33           object
dtype: object

In [173]:
df_queries['Channel'].unique()

array(['WhatsApp', 'Web', nan], dtype=object)

In [174]:
df_queries_WA = df_queries[df_queries['Channel'] == 'WhatsApp']
df_queries_WA.head()
df_queries_WA.shape

,Number,User Query,Bot,Bot Response,Time,Intent Recognized,User ID,Channel,User Feedback,Intent Feedback,Sentiment,Date,Time.1,Date & Time,&,T/F,Diff,Count,Neo,Unnamed: 19,0:10:00,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Date.1,Unnamed: 31,Unnamed: 32,Unnamed: 33
0,1,Close Account,Kotak Securities,I&#39;m not sure if I can help you with your q...,Jul 01 2022 11:59 PM,NaN,9.20E+11,WhatsApp,NaN,NaN,Neutral,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,Existing Client,Kotak Securities,NaN,Jul 01 2022 11:59 PM,WA Self Service Authentication,9.20E+11,WhatsApp,NaN,NaN,Neutral,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,Update Accounts,Kotak Securities,Choose one from the following,Jul 01 2022 11:59 PM,Update Account,9.20E+11,WhatsApp,NaN,NaN,Neutral,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,7,Hi,Kotak Securities,"Hi! I&rsquo;m Maya, your virtual assistant fro...",Jul 01 2022 11:58 PM,Greetings,9.20E+11,WhatsApp,NaN,NaN,Neutral,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,21,Hi,Kotak Securities,"Hi! I&rsquo;m Maya, your virtual assistant fro...",Jul 01 2022 11:57 PM,Greetings,9.19E+11,WhatsApp,NaN,NaN,Neutral,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

(3481261, 34)

In [175]:
df_queries_WA['Time1'] = pd.to_datetime(df_queries_WA['Time'], errors="coerce")

In [176]:
df_queries_WA.head()
df_queries_WA.dtypes

,Number,User Query,Bot,Bot Response,Time,Intent Recognized,User ID,Channel,User Feedback,Intent Feedback,Sentiment,Date,Time.1,Date & Time,&,T/F,Diff,Count,Neo,Unnamed: 19,0:10:00,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Date.1,Unnamed: 31,Unnamed: 32,Unnamed: 33,Time1
0,1,Close Account,Kotak Securities,I&#39;m not sure if I can help you with your q...,Jul 01 2022 11:59 PM,NaN,9.20E+11,WhatsApp,NaN,NaN,Neutral,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022-07-01 23:59:00
1,2,Existing Client,Kotak Securities,NaN,Jul 01 2022 11:59 PM,WA Self Service Authentication,9.20E+11,WhatsApp,NaN,NaN,Neutral,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022-07-01 23:59:00
2,3,Update Accounts,Kotak Securities,Choose one from the following,Jul 01 2022 11:59 PM,Update Account,9.20E+11,WhatsApp,NaN,NaN,Neutral,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022-07-01 23:59:00
6,7,Hi,Kotak Securities,"Hi! I&rsquo;m Maya, your virtual assistant fro...",Jul 01 2022 11:58 PM,Greetings,9.20E+11,WhatsApp,NaN,NaN,Neutral,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022-07-01 23:58:00
20,21,Hi,Kotak Securities,"Hi! I&rsquo;m Maya, your virtual assistant fro...",Jul 01 2022 11:57 PM,Greetings,9.19E+11,WhatsApp,NaN,NaN,Neutral,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022-07-01 23:57:00

Number                        int64
User Query                   object
Bot                          object
Bot Response                 object
Time                         object
Intent Recognized            object
User ID                      object
Channel                      object
User Feedback               float64
Intent Feedback              object
Sentiment                    object
Date                         object
Time.1                       object
Date & Time                  object
&                            object
T/F                          object
Diff                         object
Count                        object
Neo                         float64
Unnamed: 19                 float64
0:10:00                     float64
Unnamed: 21                 float64
Unnamed: 22                 float64
Unnamed: 23                 float64
Unnamed: 24                 float64
Unnamed: 25                 float64
Unnamed: 26                 float64
Unnamed: 27                 float64
Unnamed: 28                 float64
Unnamed: 29                 float64
Date.1                      float64
Unnamed: 31                 float64
Unnamed: 32                 float64
Unnamed: 33                  object
Time1                datetime64[ns]
dtype: object

In [177]:
data = df_queries_WA[['Number','User ID','Time1','User Query','Intent Recognized','Bot Response']]

In [178]:
data['Date_1'] = pd.to_datetime(data['Time1'],format='%Y-%m-%d')

In [179]:
data['month'] = data['Time1'].dt.month

In [180]:
data.head()
data.shape

,Number,User ID,Time1,User Query,Intent Recognized,Bot Response,Date_1,month
0,1,9.20E+11,2022-07-01 23:59:00,Close Account,NaN,I&#39;m not sure if I can help you with your q...,2022-07-01 23:59:00,7.0
1,2,9.20E+11,2022-07-01 23:59:00,Existing Client,WA Self Service Authentication,NaN,2022-07-01 23:59:00,7.0
2,3,9.20E+11,2022-07-01 23:59:00,Update Accounts,Update Account,Choose one from the following,2022-07-01 23:59:00,7.0
6,7,9.20E+11,2022-07-01 23:58:00,Hi,Greetings,"Hi! I&rsquo;m Maya, your virtual assistant fro...",2022-07-01 23:58:00,7.0
20,21,9.19E+11,2022-07-01 23:57:00,Hi,Greetings,"Hi! I&rsquo;m Maya, your virtual assistant fro...",2022-07-01 23:57:00,7.0

(3481261, 8)

In [181]:
data.dtypes

Number                        int64
User ID                      object
Time1                datetime64[ns]
User Query                   object
Intent Recognized            object
Bot Response                 object
Date_1               datetime64[ns]
month                       float64
dtype: object

In [182]:
data['User ID'] = data['User ID'].astype(str)
data['Date_str'] = data['Date_1'].astype(str)
data['User Query'] = data['User Query'].astype(str)
data['Intent Recognized'] = data['Intent Recognized'].astype(str)
data['Bot Response'] = data['Bot Response'].astype(str)

In [183]:
data.dtypes

Number                        int64
User ID                      object
Time1                datetime64[ns]
User Query                   object
Intent Recognized            object
Bot Response                 object
Date_1               datetime64[ns]
month                       float64
Date_str                     object
dtype: object

# Jul_month_Base_Data

In [184]:
#filter Month - Jul
data_7 = data[data['month']== 7]
data_7.shape

#Sort Data 
data_Jul = data_7.sort_values(by=['User ID','Time1','Number'], ascending=[1,1,0])
data_Jul = data_Jul[['User ID','Time1','User Query','Intent Recognized','Bot Response','Date_str','month']]
data_Jul.head()

#Define Sessions

data_Jul['Time'] = pd.to_datetime(data_Jul['Time1'])
data_Jul['diffs'] = data_Jul.groupby('User ID')['Time1'].diff()
data_Jul['break'] = data_Jul['diffs'] >= pd.Timedelta('10 min')

data_Jul['sessions'] = data_Jul.groupby('User ID')['break'].cumsum().apply(lambda x: 'session_{}'.format(x+1))
data_Jul.head(2)

#For Joining convert Variable to str

data_Jul['id_str']=data_Jul['User ID'].astype('str')
data_Jul['Date_str2']=data_Jul['Date_str'].astype('str')
data_Jul['Session_str']=data_Jul['sessions'].astype('str')

#Concat all three variables for joining
data_Jul['concat'] = data_Jul['id_str'] + data_Jul['Date_str2']+ data_Jul['Session_str']

# Create Unique Base for Joining
data_Base_Jul=data_Jul[['User ID','Date_str2','concat','month','sessions']]
data_Base_Jul.drop_duplicates(keep='first', inplace=True)
data_Base_Jul.head()
data_Base_Jul.shape

#User Query Transpose
data_Jul_User = data_Jul.groupby(['User ID','sessions','month','concat'])['User Query'].apply(lambda x: ' > '.join(x)).reset_index()
data_Jul_User['User Query'] = data_Jul_User['User Query'].str.lower()
data_Jul_User.head()

#Bot Response Transpose
data_Jul_Bot = data_Jul.groupby(['User ID','sessions','month','concat'])['Bot Response'].apply(lambda x: ' > '.join(x)).reset_index()
data_Jul_Bot['Bot Response'] = data_Jul_Bot['Bot Response'].str.lower()
data_Jul_Bot.head()

#Intent Response Transpose
data_Jul_intent = data_Jul.groupby(['User ID','sessions','month','concat'])['Intent Recognized'].apply(lambda x: ' > '.join(x)).reset_index()
data_Jul_intent['Intent Recognized'] = data_Jul_intent['Intent Recognized'].str.lower()
data_Jul_intent.head()

#Merge1
data_Base_Jul['key1'] = data_Base_Jul.concat.str.strip()
data_Jul_User['key1'] = data_Jul_User.concat.str.strip()
df_merge1 = pd.merge(data_Base_Jul,data_Jul_User, how='left', left_on=['key1'], right_on=['key1'])
df_merge1.head()
df_merge1.columns
df_merge1.drop(['key1','User ID_y', 'sessions_y', 'month_y', 'concat_y'],axis=1, inplace=True)
df_merge1.head(2)


#Merge2
df_merge1['key1'] = df_merge1.concat_x.str.strip()
data_Jul_Bot['key1'] = data_Jul_Bot.concat.str.strip()
df_merge2 = pd.merge(df_merge1,data_Jul_Bot, how='left', left_on=['key1'], right_on=['key1'])
df_merge2.head()
df_merge2.drop(['User ID_x', 'concat_x', 'month_x', 'sessions_x','key1'],axis=1, inplace=True)
df_merge2.head(2)

#Merge3
df_merge2['key1'] = df_merge2.concat.str.strip()
data_Jul_intent['key1'] = data_Jul_intent.concat.str.strip()
df_merge3 = pd.merge(df_merge2,data_Jul_intent, how='left', left_on=['key1'], right_on=['key1'])
df_merge3.head()
df_merge3.drop(['User ID_x', 'sessions_x', 'month_x', 'concat_x','key1'],axis=1, inplace=True)
df_merge3.head(2)

#Final File
df_Final_Jul=df_merge3.rename(columns={'User ID_y':'ID','month_y':'month','concat_y':'concat','sessions_y':'sessions'}) 
df_Final_Jul.head()
df_Final_Jul = df_Final_Jul[['ID', 'sessions', 'month', 'concat','User Query', 'Bot Response','Intent Recognized']]
df_Final_Jul.head(2)
df_Final_Jul.shape

(571188, 9)

,User ID,Time1,User Query,Intent Recognized,Bot Response,Date_str,month
178257,12016162460,2022-07-08 08:51:00,Hi,Greetings,"Hi! I&rsquo;m Maya, your virtual assistant fro...",2022-07-08 08:51:00,7.0
178248,12016162460,2022-07-08 08:51:00,FAQs,FAQs,"Sure, let me help you with that. Please select...",2022-07-08 08:51:00,7.0
178244,12016162460,2022-07-08 08:51:00,Dormant a/c Reactivation,Dormant account reactivation,Please select one of the following options or ...,2022-07-08 08:51:00,7.0
178238,12016162460,2022-07-08 08:51:00,LiveChat Service for WhatsApp,Chat with our expert,nan,2022-07-08 08:51:00,7.0
178237,12016162460,2022-07-08 08:51:00,unidentified client,LiveChat Service for WhatsApp,nan,2022-07-08 08:51:00,7.0

,User ID,Time1,User Query,Intent Recognized,Bot Response,Date_str,month,Time,diffs,break,sessions
178257,12016162460,2022-07-08 08:51:00,Hi,Greetings,"Hi! I&rsquo;m Maya, your virtual assistant fro...",2022-07-08 08:51:00,7.0,2022-07-08 08:51:00,NaT,False,session_1
178248,12016162460,2022-07-08 08:51:00,FAQs,FAQs,"Sure, let me help you with that. Please select...",2022-07-08 08:51:00,7.0,2022-07-08 08:51:00,0 days,False,session_1

,User ID,Date_str2,concat,month,sessions
178257,12016162460,2022-07-08 08:51:00,120161624602022-07-08 08:51:00session_1,7.0,session_1
178198,12016162460,2022-07-08 08:52:00,120161624602022-07-08 08:52:00session_1,7.0,session_1
213929,12016162460,2022-07-11 13:12:00,120161624602022-07-11 13:12:00session_2,7.0,session_2
213916,12016162460,2022-07-11 13:13:00,120161624602022-07-11 13:13:00session_2,7.0,session_2
123156,12019161504,2022-07-06 09:54:00,120191615042022-07-06 09:54:00session_1,7.0,session_1

(86978, 5)

,User ID,sessions,month,concat,User Query
0,12016162460,session_1,7.0,120161624602022-07-08 08:51:00session_1,hi > faqs > dormant a/c reactivation > livecha...
1,12016162460,session_1,7.0,120161624602022-07-08 08:52:00session_1,want to talk to agent directly
2,12016162460,session_2,7.0,120161624602022-07-11 13:12:00session_2,hi > update accounts
3,12016162460,session_2,7.0,120161624602022-07-11 13:13:00session_2,livechat service for whatsapp > unidentified c...
4,12019161504,session_1,7.0,120191615042022-07-06 09:54:00session_1,hello

,User ID,sessions,month,concat,Bot Response
0,12016162460,session_1,7.0,120161624602022-07-08 08:51:00session_1,"hi! i&rsquo;m maya, your virtual assistant fro..."
1,12016162460,session_1,7.0,120161624602022-07-08 08:52:00session_1,your livechat request has been registered with...
2,12016162460,session_2,7.0,120161624602022-07-11 13:12:00session_2,"hi! i&rsquo;m maya, your virtual assistant fro..."
3,12016162460,session_2,7.0,120161624602022-07-11 13:13:00session_2,nan > nan > your whatsapp number is not regist...
4,12019161504,session_1,7.0,120191615042022-07-06 09:54:00session_1,"hi! i&rsquo;m maya, your virtual assistant fro..."

,User ID,sessions,month,concat,Intent Recognized
0,12016162460,session_1,7.0,120161624602022-07-08 08:51:00session_1,greetings > faqs > dormant account reactivatio...
1,12016162460,session_1,7.0,120161624602022-07-08 08:52:00session_1,nan
2,12016162460,session_2,7.0,120161624602022-07-11 13:12:00session_2,greetings > update account
3,12016162460,session_2,7.0,120161624602022-07-11 13:13:00session_2,chat with our expert > livechat service for wh...
4,12019161504,session_1,7.0,120191615042022-07-06 09:54:00session_1,greetings

,User ID_x,Date_str2,concat_x,month_x,sessions_x,key1,User ID_y,sessions_y,month_y,concat_y,User Query
0,12016162460,2022-07-08 08:51:00,120161624602022-07-08 08:51:00session_1,7.0,session_1,120161624602022-07-08 08:51:00session_1,12016162460,session_1,7.0,120161624602022-07-08 08:51:00session_1,hi > faqs > dormant a/c reactivation > livecha...
1,12016162460,2022-07-08 08:52:00,120161624602022-07-08 08:52:00session_1,7.0,session_1,120161624602022-07-08 08:52:00session_1,12016162460,session_1,7.0,120161624602022-07-08 08:52:00session_1,want to talk to agent directly
2,12016162460,2022-07-11 13:12:00,120161624602022-07-11 13:12:00session_2,7.0,session_2,120161624602022-07-11 13:12:00session_2,12016162460,session_2,7.0,120161624602022-07-11 13:12:00session_2,hi > update accounts
3,12016162460,2022-07-11 13:13:00,120161624602022-07-11 13:13:00session_2,7.0,session_2,120161624602022-07-11 13:13:00session_2,12016162460,session_2,7.0,120161624602022-07-11 13:13:00session_2,livechat service for whatsapp > unidentified c...
4,12019161504,2022-07-06 09:54:00,120191615042022-07-06 09:54:00session_1,7.0,session_1,120191615042022-07-06 09:54:00session_1,12019161504,session_1,7.0,120191615042022-07-06 09:54:00session_1,hello

Index(['User ID_x', 'Date_str2', 'concat_x', 'month_x', 'sessions_x', 'key1',
       'User ID_y', 'sessions_y', 'month_y', 'concat_y', 'User Query'],
      dtype='object')

,User ID_x,Date_str2,concat_x,month_x,sessions_x,User Query
0,12016162460,2022-07-08 08:51:00,120161624602022-07-08 08:51:00session_1,7.0,session_1,hi > faqs > dormant a/c reactivation > livecha...
1,12016162460,2022-07-08 08:52:00,120161624602022-07-08 08:52:00session_1,7.0,session_1,want to talk to agent directly

,User ID_x,Date_str2,concat_x,month_x,sessions_x,User Query,key1,User ID,sessions,month,concat,Bot Response
0,12016162460,2022-07-08 08:51:00,120161624602022-07-08 08:51:00session_1,7.0,session_1,hi > faqs > dormant a/c reactivation > livecha...,120161624602022-07-08 08:51:00session_1,12016162460,session_1,7.0,120161624602022-07-08 08:51:00session_1,"hi! i&rsquo;m maya, your virtual assistant fro..."
1,12016162460,2022-07-08 08:52:00,120161624602022-07-08 08:52:00session_1,7.0,session_1,want to talk to agent directly,120161624602022-07-08 08:52:00session_1,12016162460,session_1,7.0,120161624602022-07-08 08:52:00session_1,your livechat request has been registered with...
2,12016162460,2022-07-11 13:12:00,120161624602022-07-11 13:12:00session_2,7.0,session_2,hi > update accounts,120161624602022-07-11 13:12:00session_2,12016162460,session_2,7.0,120161624602022-07-11 13:12:00session_2,"hi! i&rsquo;m maya, your virtual assistant fro..."
3,12016162460,2022-07-11 13:13:00,120161624602022-07-11 13:13:00session_2,7.0,session_2,livechat service for whatsapp > unidentified c...,120161624602022-07-11 13:13:00session_2,12016162460,session_2,7.0,120161624602022-07-11 13:13:00session_2,nan > nan > your whatsapp number is not regist...
4,12019161504,2022-07-06 09:54:00,120191615042022-07-06 09:54:00session_1,7.0,session_1,hello,120191615042022-07-06 09:54:00session_1,12019161504,session_1,7.0,120191615042022-07-06 09:54:00session_1,"hi! i&rsquo;m maya, your virtual assistant fro..."

,Date_str2,User Query,User ID,sessions,month,concat,Bot Response
0,2022-07-08 08:51:00,hi > faqs > dormant a/c reactivation > livecha...,12016162460,session_1,7.0,120161624602022-07-08 08:51:00session_1,"hi! i&rsquo;m maya, your virtual assistant fro..."
1,2022-07-08 08:52:00,want to talk to agent directly,12016162460,session_1,7.0,120161624602022-07-08 08:52:00session_1,your livechat request has been registered with...

,Date_str2,User Query,User ID_x,sessions_x,month_x,concat_x,Bot Response,key1,User ID_y,sessions_y,month_y,concat_y,Intent Recognized
0,2022-07-08 08:51:00,hi > faqs > dormant a/c reactivation > livecha...,12016162460,session_1,7.0,120161624602022-07-08 08:51:00session_1,"hi! i&rsquo;m maya, your virtual assistant fro...",120161624602022-07-08 08:51:00session_1,12016162460,session_1,7.0,120161624602022-07-08 08:51:00session_1,greetings > faqs > dormant account reactivatio...
1,2022-07-08 08:52:00,want to talk to agent directly,12016162460,session_1,7.0,120161624602022-07-08 08:52:00session_1,your livechat request has been registered with...,120161624602022-07-08 08:52:00session_1,12016162460,session_1,7.0,120161624602022-07-08 08:52:00session_1,nan
2,2022-07-11 13:12:00,hi > update accounts,12016162460,session_2,7.0,120161624602022-07-11 13:12:00session_2,"hi! i&rsquo;m maya, your virtual assistant fro...",120161624602022-07-11 13:12:00session_2,12016162460,session_2,7.0,120161624602022-07-11 13:12:00session_2,greetings > update account
3,2022-07-11 13:13:00,livechat service for whatsapp > unidentified c...,12016162460,session_2,7.0,120161624602022-07-11 13:13:00session_2,nan > nan > your whatsapp number is not regist...,120161624602022-07-11 13:13:00session_2,12016162460,session_2,7.0,120161624602022-07-11 13:13:00session_2,chat with our expert > livechat service for wh...
4,2022-07-06 09:54:00,hello,12019161504,session_1,7.0,120191615042022-07-06 09:54:00session_1,"hi! i&rsquo;m maya, your virtual assistant fro...",120191615042022-07-06 09:54:00session_1,12019161504,session_1,7.0,120191615042022-07-06 09:54:00session_1,greetings

,Date_str2,User Query,Bot Response,User ID_y,sessions_y,month_y,concat_y,Intent Recognized
0,2022-07-08 08:51:00,hi > faqs > dormant a/c reactivation > livecha...,"hi! i&rsquo;m maya, your virtual assistant fro...",12016162460,session_1,7.0,120161624602022-07-08 08:51:00session_1,greetings > faqs > dormant account reactivatio...
1,2022-07-08 08:52:00,want to talk to agent directly,your livechat request has been registered with...,12016162460,session_1,7.0,120161624602022-07-08 08:52:00session_1,nan

,Date_str2,User Query,Bot Response,ID,sessions,month,concat,Intent Recognized
0,2022-07-08 08:51:00,hi > faqs > dormant a/c reactivation > livecha...,"hi! i&rsquo;m maya, your virtual assistant fro...",12016162460,session_1,7.0,120161624602022-07-08 08:51:00session_1,greetings > faqs > dormant account reactivatio...
1,2022-07-08 08:52:00,want to talk to agent directly,your livechat request has been registered with...,12016162460,session_1,7.0,120161624602022-07-08 08:52:00session_1,nan
2,2022-07-11 13:12:00,hi > update accounts,"hi! i&rsquo;m maya, your virtual assistant fro...",12016162460,session_2,7.0,120161624602022-07-11 13:12:00session_2,greetings > update account
3,2022-07-11 13:13:00,livechat service for whatsapp > unidentified c...,nan > nan > your whatsapp number is not regist...,12016162460,session_2,7.0,120161624602022-07-11 13:13:00session_2,chat with our expert > livechat service for wh...
4,2022-07-06 09:54:00,hello,"hi! i&rsquo;m maya, your virtual assistant fro...",12019161504,session_1,7.0,120191615042022-07-06 09:54:00session_1,greetings

,ID,sessions,month,concat,User Query,Bot Response,Intent Recognized
0,12016162460,session_1,7.0,120161624602022-07-08 08:51:00session_1,hi > faqs > dormant a/c reactivation > livecha...,"hi! i&rsquo;m maya, your virtual assistant fro...",greetings > faqs > dormant account reactivatio...
1,12016162460,session_1,7.0,120161624602022-07-08 08:52:00session_1,want to talk to agent directly,your livechat request has been registered with...,nan

(86978, 7)

# Aug_month_Base_Data

In [186]:
#filter Month - Aug
data_8 = data[data['month']== 8]
data_8.shape

#Sort Data 
data_Aug = data_8.sort_values(by=['User ID','Time1','Number'], ascending=[1,1,0])
data_Aug = data_Aug[['User ID','Time1','User Query','Intent Recognized','Bot Response','Date_str','month']]
data_Aug.head()

#Define Sessions

data_Aug['Time'] = pd.to_datetime(data_Aug['Time1'])
data_Aug['diffs'] = data_Aug.groupby('User ID')['Time1'].diff()
data_Aug['break'] = data_Aug['diffs'] >= pd.Timedelta('10 min')
data_Aug['sessions'] = data_Aug.groupby('User ID')['break'].cumsum().apply(lambda x: 'session_{}'.format(x+1))
data_Aug.head(2)

#For Joining convert Variable to str

data_Aug['id_str']=data_Aug['User ID'].astype('str')
data_Aug['Date_str2']=data_Aug['Date_str'].astype('str')
data_Aug['Session_str']=data_Aug['sessions'].astype('str')

#Concat all three variables for joining
data_Aug['concat'] = data_Aug['id_str'] + data_Aug['Date_str2']+ data_Aug['Session_str']

# Create Unique Base for Joining
data_Base_Aug=data_Aug[['User ID','Date_str2','concat','month','sessions']]
data_Base_Aug.drop_duplicates(keep='first', inplace=True)
data_Base_Aug.head()
data_Base_Aug.shape

#User Query Transpose
data_Aug_User = data_Aug.groupby(['User ID','sessions','month','concat'])['User Query'].apply(lambda x: ' > '.join(x)).reset_index()
data_Aug_User['User Query'] = data_Aug_User['User Query'].str.lower()
data_Aug_User.head()

#Bot Response Transpose
data_Aug_Bot = data_Aug.groupby(['User ID','sessions','month','concat'])['Bot Response'].apply(lambda x: ' > '.join(x)).reset_index()
data_Aug_Bot['Bot Response'] = data_Aug_Bot['Bot Response'].str.lower()
data_Aug_Bot.head()

#Intent Response Transpose
data_Aug_intent = data_Aug.groupby(['User ID','sessions','month','concat'])['Intent Recognized'].apply(lambda x: ' > '.join(x)).reset_index()
data_Aug_intent['Intent Recognized'] = data_Aug_intent['Intent Recognized'].str.lower()
data_Aug_intent.head()

#Merge1
data_Base_Aug['key1'] = data_Base_Aug.concat.str.strip()
data_Aug_User['key1'] = data_Aug_User.concat.str.strip()
df_merge1 = pd.merge(data_Base_Aug,data_Aug_User, how='left', left_on=['key1'], right_on=['key1'])
df_merge1.head()
df_merge1.columns
df_merge1.drop(['key1','User ID_y', 'sessions_y', 'month_y', 'concat_y'],axis=1, inplace=True)
df_merge1.head(2)


#Merge2
df_merge1['key1'] = df_merge1.concat_x.str.strip()
data_Aug_Bot['key1'] = data_Aug_Bot.concat.str.strip()
df_merge2 = pd.merge(df_merge1,data_Aug_Bot, how='left', left_on=['key1'], right_on=['key1'])
df_merge2.head()
df_merge2.drop(['User ID_x', 'concat_x', 'month_x', 'sessions_x','key1'],axis=1, inplace=True)
df_merge2.head(2)

#Merge3
df_merge2['key1'] = df_merge2.concat.str.strip()
data_Aug_intent['key1'] = data_Aug_intent.concat.str.strip()
df_merge3 = pd.merge(df_merge2,data_Aug_intent, how='left', left_on=['key1'], right_on=['key1'])
df_merge3.head()
df_merge3.drop(['User ID_x', 'sessions_x', 'month_x', 'concat_x','key1'],axis=1, inplace=True)
df_merge3.head(2)

#Final File
df_Final_Aug=df_merge3.rename(columns={'User ID_y':'ID','month_y':'month','concat_y':'concat','sessions_y':'sessions'}) 
df_Final_Aug.head()
df_Final_Aug = df_Final_Aug[['ID', 'sessions', 'month', 'concat','User Query', 'Bot Response','Intent Recognized']]
df_Final_Aug.head(2)
df_Final_Aug.shape

(569730, 9)

,User ID,Time1,User Query,Intent Recognized,Bot Response,Date_str,month
191573,12012303393,2022-08-16 07:41:00,LiveChat Service for WhatsApp,Chat with our expert,nan,2022-08-16 07:41:00,8.0
191572,12012303393,2022-08-16 07:41:00,identified client single client code,LiveChat Service for WhatsApp,nan,2022-08-16 07:41:00,8.0
191571,12012303393,2022-08-16 07:41:00,Chat with an Expert,nan,Do you wish to self-authenticate?,2022-08-16 07:41:00,8.0
191570,12012303393,2022-08-16 07:41:00,Yes,nan,Kindly answer the below security question: PAN...,2022-08-16 07:41:00,8.0
191574,12012303393,2022-08-16 07:42:00,no,nan,Invalid AnswerKindly provide a valid answer to...,2022-08-16 07:42:00,8.0

,User ID,Time1,User Query,Intent Recognized,Bot Response,Date_str,month,Time,diffs,break,sessions
191573,12012303393,2022-08-16 07:41:00,LiveChat Service for WhatsApp,Chat with our expert,nan,2022-08-16 07:41:00,8.0,2022-08-16 07:41:00,NaT,False,session_1
191572,12012303393,2022-08-16 07:41:00,identified client single client code,LiveChat Service for WhatsApp,nan,2022-08-16 07:41:00,8.0,2022-08-16 07:41:00,0 days,False,session_1

,User ID,Date_str2,concat,month,sessions
191573,12012303393,2022-08-16 07:41:00,120123033932022-08-16 07:41:00session_1,8.0,session_1
191574,12012303393,2022-08-16 07:42:00,120123033932022-08-16 07:42:00session_1,8.0,session_1
191576,12012303393,2022-08-16 07:43:00,120123033932022-08-16 07:43:00session_1,8.0,session_1
191577,12012303393,2022-08-16 07:44:00,120123033932022-08-16 07:44:00session_1,8.0,session_1
191578,12012303393,2022-08-16 07:45:00,120123033932022-08-16 07:45:00session_1,8.0,session_1

(92115, 5)

,User ID,sessions,month,concat,User Query
0,12012303393,session_1,8.0,120123033932022-08-16 07:41:00session_1,livechat service for whatsapp > identified cli...
1,12012303393,session_1,8.0,120123033932022-08-16 07:42:00session_1,no
2,12012303393,session_1,8.0,120123033932022-08-16 07:43:00session_1,********** > resend
3,12012303393,session_1,8.0,120123033932022-08-16 07:44:00session_1,**********
4,12012303393,session_1,8.0,120123033932022-08-16 07:45:00session_1,login help

,User ID,sessions,month,concat,Bot Response
0,12012303393,session_1,8.0,120123033932022-08-16 07:41:00session_1,nan > nan > do you wish to self-authenticate? ...
1,12012303393,session_1,8.0,120123033932022-08-16 07:42:00session_1,invalid answerkindly provide a valid answer to...
2,12012303393,session_1,8.0,120123033932022-08-16 07:43:00session_1,kindly enter the otp we have sent on your regi...
3,12012303393,session_1,8.0,120123033932022-08-16 07:44:00session_1,you are successfully authenticated with client...
4,12012303393,session_1,8.0,120123033932022-08-16 07:45:00session_1,"due to high chat volumes, there may be a delay..."

,User ID,sessions,month,concat,Intent Recognized
0,12012303393,session_1,8.0,120123033932022-08-16 07:41:00session_1,chat with our expert > livechat service for wh...
1,12012303393,session_1,8.0,120123033932022-08-16 07:42:00session_1,nan
2,12012303393,session_1,8.0,120123033932022-08-16 07:43:00session_1,nan > nan
3,12012303393,session_1,8.0,120123033932022-08-16 07:44:00session_1,nan
4,12012303393,session_1,8.0,120123033932022-08-16 07:45:00session_1,nan

,User ID_x,Date_str2,concat_x,month_x,sessions_x,key1,User ID_y,sessions_y,month_y,concat_y,User Query
0,12012303393,2022-08-16 07:41:00,120123033932022-08-16 07:41:00session_1,8.0,session_1,120123033932022-08-16 07:41:00session_1,12012303393,session_1,8.0,120123033932022-08-16 07:41:00session_1,livechat service for whatsapp > identified cli...
1,12012303393,2022-08-16 07:42:00,120123033932022-08-16 07:42:00session_1,8.0,session_1,120123033932022-08-16 07:42:00session_1,12012303393,session_1,8.0,120123033932022-08-16 07:42:00session_1,no
2,12012303393,2022-08-16 07:43:00,120123033932022-08-16 07:43:00session_1,8.0,session_1,120123033932022-08-16 07:43:00session_1,12012303393,session_1,8.0,120123033932022-08-16 07:43:00session_1,********** > resend
3,12012303393,2022-08-16 07:44:00,120123033932022-08-16 07:44:00session_1,8.0,session_1,120123033932022-08-16 07:44:00session_1,12012303393,session_1,8.0,120123033932022-08-16 07:44:00session_1,**********
4,12012303393,2022-08-16 07:45:00,120123033932022-08-16 07:45:00session_1,8.0,session_1,120123033932022-08-16 07:45:00session_1,12012303393,session_1,8.0,120123033932022-08-16 07:45:00session_1,login help

Index(['User ID_x', 'Date_str2', 'concat_x', 'month_x', 'sessions_x', 'key1',
       'User ID_y', 'sessions_y', 'month_y', 'concat_y', 'User Query'],
      dtype='object')

,User ID_x,Date_str2,concat_x,month_x,sessions_x,User Query
0,12012303393,2022-08-16 07:41:00,120123033932022-08-16 07:41:00session_1,8.0,session_1,livechat service for whatsapp > identified cli...
1,12012303393,2022-08-16 07:42:00,120123033932022-08-16 07:42:00session_1,8.0,session_1,no

,User ID_x,Date_str2,concat_x,month_x,sessions_x,User Query,key1,User ID,sessions,month,concat,Bot Response
0,12012303393,2022-08-16 07:41:00,120123033932022-08-16 07:41:00session_1,8.0,session_1,livechat service for whatsapp > identified cli...,120123033932022-08-16 07:41:00session_1,12012303393,session_1,8.0,120123033932022-08-16 07:41:00session_1,nan > nan > do you wish to self-authenticate? ...
1,12012303393,2022-08-16 07:42:00,120123033932022-08-16 07:42:00session_1,8.0,session_1,no,120123033932022-08-16 07:42:00session_1,12012303393,session_1,8.0,120123033932022-08-16 07:42:00session_1,invalid answerkindly provide a valid answer to...
2,12012303393,2022-08-16 07:43:00,120123033932022-08-16 07:43:00session_1,8.0,session_1,********** > resend,120123033932022-08-16 07:43:00session_1,12012303393,session_1,8.0,120123033932022-08-16 07:43:00session_1,kindly enter the otp we have sent on your regi...
3,12012303393,2022-08-16 07:44:00,120123033932022-08-16 07:44:00session_1,8.0,session_1,**********,120123033932022-08-16 07:44:00session_1,12012303393,session_1,8.0,120123033932022-08-16 07:44:00session_1,you are successfully authenticated with client...
4,12012303393,2022-08-16 07:45:00,120123033932022-08-16 07:45:00session_1,8.0,session_1,login help,120123033932022-08-16 07:45:00session_1,12012303393,session_1,8.0,120123033932022-08-16 07:45:00session_1,"due to high chat volumes, there may be a delay..."

,Date_str2,User Query,User ID,sessions,month,concat,Bot Response
0,2022-08-16 07:41:00,livechat service for whatsapp > identified cli...,12012303393,session_1,8.0,120123033932022-08-16 07:41:00session_1,nan > nan > do you wish to self-authenticate? ...
1,2022-08-16 07:42:00,no,12012303393,session_1,8.0,120123033932022-08-16 07:42:00session_1,invalid answerkindly provide a valid answer to...

,Date_str2,User Query,User ID_x,sessions_x,month_x,concat_x,Bot Response,key1,User ID_y,sessions_y,month_y,concat_y,Intent Recognized
0,2022-08-16 07:41:00,livechat service for whatsapp > identified cli...,12012303393,session_1,8.0,120123033932022-08-16 07:41:00session_1,nan > nan > do you wish to self-authenticate? ...,120123033932022-08-16 07:41:00session_1,12012303393,session_1,8.0,120123033932022-08-16 07:41:00session_1,chat with our expert > livechat service for wh...
1,2022-08-16 07:42:00,no,12012303393,session_1,8.0,120123033932022-08-16 07:42:00session_1,invalid answerkindly provide a valid answer to...,120123033932022-08-16 07:42:00session_1,12012303393,session_1,8.0,120123033932022-08-16 07:42:00session_1,nan
2,2022-08-16 07:43:00,********** > resend,12012303393,session_1,8.0,120123033932022-08-16 07:43:00session_1,kindly enter the otp we have sent on your regi...,120123033932022-08-16 07:43:00session_1,12012303393,session_1,8.0,120123033932022-08-16 07:43:00session_1,nan > nan
3,2022-08-16 07:44:00,**********,12012303393,session_1,8.0,120123033932022-08-16 07:44:00session_1,you are successfully authenticated with client...,120123033932022-08-16 07:44:00session_1,12012303393,session_1,8.0,120123033932022-08-16 07:44:00session_1,nan
4,2022-08-16 07:45:00,login help,12012303393,session_1,8.0,120123033932022-08-16 07:45:00session_1,"due to high chat volumes, there may be a delay...",120123033932022-08-16 07:45:00session_1,12012303393,session_1,8.0,120123033932022-08-16 07:45:00session_1,nan

,Date_str2,User Query,Bot Response,User ID_y,sessions_y,month_y,concat_y,Intent Recognized
0,2022-08-16 07:41:00,livechat service for whatsapp > identified cli...,nan > nan > do you wish to self-authenticate? ...,12012303393,session_1,8.0,120123033932022-08-16 07:41:00session_1,chat with our expert > livechat service for wh...
1,2022-08-16 07:42:00,no,invalid answerkindly provide a valid answer to...,12012303393,session_1,8.0,120123033932022-08-16 07:42:00session_1,nan

,Date_str2,User Query,Bot Response,ID,sessions,month,concat,Intent Recognized
0,2022-08-16 07:41:00,livechat service for whatsapp > identified cli...,nan > nan > do you wish to self-authenticate? ...,12012303393,session_1,8.0,120123033932022-08-16 07:41:00session_1,chat with our expert > livechat service for wh...
1,2022-08-16 07:42:00,no,invalid answerkindly provide a valid answer to...,12012303393,session_1,8.0,120123033932022-08-16 07:42:00session_1,nan
2,2022-08-16 07:43:00,********** > resend,kindly enter the otp we have sent on your regi...,12012303393,session_1,8.0,120123033932022-08-16 07:43:00session_1,nan > nan
3,2022-08-16 07:44:00,**********,you are successfully authenticated with client...,12012303393,session_1,8.0,120123033932022-08-16 07:44:00session_1,nan
4,2022-08-16 07:45:00,login help,"due to high chat volumes, there may be a delay...",12012303393,session_1,8.0,120123033932022-08-16 07:45:00session_1,nan

,ID,sessions,month,concat,User Query,Bot Response,Intent Recognized
0,12012303393,session_1,8.0,120123033932022-08-16 07:41:00session_1,livechat service for whatsapp > identified cli...,nan > nan > do you wish to self-authenticate? ...,chat with our expert > livechat service for wh...
1,12012303393,session_1,8.0,120123033932022-08-16 07:42:00session_1,no,invalid answerkindly provide a valid answer to...,nan

(92115, 7)

# Sept_month_Base_Data

In [187]:
#filter Month - Sept
data_9 = data[data['month']== 9]
data_9.shape

#Sort Data 
data_Sept = data_9.sort_values(by=['User ID','Time1','Number'], ascending=[1,1,0])
data_Sept = data_Sept[['User ID','Time1','User Query','Intent Recognized','Bot Response','Date_str','month']]
data_Sept.head()

#Define Sessions

data_Sept['Time'] = pd.to_datetime(data_Sept['Time1'])
data_Sept['diffs'] = data_Sept.groupby('User ID')['Time1'].diff()
data_Sept['break'] = data_Sept['diffs'] >= pd.Timedelta('10 min')
data_Sept['sessions'] = data_Sept.groupby('User ID')['break'].cumsum().apply(lambda x: 'session_{}'.format(x+1))
data_Sept.head(2)

#For Joining convert Variable to str

data_Sept['id_str']=data_Sept['User ID'].astype('str')
data_Sept['Date_str2']=data_Sept['Date_str'].astype('str')
data_Sept['Session_str']=data_Sept['sessions'].astype('str')

#Concat all three variables for joining
data_Sept['concat'] = data_Sept['id_str'] + data_Sept['Date_str2']+ data_Sept['Session_str']

# Create Unique Base for Joining
data_Base_Sept=data_Sept[['User ID','Date_str2','concat','month','sessions']]
data_Base_Sept.drop_duplicates(keep='first', inplace=True)
data_Base_Sept.head()
data_Base_Sept.shape

#User Query Transpose
data_Sept_User = data_Sept.groupby(['User ID','sessions','month','concat'])['User Query'].apply(lambda x: ' > '.join(x)).reset_index()
data_Sept_User['User Query'] = data_Sept_User['User Query'].str.lower()
data_Sept_User.head()

#Bot Response Transpose
data_Sept_Bot = data_Sept.groupby(['User ID','sessions','month','concat'])['Bot Response'].apply(lambda x: ' > '.join(x)).reset_index()
data_Sept_Bot['Bot Response'] = data_Sept_Bot['Bot Response'].str.lower()
data_Sept_Bot.head()

#Intent Response Transpose
data_Sept_intent = data_Sept.groupby(['User ID','sessions','month','concat'])['Intent Recognized'].apply(lambda x: ' > '.join(x)).reset_index()
data_Sept_intent['Intent Recognized'] = data_Sept_intent['Intent Recognized'].str.lower()
data_Sept_intent.head()

#Merge1
data_Base_Sept['key1'] = data_Base_Sept.concat.str.strip()
data_Sept_User['key1'] = data_Sept_User.concat.str.strip()
df_merge1 = pd.merge(data_Base_Sept,data_Sept_User, how='left', left_on=['key1'], right_on=['key1'])
df_merge1.head()
df_merge1.columns
df_merge1.drop(['key1','User ID_y', 'sessions_y', 'month_y', 'concat_y'],axis=1, inplace=True)
df_merge1.head(2)


#Merge2
df_merge1['key1'] = df_merge1.concat_x.str.strip()
data_Sept_Bot['key1'] = data_Sept_Bot.concat.str.strip()
df_merge2 = pd.merge(df_merge1,data_Sept_Bot, how='left', left_on=['key1'], right_on=['key1'])
df_merge2.head()
df_merge2.drop(['User ID_x', 'concat_x', 'month_x', 'sessions_x','key1'],axis=1, inplace=True)
df_merge2.head(2)

#Merge3
df_merge2['key1'] = df_merge2.concat.str.strip()
data_Sept_intent['key1'] = data_Sept_intent.concat.str.strip()
df_merge3 = pd.merge(df_merge2,data_Sept_intent, how='left', left_on=['key1'], right_on=['key1'])
df_merge3.head()
df_merge3.drop(['User ID_x', 'sessions_x', 'month_x', 'concat_x','key1'],axis=1, inplace=True)
df_merge3.head(2)

#Final File
df_Final_Sept=df_merge3.rename(columns={'User ID_y':'ID','month_y':'month','concat_y':'concat','sessions_y':'sessions'}) 
df_Final_Sept.head()
df_Final_Sept = df_Final_Sept[['ID', 'sessions', 'month', 'concat','User Query', 'Bot Response','Intent Recognized']]
df_Final_Sept.head(2)
df_Final_Sept.shape

(539186, 9)

,User ID,Time1,User Query,Intent Recognized,Bot Response,Date_str,month
376498,12012149573,2022-09-03 18:22:00,WhatsApp ???? LiveChat ????,Chat with our expert,nan,2022-09-03 18:22:00,9.0
376497,12012149573,2022-09-03 18:22:00,??????? ??????? ????? ??????? ???,LiveChat Service for WhatsApp,nan,2022-09-03 18:22:00,9.0
376496,12012149573,2022-09-03 18:22:00,??????? ???? ??? ???,nan,??? ??? ???-???????? ???? ????? ???,2022-09-03 18:22:00,9.0
376499,12012149573,2022-09-03 18:24:00,???????? ??? ????? ??????? ??? ?????? ????????...,What is the process to close the trading and d...,???? ??? ????? ??? ????? ???! ????? ???? ?????...,2022-09-03 18:24:00,9.0
376501,12012149573,2022-09-03 18:25:00,?????,nan,??? ????? ??? ?? ????? ?????? ???? ??? ???? ??...,2022-09-03 18:25:00,9.0

,User ID,Time1,User Query,Intent Recognized,Bot Response,Date_str,month,Time,diffs,break,sessions
376498,12012149573,2022-09-03 18:22:00,WhatsApp ???? LiveChat ????,Chat with our expert,nan,2022-09-03 18:22:00,9.0,2022-09-03 18:22:00,NaT,False,session_1
376497,12012149573,2022-09-03 18:22:00,??????? ??????? ????? ??????? ???,LiveChat Service for WhatsApp,nan,2022-09-03 18:22:00,9.0,2022-09-03 18:22:00,0 days,False,session_1

,User ID,Date_str2,concat,month,sessions
376498,12012149573,2022-09-03 18:22:00,120121495732022-09-03 18:22:00session_1,9.0,session_1
376499,12012149573,2022-09-03 18:24:00,120121495732022-09-03 18:24:00session_1,9.0,session_1
376501,12012149573,2022-09-03 18:25:00,120121495732022-09-03 18:25:00session_1,9.0,session_1
376506,12012149573,2022-09-03 18:26:00,120121495732022-09-03 18:26:00session_1,9.0,session_1
376507,12012149573,2022-09-03 18:27:00,120121495732022-09-03 18:27:00session_1,9.0,session_1

(189963, 5)

,User ID,sessions,month,concat,User Query
0,12012149573,session_1,9.0,120121495732022-09-03 18:22:00session_1,whatsapp ???? livechat ???? > ??????? ??????? ...
1,12012149573,session_1,9.0,120121495732022-09-03 18:24:00session_1,???????? ??? ????? ??????? ??? ?????? ????????...
2,12012149573,session_1,9.0,120121495732022-09-03 18:25:00session_1,????? > ?????
3,12012149573,session_1,9.0,120121495732022-09-03 18:26:00session_1,whatsapp ???? livechat ???? > ??????? ??????? ...
4,12012149573,session_1,9.0,120121495732022-09-03 18:27:00session_1,380007 ??

,User ID,sessions,month,concat,Bot Response
0,12012149573,session_1,9.0,120121495732022-09-03 18:22:00session_1,nan > nan > ??? ??? ???-???????? ???? ????? ???
1,12012149573,session_1,9.0,120121495732022-09-03 18:24:00session_1,???? ??? ????? ??? ????? ???! ????? ???? ?????...
2,12012149573,session_1,9.0,120121495732022-09-03 18:25:00session_1,??? ????? ??? ?? ????? ?????? ???? ??? ???? ??...
3,12012149573,session_1,9.0,120121495732022-09-03 18:26:00session_1,nan > nan > ??? ??? ???-???????? ???? ????? ??...
4,12012149573,session_1,9.0,120121495732022-09-03 18:27:00session_1,???? ????? ??? ????? ????????? ?????? ???? ???...

,User ID,sessions,month,concat,Intent Recognized
0,12012149573,session_1,9.0,120121495732022-09-03 18:22:00session_1,chat with our expert > livechat service for wh...
1,12012149573,session_1,9.0,120121495732022-09-03 18:24:00session_1,what is the process to close the trading and d...
2,12012149573,session_1,9.0,120121495732022-09-03 18:25:00session_1,nan > nan
3,12012149573,session_1,9.0,120121495732022-09-03 18:26:00session_1,chat with our expert > livechat service for wh...
4,12012149573,session_1,9.0,120121495732022-09-03 18:27:00session_1,nan

,User ID_x,Date_str2,concat_x,month_x,sessions_x,key1,User ID_y,sessions_y,month_y,concat_y,User Query
0,12012149573,2022-09-03 18:22:00,120121495732022-09-03 18:22:00session_1,9.0,session_1,120121495732022-09-03 18:22:00session_1,12012149573,session_1,9.0,120121495732022-09-03 18:22:00session_1,whatsapp ???? livechat ???? > ??????? ??????? ...
1,12012149573,2022-09-03 18:24:00,120121495732022-09-03 18:24:00session_1,9.0,session_1,120121495732022-09-03 18:24:00session_1,12012149573,session_1,9.0,120121495732022-09-03 18:24:00session_1,???????? ??? ????? ??????? ??? ?????? ????????...
2,12012149573,2022-09-03 18:25:00,120121495732022-09-03 18:25:00session_1,9.0,session_1,120121495732022-09-03 18:25:00session_1,12012149573,session_1,9.0,120121495732022-09-03 18:25:00session_1,????? > ?????
3,12012149573,2022-09-03 18:26:00,120121495732022-09-03 18:26:00session_1,9.0,session_1,120121495732022-09-03 18:26:00session_1,12012149573,session_1,9.0,120121495732022-09-03 18:26:00session_1,whatsapp ???? livechat ???? > ??????? ??????? ...
4,12012149573,2022-09-03 18:27:00,120121495732022-09-03 18:27:00session_1,9.0,session_1,120121495732022-09-03 18:27:00session_1,12012149573,session_1,9.0,120121495732022-09-03 18:27:00session_1,380007 ??

Index(['User ID_x', 'Date_str2', 'concat_x', 'month_x', 'sessions_x', 'key1',
       'User ID_y', 'sessions_y', 'month_y', 'concat_y', 'User Query'],
      dtype='object')

,User ID_x,Date_str2,concat_x,month_x,sessions_x,User Query
0,12012149573,2022-09-03 18:22:00,120121495732022-09-03 18:22:00session_1,9.0,session_1,whatsapp ???? livechat ???? > ??????? ??????? ...
1,12012149573,2022-09-03 18:24:00,120121495732022-09-03 18:24:00session_1,9.0,session_1,???????? ??? ????? ??????? ??? ?????? ????????...

,User ID_x,Date_str2,concat_x,month_x,sessions_x,User Query,key1,User ID,sessions,month,concat,Bot Response
0,12012149573,2022-09-03 18:22:00,120121495732022-09-03 18:22:00session_1,9.0,session_1,whatsapp ???? livechat ???? > ??????? ??????? ...,120121495732022-09-03 18:22:00session_1,12012149573,session_1,9.0,120121495732022-09-03 18:22:00session_1,nan > nan > ??? ??? ???-???????? ???? ????? ???
1,12012149573,2022-09-03 18:24:00,120121495732022-09-03 18:24:00session_1,9.0,session_1,???????? ??? ????? ??????? ??? ?????? ????????...,120121495732022-09-03 18:24:00session_1,12012149573,session_1,9.0,120121495732022-09-03 18:24:00session_1,???? ??? ????? ??? ????? ???! ????? ???? ?????...
2,12012149573,2022-09-03 18:25:00,120121495732022-09-03 18:25:00session_1,9.0,session_1,????? > ?????,120121495732022-09-03 18:25:00session_1,12012149573,session_1,9.0,120121495732022-09-03 18:25:00session_1,??? ????? ??? ?? ????? ?????? ???? ??? ???? ??...
3,12012149573,2022-09-03 18:26:00,120121495732022-09-03 18:26:00session_1,9.0,session_1,whatsapp ???? livechat ???? > ??????? ??????? ...,120121495732022-09-03 18:26:00session_1,12012149573,session_1,9.0,120121495732022-09-03 18:26:00session_1,nan > nan > ??? ??? ???-???????? ???? ????? ??...
4,12012149573,2022-09-03 18:27:00,120121495732022-09-03 18:27:00session_1,9.0,session_1,380007 ??,120121495732022-09-03 18:27:00session_1,12012149573,session_1,9.0,120121495732022-09-03 18:27:00session_1,???? ????? ??? ????? ????????? ?????? ???? ???...

,Date_str2,User Query,User ID,sessions,month,concat,Bot Response
0,2022-09-03 18:22:00,whatsapp ???? livechat ???? > ??????? ??????? ...,12012149573,session_1,9.0,120121495732022-09-03 18:22:00session_1,nan > nan > ??? ??? ???-???????? ???? ????? ???
1,2022-09-03 18:24:00,???????? ??? ????? ??????? ??? ?????? ????????...,12012149573,session_1,9.0,120121495732022-09-03 18:24:00session_1,???? ??? ????? ??? ????? ???! ????? ???? ?????...

,Date_str2,User Query,User ID_x,sessions_x,month_x,concat_x,Bot Response,key1,User ID_y,sessions_y,month_y,concat_y,Intent Recognized
0,2022-09-03 18:22:00,whatsapp ???? livechat ???? > ??????? ??????? ...,12012149573,session_1,9.0,120121495732022-09-03 18:22:00session_1,nan > nan > ??? ??? ???-???????? ???? ????? ???,120121495732022-09-03 18:22:00session_1,12012149573,session_1,9.0,120121495732022-09-03 18:22:00session_1,chat with our expert > livechat service for wh...
1,2022-09-03 18:24:00,???????? ??? ????? ??????? ??? ?????? ????????...,12012149573,session_1,9.0,120121495732022-09-03 18:24:00session_1,???? ??? ????? ??? ????? ???! ????? ???? ?????...,120121495732022-09-03 18:24:00session_1,12012149573,session_1,9.0,120121495732022-09-03 18:24:00session_1,what is the process to close the trading and d...
2,2022-09-03 18:25:00,????? > ?????,12012149573,session_1,9.0,120121495732022-09-03 18:25:00session_1,??? ????? ??? ?? ????? ?????? ???? ??? ???? ??...,120121495732022-09-03 18:25:00session_1,12012149573,session_1,9.0,120121495732022-09-03 18:25:00session_1,nan > nan
3,2022-09-03 18:26:00,whatsapp ???? livechat ???? > ??????? ??????? ...,12012149573,session_1,9.0,120121495732022-09-03 18:26:00session_1,nan > nan > ??? ??? ???-???????? ???? ????? ??...,120121495732022-09-03 18:26:00session_1,12012149573,session_1,9.0,120121495732022-09-03 18:26:00session_1,chat with our expert > livechat service for wh...
4,2022-09-03 18:27:00,380007 ??,12012149573,session_1,9.0,120121495732022-09-03 18:27:00session_1,???? ????? ??? ????? ????????? ?????? ???? ???...,120121495732022-09-03 18:27:00session_1,12012149573,session_1,9.0,120121495732022-09-03 18:27:00session_1,nan

,Date_str2,User Query,Bot Response,User ID_y,sessions_y,month_y,concat_y,Intent Recognized
0,2022-09-03 18:22:00,whatsapp ???? livechat ???? > ??????? ??????? ...,nan > nan > ??? ??? ???-???????? ???? ????? ???,12012149573,session_1,9.0,120121495732022-09-03 18:22:00session_1,chat with our expert > livechat service for wh...
1,2022-09-03 18:24:00,???????? ??? ????? ??????? ??? ?????? ????????...,???? ??? ????? ??? ????? ???! ????? ???? ?????...,12012149573,session_1,9.0,120121495732022-09-03 18:24:00session_1,what is the process to close the trading and d...

,Date_str2,User Query,Bot Response,ID,sessions,month,concat,Intent Recognized
0,2022-09-03 18:22:00,whatsapp ???? livechat ???? > ??????? ??????? ...,nan > nan > ??? ??? ???-???????? ???? ????? ???,12012149573,session_1,9.0,120121495732022-09-03 18:22:00session_1,chat with our expert > livechat service for wh...
1,2022-09-03 18:24:00,???????? ??? ????? ??????? ??? ?????? ????????...,???? ??? ????? ??? ????? ???! ????? ???? ?????...,12012149573,session_1,9.0,120121495732022-09-03 18:24:00session_1,what is the process to close the trading and d...
2,2022-09-03 18:25:00,????? > ?????,??? ????? ??? ?? ????? ?????? ???? ??? ???? ??...,12012149573,session_1,9.0,120121495732022-09-03 18:25:00session_1,nan > nan
3,2022-09-03 18:26:00,whatsapp ???? livechat ???? > ??????? ??????? ...,nan > nan > ??? ??? ???-???????? ???? ????? ??...,12012149573,session_1,9.0,120121495732022-09-03 18:26:00session_1,chat with our expert > livechat service for wh...
4,2022-09-03 18:27:00,380007 ??,???? ????? ??? ????? ????????? ?????? ???? ???...,12012149573,session_1,9.0,120121495732022-09-03 18:27:00session_1,nan

,ID,sessions,month,concat,User Query,Bot Response,Intent Recognized
0,12012149573,session_1,9.0,120121495732022-09-03 18:22:00session_1,whatsapp ???? livechat ???? > ??????? ??????? ...,nan > nan > ??? ??? ???-???????? ???? ????? ???,chat with our expert > livechat service for wh...
1,12012149573,session_1,9.0,120121495732022-09-03 18:24:00session_1,???????? ??? ????? ??????? ??? ?????? ????????...,???? ??? ????? ??? ????? ???! ????? ???? ?????...,what is the process to close the trading and d...

(189963, 7)

# October_month_base_data

In [188]:
#filter Month - Oct
data_10 = data[data['month']== 10]
data_10.shape

#Sort Data 
data_Oct = data_10.sort_values(by=['User ID','Time1','Number'], ascending=[1,1,0])
data_Oct = data_Oct[['User ID','Time1','User Query','Intent Recognized','Bot Response','Date_str','month']]
data_Oct.head()

#Define Sessions

data_Oct['Time'] = pd.to_datetime(data_Oct['Time1'])
data_Oct['diffs'] = data_Oct.groupby('User ID')['Time1'].diff()
data_Oct['break'] = data_Oct['diffs'] >= pd.Timedelta('10 min')

data_Oct['sessions'] = data_Oct.groupby('User ID')['break'].cumsum().apply(lambda x: 'session_{}'.format(x+1))
data_Oct.head(2)

#For Joining convert Variable to str

data_Oct['id_str']=data_Oct['User ID'].astype('str')
data_Oct['Date_str2']=data_Oct['Date_str'].astype('str')
data_Oct['Session_str']=data_Oct['sessions'].astype('str')

#Concat all three variables for joining
data_Oct['concat'] = data_Oct['id_str'] + data_Oct['Date_str2']+ data_Oct['Session_str']

# Create Unique Base for Joining
data_Base_Oct=data_Oct[['User ID','Date_str2','concat','month','sessions']]
data_Base_Oct.drop_duplicates(keep='first', inplace=True)
data_Base_Oct.head()
data_Base_Oct.shape

#User Query Transpose
data_Oct_User = data_Oct.groupby(['User ID','sessions','month','concat'])['User Query'].apply(lambda x: ' > '.join(x)).reset_index()
data_Oct_User['User Query'] = data_Oct_User['User Query'].str.lower()
data_Oct_User.head()

#Bot Response Transpose
data_Oct_Bot = data_Oct.groupby(['User ID','sessions','month','concat'])['Bot Response'].apply(lambda x: ' > '.join(x)).reset_index()
data_Oct_Bot['Bot Response'] = data_Oct_Bot['Bot Response'].str.lower()
data_Oct_Bot.head()

#Intent Response Transpose
data_Oct_intent = data_Oct.groupby(['User ID','sessions','month','concat'])['Intent Recognized'].apply(lambda x: ' > '.join(x)).reset_index()
data_Oct_intent['Intent Recognized'] = data_Oct_intent['Intent Recognized'].str.lower()
data_Oct_intent.head()

#Merge1
data_Base_Oct['key1'] = data_Base_Oct.concat.str.strip()
data_Oct_User['key1'] = data_Oct_User.concat.str.strip()
df_merge1 = pd.merge(data_Base_Oct,data_Oct_User, how='left', left_on=['key1'], right_on=['key1'])
df_merge1.head()
df_merge1.columns
df_merge1.drop(['key1','User ID_y', 'sessions_y', 'month_y', 'concat_y'],axis=1, inplace=True)
df_merge1.head(2)


#Merge2
df_merge1['key1'] = df_merge1.concat_x.str.strip()
data_Oct_Bot['key1'] = data_Oct_Bot.concat.str.strip()
df_merge2 = pd.merge(df_merge1,data_Oct_Bot, how='left', left_on=['key1'], right_on=['key1'])
df_merge2.head()
df_merge2.drop(['User ID_x', 'concat_x', 'month_x', 'sessions_x','key1'],axis=1, inplace=True)
df_merge2.head(2)

#Merge3
df_merge2['key1'] = df_merge2.concat.str.strip()
data_Oct_intent['key1'] = data_Oct_intent.concat.str.strip()
df_merge3 = pd.merge(df_merge2,data_Oct_intent, how='left', left_on=['key1'], right_on=['key1'])
df_merge3.head()
df_merge3.drop(['User ID_x', 'sessions_x', 'month_x', 'concat_x','key1'],axis=1, inplace=True)
df_merge3.head(2)

#Final File
df_Final_Oct=df_merge3.rename(columns={'User ID_y':'ID','month_y':'month','concat_y':'concat','sessions_y':'sessions'}) 
df_Final_Oct.head()
df_Final_Oct = df_Final_Oct[['ID', 'sessions', 'month', 'concat','User Query', 'Bot Response','Intent Recognized']]
df_Final_Oct.head(2)
df_Final_Oct.shape

(462153, 9)

,User ID,Time1,User Query,Intent Recognized,Bot Response,Date_str,month
6,12012349824,2022-10-02 03:18:00,Account opening,Account Opening,Please select one of the following options bel...,2022-10-02 03:18:00,10.0
5,12012349824,2022-10-02 03:18:00,I want to open an account with Kotak Securities.,I want to open an account with Kotak Securities.,We&#39;re delighted to know that you wish to o...,2022-10-02 03:18:00,10.0
4,12012349824,2022-10-02 03:18:00,4,nan,I&#39;m not sure if I can help you with your q...,2022-10-02 03:18:00,10.0
3,12012349824,2022-10-02 03:18:00,LiveChat Service for WhatsApp,Chat with our expert,nan,2022-10-02 03:18:00,10.0
2,12012349824,2022-10-02 03:18:00,unidentified client,LiveChat Service for WhatsApp,nan,2022-10-02 03:18:00,10.0

,User ID,Time1,User Query,Intent Recognized,Bot Response,Date_str,month,Time,diffs,break,sessions
6,12012349824,2022-10-02 03:18:00,Account opening,Account Opening,Please select one of the following options bel...,2022-10-02 03:18:00,10.0,2022-10-02 03:18:00,NaT,False,session_1
5,12012349824,2022-10-02 03:18:00,I want to open an account with Kotak Securities.,I want to open an account with Kotak Securities.,We&#39;re delighted to know that you wish to o...,2022-10-02 03:18:00,10.0,2022-10-02 03:18:00,0 days,False,session_1

,User ID,Date_str2,concat,month,sessions
6,12012349824,2022-10-02 03:18:00,120123498242022-10-02 03:18:00session_1,10.0,session_1
7,12012349824,2022-10-02 03:19:00,120123498242022-10-02 03:19:00session_1,10.0,session_1
9,12012349824,2022-10-03 17:52:00,120123498242022-10-03 17:52:00session_2,10.0,session_2
10,12012349824,2022-10-03 17:53:00,120123498242022-10-03 17:53:00session_2,10.0,session_2
13,12012349824,2022-10-03 17:54:00,120123498242022-10-03 17:54:00session_2,10.0,session_2

(155469, 5)

,User ID,sessions,month,concat,User Query
0,12012349824,session_1,10.0,120123498242022-10-02 03:18:00session_1,account opening > i want to open an account wi...
1,12012349824,session_1,10.0,120123498242022-10-02 03:19:00session_1,demat account
2,12012349824,session_2,10.0,120123498242022-10-03 17:52:00session_2,hello > open new account
3,12012349824,session_2,10.0,120123498242022-10-03 17:53:00session_2,account opening
4,12012349824,session_2,10.0,120123498242022-10-03 17:54:00session_2,livechat service for whatsapp > unidentified c...

,User ID,sessions,month,concat,Bot Response
0,12012349824,session_1,10.0,120123498242022-10-02 03:18:00session_1,please select one of the following options bel...
1,12012349824,session_1,10.0,120123498242022-10-02 03:19:00session_1,"due to high chat volumes, there may be a delay..."
2,12012349824,session_2,10.0,120123498242022-10-03 17:52:00session_2,"hi! i&rsquo;m maya, your virtual assistant fro..."
3,12012349824,session_2,10.0,120123498242022-10-03 17:53:00session_2,please select one of the following options bel...
4,12012349824,session_2,10.0,120123498242022-10-03 17:54:00session_2,nan > nan > your whatsapp number is not regist...

,User ID,sessions,month,concat,Intent Recognized
0,12012349824,session_1,10.0,120123498242022-10-02 03:18:00session_1,account opening > i want to open an account wi...
1,12012349824,session_1,10.0,120123498242022-10-02 03:19:00session_1,nan
2,12012349824,session_2,10.0,120123498242022-10-03 17:52:00session_2,greetings > new account
3,12012349824,session_2,10.0,120123498242022-10-03 17:53:00session_2,account opening
4,12012349824,session_2,10.0,120123498242022-10-03 17:54:00session_2,chat with our expert > livechat service for wh...

,User ID_x,Date_str2,concat_x,month_x,sessions_x,key1,User ID_y,sessions_y,month_y,concat_y,User Query
0,12012349824,2022-10-02 03:18:00,120123498242022-10-02 03:18:00session_1,10.0,session_1,120123498242022-10-02 03:18:00session_1,12012349824,session_1,10.0,120123498242022-10-02 03:18:00session_1,account opening > i want to open an account wi...
1,12012349824,2022-10-02 03:19:00,120123498242022-10-02 03:19:00session_1,10.0,session_1,120123498242022-10-02 03:19:00session_1,12012349824,session_1,10.0,120123498242022-10-02 03:19:00session_1,demat account
2,12012349824,2022-10-03 17:52:00,120123498242022-10-03 17:52:00session_2,10.0,session_2,120123498242022-10-03 17:52:00session_2,12012349824,session_2,10.0,120123498242022-10-03 17:52:00session_2,hello > open new account
3,12012349824,2022-10-03 17:53:00,120123498242022-10-03 17:53:00session_2,10.0,session_2,120123498242022-10-03 17:53:00session_2,12012349824,session_2,10.0,120123498242022-10-03 17:53:00session_2,account opening
4,12012349824,2022-10-03 17:54:00,120123498242022-10-03 17:54:00session_2,10.0,session_2,120123498242022-10-03 17:54:00session_2,12012349824,session_2,10.0,120123498242022-10-03 17:54:00session_2,livechat service for whatsapp > unidentified c...

Index(['User ID_x', 'Date_str2', 'concat_x', 'month_x', 'sessions_x', 'key1',
       'User ID_y', 'sessions_y', 'month_y', 'concat_y', 'User Query'],
      dtype='object')

,User ID_x,Date_str2,concat_x,month_x,sessions_x,User Query
0,12012349824,2022-10-02 03:18:00,120123498242022-10-02 03:18:00session_1,10.0,session_1,account opening > i want to open an account wi...
1,12012349824,2022-10-02 03:19:00,120123498242022-10-02 03:19:00session_1,10.0,session_1,demat account

,User ID_x,Date_str2,concat_x,month_x,sessions_x,User Query,key1,User ID,sessions,month,concat,Bot Response
0,12012349824,2022-10-02 03:18:00,120123498242022-10-02 03:18:00session_1,10.0,session_1,account opening > i want to open an account wi...,120123498242022-10-02 03:18:00session_1,12012349824,session_1,10.0,120123498242022-10-02 03:18:00session_1,please select one of the following options bel...
1,12012349824,2022-10-02 03:19:00,120123498242022-10-02 03:19:00session_1,10.0,session_1,demat account,120123498242022-10-02 03:19:00session_1,12012349824,session_1,10.0,120123498242022-10-02 03:19:00session_1,"due to high chat volumes, there may be a delay..."
2,12012349824,2022-10-03 17:52:00,120123498242022-10-03 17:52:00session_2,10.0,session_2,hello > open new account,120123498242022-10-03 17:52:00session_2,12012349824,session_2,10.0,120123498242022-10-03 17:52:00session_2,"hi! i&rsquo;m maya, your virtual assistant fro..."
3,12012349824,2022-10-03 17:53:00,120123498242022-10-03 17:53:00session_2,10.0,session_2,account opening,120123498242022-10-03 17:53:00session_2,12012349824,session_2,10.0,120123498242022-10-03 17:53:00session_2,please select one of the following options bel...
4,12012349824,2022-10-03 17:54:00,120123498242022-10-03 17:54:00session_2,10.0,session_2,livechat service for whatsapp > unidentified c...,120123498242022-10-03 17:54:00session_2,12012349824,session_2,10.0,120123498242022-10-03 17:54:00session_2,nan > nan > your whatsapp number is not regist...

,Date_str2,User Query,User ID,sessions,month,concat,Bot Response
0,2022-10-02 03:18:00,account opening > i want to open an account wi...,12012349824,session_1,10.0,120123498242022-10-02 03:18:00session_1,please select one of the following options bel...
1,2022-10-02 03:19:00,demat account,12012349824,session_1,10.0,120123498242022-10-02 03:19:00session_1,"due to high chat volumes, there may be a delay..."

,Date_str2,User Query,User ID_x,sessions_x,month_x,concat_x,Bot Response,key1,User ID_y,sessions_y,month_y,concat_y,Intent Recognized
0,2022-10-02 03:18:00,account opening > i want to open an account wi...,12012349824,session_1,10.0,120123498242022-10-02 03:18:00session_1,please select one of the following options bel...,120123498242022-10-02 03:18:00session_1,12012349824,session_1,10.0,120123498242022-10-02 03:18:00session_1,account opening > i want to open an account wi...
1,2022-10-02 03:19:00,demat account,12012349824,session_1,10.0,120123498242022-10-02 03:19:00session_1,"due to high chat volumes, there may be a delay...",120123498242022-10-02 03:19:00session_1,12012349824,session_1,10.0,120123498242022-10-02 03:19:00session_1,nan
2,2022-10-03 17:52:00,hello > open new account,12012349824,session_2,10.0,120123498242022-10-03 17:52:00session_2,"hi! i&rsquo;m maya, your virtual assistant fro...",120123498242022-10-03 17:52:00session_2,12012349824,session_2,10.0,120123498242022-10-03 17:52:00session_2,greetings > new account
3,2022-10-03 17:53:00,account opening,12012349824,session_2,10.0,120123498242022-10-03 17:53:00session_2,please select one of the following options bel...,120123498242022-10-03 17:53:00session_2,12012349824,session_2,10.0,120123498242022-10-03 17:53:00session_2,account opening
4,2022-10-03 17:54:00,livechat service for whatsapp > unidentified c...,12012349824,session_2,10.0,120123498242022-10-03 17:54:00session_2,nan > nan > your whatsapp number is not regist...,120123498242022-10-03 17:54:00session_2,12012349824,session_2,10.0,120123498242022-10-03 17:54:00session_2,chat with our expert > livechat service for wh...

,Date_str2,User Query,Bot Response,User ID_y,sessions_y,month_y,concat_y,Intent Recognized
0,2022-10-02 03:18:00,account opening > i want to open an account wi...,please select one of the following options bel...,12012349824,session_1,10.0,120123498242022-10-02 03:18:00session_1,account opening > i want to open an account wi...
1,2022-10-02 03:19:00,demat account,"due to high chat volumes, there may be a delay...",12012349824,session_1,10.0,120123498242022-10-02 03:19:00session_1,nan

,Date_str2,User Query,Bot Response,ID,sessions,month,concat,Intent Recognized
0,2022-10-02 03:18:00,account opening > i want to open an account wi...,please select one of the following options bel...,12012349824,session_1,10.0,120123498242022-10-02 03:18:00session_1,account opening > i want to open an account wi...
1,2022-10-02 03:19:00,demat account,"due to high chat volumes, there may be a delay...",12012349824,session_1,10.0,120123498242022-10-02 03:19:00session_1,nan
2,2022-10-03 17:52:00,hello > open new account,"hi! i&rsquo;m maya, your virtual assistant fro...",12012349824,session_2,10.0,120123498242022-10-03 17:52:00session_2,greetings > new account
3,2022-10-03 17:53:00,account opening,please select one of the following options bel...,12012349824,session_2,10.0,120123498242022-10-03 17:53:00session_2,account opening
4,2022-10-03 17:54:00,livechat service for whatsapp > unidentified c...,nan > nan > your whatsapp number is not regist...,12012349824,session_2,10.0,120123498242022-10-03 17:54:00session_2,chat with our expert > livechat service for wh...

,ID,sessions,month,concat,User Query,Bot Response,Intent Recognized
0,12012349824,session_1,10.0,120123498242022-10-02 03:18:00session_1,account opening > i want to open an account wi...,please select one of the following options bel...,account opening > i want to open an account wi...
1,12012349824,session_1,10.0,120123498242022-10-02 03:19:00session_1,demat account,"due to high chat volumes, there may be a delay...",nan

(155469, 7)

# November_month_base_data

In [189]:
#filter Month - Nov
data_11 = data[data['month']== 11]
data_11.shape

#Sort Data 
data_Nov = data_11.sort_values(by=['User ID','Time1','Number'], ascending=[1,1,0])
data_Nov = data_Nov[['User ID','Time1','User Query','Intent Recognized','Bot Response','Date_str','month']]
data_Nov.head()

#Define Sessions

data_Nov['Time'] = pd.to_datetime(data_Nov['Time1'])
data_Nov['diffs'] = data_Nov.groupby('User ID')['Time1'].diff()
data_Nov['break'] = data_Nov['diffs'] >= pd.Timedelta('10 min')
data_Nov['sessions'] = data_Nov.groupby('User ID')['break'].cumsum().apply(lambda x: 'session_{}'.format(x+1))
data_Nov.head(2)

#For Joining convert Variable to str

data_Nov['id_str']=data_Nov['User ID'].astype('str')
data_Nov['Date_str2']=data_Nov['Date_str'].astype('str')
data_Nov['Session_str']=data_Nov['sessions'].astype('str')

#Concat all three variables for joining
data_Nov['concat'] = data_Nov['id_str'] + data_Nov['Date_str2']+ data_Nov['Session_str']

# Create Unique Base for Joining
data_Base_Nov=data_Nov[['User ID','Date_str2','concat','month','sessions']]
data_Base_Nov.drop_duplicates(keep='first', inplace=True)
data_Base_Nov.head()
data_Base_Nov.shape

#User Query Transpose
data_Nov_User = data_Nov.groupby(['User ID','sessions','month','concat'])['User Query'].apply(lambda x: ' > '.join(x)).reset_index()
data_Nov_User['User Query'] = data_Nov_User['User Query'].str.lower()
data_Nov_User.head()

#Bot Response Transpose
data_Nov_Bot = data_Nov.groupby(['User ID','sessions','month','concat'])['Bot Response'].apply(lambda x: ' > '.join(x)).reset_index()
data_Nov_Bot['Bot Response'] = data_Nov_Bot['Bot Response'].str.lower()
data_Nov_Bot.head()

#Intent Response Transpose
data_Nov_intent = data_Nov.groupby(['User ID','sessions','month','concat'])['Intent Recognized'].apply(lambda x: ' > '.join(x)).reset_index()
data_Nov_intent['Intent Recognized'] = data_Nov_intent['Intent Recognized'].str.lower()
data_Nov_intent.head()

#Merge1
data_Base_Nov['key1'] = data_Base_Nov.concat.str.strip()
data_Nov_User['key1'] = data_Nov_User.concat.str.strip()
df_merge1 = pd.merge(data_Base_Nov,data_Nov_User, how='left', left_on=['key1'], right_on=['key1'])
df_merge1.head()
df_merge1.columns
df_merge1.drop(['key1','User ID_y', 'sessions_y', 'month_y', 'concat_y'],axis=1, inplace=True)
df_merge1.head(2)


#Merge2
df_merge1['key1'] = df_merge1.concat_x.str.strip()
data_Nov_Bot['key1'] = data_Nov_Bot.concat.str.strip()
df_merge2 = pd.merge(df_merge1,data_Nov_Bot, how='left', left_on=['key1'], right_on=['key1'])
df_merge2.head()
df_merge2.drop(['User ID_x', 'concat_x', 'month_x', 'sessions_x','key1'],axis=1, inplace=True)
df_merge2.head(2)

#Merge3
df_merge2['key1'] = df_merge2.concat.str.strip()
data_Nov_intent['key1'] = data_Nov_intent.concat.str.strip()
df_merge3 = pd.merge(df_merge2,data_Nov_intent, how='left', left_on=['key1'], right_on=['key1'])
df_merge3.head()
df_merge3.drop(['User ID_x', 'sessions_x', 'month_x', 'concat_x','key1'],axis=1, inplace=True)
df_merge3.head(2)

#Final File
df_Final_Nov=df_merge3.rename(columns={'User ID_y':'ID','month_y':'month','concat_y':'concat','sessions_y':'sessions'}) 
df_Final_Nov.head()
df_Final_Nov = df_Final_Nov[['ID', 'sessions', 'month', 'concat','User Query', 'Bot Response','Intent Recognized']]
df_Final_Nov.head(2)
df_Final_Nov.shape

(586691, 9)

,User ID,Time1,User Query,Intent Recognized,Bot Response,Date_str,month
1,12016204891,2022-11-25 10:15:00,Hi,Hi,"Hi! I&rsquo;m Maya, your virtual assistant fro...",2022-11-25 10:15:00,11.0
0,12016204891,2022-11-25 10:15:00,Main Menu,Greetings,"Hi! I&rsquo;m Maya, your virtual assistant fro...",2022-11-25 10:15:00,11.0
5,12016204891,2022-11-25 10:16:00,Update Accounts,Update Account,Choose one from the following,2022-11-25 10:16:00,11.0
4,12016204891,2022-11-25 10:16:00,LiveChat Service for WhatsApp,Chat with our expert,nan,2022-11-25 10:16:00,11.0
3,12016204891,2022-11-25 10:16:00,unidentified client,LiveChat Service for WhatsApp,nan,2022-11-25 10:16:00,11.0

,User ID,Time1,User Query,Intent Recognized,Bot Response,Date_str,month,Time,diffs,break,sessions
1,12016204891,2022-11-25 10:15:00,Hi,Hi,"Hi! I&rsquo;m Maya, your virtual assistant fro...",2022-11-25 10:15:00,11.0,2022-11-25 10:15:00,NaT,False,session_1
0,12016204891,2022-11-25 10:15:00,Main Menu,Greetings,"Hi! I&rsquo;m Maya, your virtual assistant fro...",2022-11-25 10:15:00,11.0,2022-11-25 10:15:00,0 days,False,session_1

,User ID,Date_str2,concat,month,sessions
1,12016204891,2022-11-25 10:15:00,120162048912022-11-25 10:15:00session_1,11.0,session_1
5,12016204891,2022-11-25 10:16:00,120162048912022-11-25 10:16:00session_1,11.0,session_1
6,12016204891,2022-11-25 10:24:00,120162048912022-11-25 10:24:00session_1,11.0,session_1
7,12016204891,2022-11-25 10:25:00,120162048912022-11-25 10:25:00session_1,11.0,session_1
8,12034358993,2022-11-17 17:12:00,120343589932022-11-17 17:12:00session_1,11.0,session_1

(74586, 5)

,User ID,sessions,month,concat,User Query
0,12016204891,session_1,11.0,120162048912022-11-25 10:15:00session_1,hi > main menu
1,12016204891,session_1,11.0,120162048912022-11-25 10:16:00session_1,update accounts > livechat service for whatsap...
2,12016204891,session_1,11.0,120162048912022-11-25 10:24:00session_1,want to talk to agent directly
3,12016204891,session_1,11.0,120162048912022-11-25 10:25:00session_1,dormant account reactivation
4,12034358993,session_1,11.0,120343589932022-11-17 17:12:00session_1,test message

,User ID,sessions,month,concat,Bot Response
0,12016204891,session_1,11.0,120162048912022-11-25 10:15:00session_1,"hi! i&rsquo;m maya, your virtual assistant fro..."
1,12016204891,session_1,11.0,120162048912022-11-25 10:16:00session_1,choose one from the following > nan > nan > yo...
2,12016204891,session_1,11.0,120162048912022-11-25 10:24:00session_1,please select a category from the following.
3,12016204891,session_1,11.0,120162048912022-11-25 10:25:00session_1,"due to high chat volumes, there may be a delay..."
4,12034358993,session_1,11.0,120343589932022-11-17 17:12:00session_1,i&#39;m not sure if i can help you with your q...

,User ID,sessions,month,concat,Intent Recognized
0,12016204891,session_1,11.0,120162048912022-11-25 10:15:00session_1,hi > greetings
1,12016204891,session_1,11.0,120162048912022-11-25 10:16:00session_1,update account > chat with our expert > livech...
2,12016204891,session_1,11.0,120162048912022-11-25 10:24:00session_1,nan
3,12016204891,session_1,11.0,120162048912022-11-25 10:25:00session_1,nan
4,12034358993,session_1,11.0,120343589932022-11-17 17:12:00session_1,nan

,User ID_x,Date_str2,concat_x,month_x,sessions_x,key1,User ID_y,sessions_y,month_y,concat_y,User Query
0,12016204891,2022-11-25 10:15:00,120162048912022-11-25 10:15:00session_1,11.0,session_1,120162048912022-11-25 10:15:00session_1,12016204891,session_1,11.0,120162048912022-11-25 10:15:00session_1,hi > main menu
1,12016204891,2022-11-25 10:16:00,120162048912022-11-25 10:16:00session_1,11.0,session_1,120162048912022-11-25 10:16:00session_1,12016204891,session_1,11.0,120162048912022-11-25 10:16:00session_1,update accounts > livechat service for whatsap...
2,12016204891,2022-11-25 10:24:00,120162048912022-11-25 10:24:00session_1,11.0,session_1,120162048912022-11-25 10:24:00session_1,12016204891,session_1,11.0,120162048912022-11-25 10:24:00session_1,want to talk to agent directly
3,12016204891,2022-11-25 10:25:00,120162048912022-11-25 10:25:00session_1,11.0,session_1,120162048912022-11-25 10:25:00session_1,12016204891,session_1,11.0,120162048912022-11-25 10:25:00session_1,dormant account reactivation
4,12034358993,2022-11-17 17:12:00,120343589932022-11-17 17:12:00session_1,11.0,session_1,120343589932022-11-17 17:12:00session_1,12034358993,session_1,11.0,120343589932022-11-17 17:12:00session_1,test message

Index(['User ID_x', 'Date_str2', 'concat_x', 'month_x', 'sessions_x', 'key1',
       'User ID_y', 'sessions_y', 'month_y', 'concat_y', 'User Query'],
      dtype='object')

,User ID_x,Date_str2,concat_x,month_x,sessions_x,User Query
0,12016204891,2022-11-25 10:15:00,120162048912022-11-25 10:15:00session_1,11.0,session_1,hi > main menu
1,12016204891,2022-11-25 10:16:00,120162048912022-11-25 10:16:00session_1,11.0,session_1,update accounts > livechat service for whatsap...

,User ID_x,Date_str2,concat_x,month_x,sessions_x,User Query,key1,User ID,sessions,month,concat,Bot Response
0,12016204891,2022-11-25 10:15:00,120162048912022-11-25 10:15:00session_1,11.0,session_1,hi > main menu,120162048912022-11-25 10:15:00session_1,12016204891,session_1,11.0,120162048912022-11-25 10:15:00session_1,"hi! i&rsquo;m maya, your virtual assistant fro..."
1,12016204891,2022-11-25 10:16:00,120162048912022-11-25 10:16:00session_1,11.0,session_1,update accounts > livechat service for whatsap...,120162048912022-11-25 10:16:00session_1,12016204891,session_1,11.0,120162048912022-11-25 10:16:00session_1,choose one from the following > nan > nan > yo...
2,12016204891,2022-11-25 10:24:00,120162048912022-11-25 10:24:00session_1,11.0,session_1,want to talk to agent directly,120162048912022-11-25 10:24:00session_1,12016204891,session_1,11.0,120162048912022-11-25 10:24:00session_1,please select a category from the following.
3,12016204891,2022-11-25 10:25:00,120162048912022-11-25 10:25:00session_1,11.0,session_1,dormant account reactivation,120162048912022-11-25 10:25:00session_1,12016204891,session_1,11.0,120162048912022-11-25 10:25:00session_1,"due to high chat volumes, there may be a delay..."
4,12034358993,2022-11-17 17:12:00,120343589932022-11-17 17:12:00session_1,11.0,session_1,test message,120343589932022-11-17 17:12:00session_1,12034358993,session_1,11.0,120343589932022-11-17 17:12:00session_1,i&#39;m not sure if i can help you with your q...

,Date_str2,User Query,User ID,sessions,month,concat,Bot Response
0,2022-11-25 10:15:00,hi > main menu,12016204891,session_1,11.0,120162048912022-11-25 10:15:00session_1,"hi! i&rsquo;m maya, your virtual assistant fro..."
1,2022-11-25 10:16:00,update accounts > livechat service for whatsap...,12016204891,session_1,11.0,120162048912022-11-25 10:16:00session_1,choose one from the following > nan > nan > yo...

,Date_str2,User Query,User ID_x,sessions_x,month_x,concat_x,Bot Response,key1,User ID_y,sessions_y,month_y,concat_y,Intent Recognized
0,2022-11-25 10:15:00,hi > main menu,12016204891,session_1,11.0,120162048912022-11-25 10:15:00session_1,"hi! i&rsquo;m maya, your virtual assistant fro...",120162048912022-11-25 10:15:00session_1,12016204891,session_1,11.0,120162048912022-11-25 10:15:00session_1,hi > greetings
1,2022-11-25 10:16:00,update accounts > livechat service for whatsap...,12016204891,session_1,11.0,120162048912022-11-25 10:16:00session_1,choose one from the following > nan > nan > yo...,120162048912022-11-25 10:16:00session_1,12016204891,session_1,11.0,120162048912022-11-25 10:16:00session_1,update account > chat with our expert > livech...
2,2022-11-25 10:24:00,want to talk to agent directly,12016204891,session_1,11.0,120162048912022-11-25 10:24:00session_1,please select a category from the following.,120162048912022-11-25 10:24:00session_1,12016204891,session_1,11.0,120162048912022-11-25 10:24:00session_1,nan
3,2022-11-25 10:25:00,dormant account reactivation,12016204891,session_1,11.0,120162048912022-11-25 10:25:00session_1,"due to high chat volumes, there may be a delay...",120162048912022-11-25 10:25:00session_1,12016204891,session_1,11.0,120162048912022-11-25 10:25:00session_1,nan
4,2022-11-17 17:12:00,test message,12034358993,session_1,11.0,120343589932022-11-17 17:12:00session_1,i&#39;m not sure if i can help you with your q...,120343589932022-11-17 17:12:00session_1,12034358993,session_1,11.0,120343589932022-11-17 17:12:00session_1,nan

,Date_str2,User Query,Bot Response,User ID_y,sessions_y,month_y,concat_y,Intent Recognized
0,2022-11-25 10:15:00,hi > main menu,"hi! i&rsquo;m maya, your virtual assistant fro...",12016204891,session_1,11.0,120162048912022-11-25 10:15:00session_1,hi > greetings
1,2022-11-25 10:16:00,update accounts > livechat service for whatsap...,choose one from the following > nan > nan > yo...,12016204891,session_1,11.0,120162048912022-11-25 10:16:00session_1,update account > chat with our expert > livech...

,Date_str2,User Query,Bot Response,ID,sessions,month,concat,Intent Recognized
0,2022-11-25 10:15:00,hi > main menu,"hi! i&rsquo;m maya, your virtual assistant fro...",12016204891,session_1,11.0,120162048912022-11-25 10:15:00session_1,hi > greetings
1,2022-11-25 10:16:00,update accounts > livechat service for whatsap...,choose one from the following > nan > nan > yo...,12016204891,session_1,11.0,120162048912022-11-25 10:16:00session_1,update account > chat with our expert > livech...
2,2022-11-25 10:24:00,want to talk to agent directly,please select a category from the following.,12016204891,session_1,11.0,120162048912022-11-25 10:24:00session_1,nan
3,2022-11-25 10:25:00,dormant account reactivation,"due to high chat volumes, there may be a delay...",12016204891,session_1,11.0,120162048912022-11-25 10:25:00session_1,nan
4,2022-11-17 17:12:00,test message,i&#39;m not sure if i can help you with your q...,12034358993,session_1,11.0,120343589932022-11-17 17:12:00session_1,nan

,ID,sessions,month,concat,User Query,Bot Response,Intent Recognized
0,12016204891,session_1,11.0,120162048912022-11-25 10:15:00session_1,hi > main menu,"hi! i&rsquo;m maya, your virtual assistant fro...",hi > greetings
1,12016204891,session_1,11.0,120162048912022-11-25 10:16:00session_1,update accounts > livechat service for whatsap...,choose one from the following > nan > nan > yo...,update account > chat with our expert > livech...

(74586, 7)

# December_month_base_data

In [190]:
#filter Month - Dec
data_12 = data[data['month']== 12]
data_12.shape

#Sort Data 
data_Dec = data_12.sort_values(by=['User ID','Time1','Number'], ascending=[1,1,0])
data_Dec = data_Dec[['User ID','Time1','User Query','Intent Recognized','Bot Response','Date_str','month']]
data_Dec.head()

#Define Sessions

data_Dec['Time'] = pd.to_datetime(data_Dec['Time1'])
data_Dec['diffs'] = data_Dec.groupby('User ID')['Time1'].diff()
data_Dec['break'] = data_Dec['diffs'] >= pd.Timedelta('10 min')
data_Dec['sessions'] = data_Dec.groupby('User ID')['break'].cumsum().apply(lambda x: 'session_{}'.format(x+1))
data_Dec.head(2)

#For Joining convert Variable to str

data_Dec['id_str']=data_Dec['User ID'].astype('str')
data_Dec['Date_str2']=data_Dec['Date_str'].astype('str')
data_Dec['Session_str']=data_Dec['sessions'].astype('str')

#Concat all three variables for joining
data_Dec['concat'] = data_Dec['id_str'] + data_Dec['Date_str2']+ data_Dec['Session_str']

# Create Unique Base for Joining
data_Base_Dec=data_Dec[['User ID','Date_str2','concat','month','sessions']]
data_Base_Dec.drop_duplicates(keep='first', inplace=True)
data_Base_Dec.head()
data_Base_Dec.shape

#User Query Transpose
data_Dec_User = data_Dec.groupby(['User ID','sessions','month','concat'])['User Query'].apply(lambda x: ' > '.join(x)).reset_index()
data_Dec_User['User Query'] = data_Dec_User['User Query'].str.lower()
data_Dec_User.head()

#Bot Response Transpose
data_Dec_Bot = data_Dec.groupby(['User ID','sessions','month','concat'])['Bot Response'].apply(lambda x: ' > '.join(x)).reset_index()
data_Dec_Bot['Bot Response'] = data_Dec_Bot['Bot Response'].str.lower()
data_Dec_Bot.head()

#Intent Response Transpose
data_Dec_intent = data_Dec.groupby(['User ID','sessions','month','concat'])['Intent Recognized'].apply(lambda x: ' > '.join(x)).reset_index()
data_Dec_intent['Intent Recognized'] = data_Dec_intent['Intent Recognized'].str.lower()
data_Dec_intent.head()

#Merge1
data_Base_Dec['key1'] = data_Base_Dec.concat.str.strip()
data_Dec_User['key1'] = data_Dec_User.concat.str.strip()
df_merge1 = pd.merge(data_Base_Dec,data_Dec_User, how='left', left_on=['key1'], right_on=['key1'])
df_merge1.head()
df_merge1.columns
df_merge1.drop(['key1','User ID_y', 'sessions_y', 'month_y', 'concat_y'],axis=1, inplace=True)
df_merge1.head(2)


#Merge2
df_merge1['key1'] = df_merge1.concat_x.str.strip()
data_Dec_Bot['key1'] = data_Dec_Bot.concat.str.strip()
df_merge2 = pd.merge(df_merge1,data_Dec_Bot, how='left', left_on=['key1'], right_on=['key1'])
df_merge2.head()
df_merge2.drop(['User ID_x', 'concat_x', 'month_x', 'sessions_x','key1'],axis=1, inplace=True)
df_merge2.head(2)

#Merge3
df_merge2['key1'] = df_merge2.concat.str.strip()
data_Dec_intent['key1'] = data_Dec_intent.concat.str.strip()
df_merge3 = pd.merge(df_merge2,data_Dec_intent, how='left', left_on=['key1'], right_on=['key1'])
df_merge3.head()
df_merge3.drop(['User ID_x', 'sessions_x', 'month_x', 'concat_x','key1'],axis=1, inplace=True)
df_merge3.head(2)

#Final File
df_Final_Dec=df_merge3.rename(columns={'User ID_y':'ID','month_y':'month','concat_y':'concat','sessions_y':'sessions'}) 
df_Final_Dec.head()
df_Final_Dec = df_Final_Dec[['ID', 'sessions', 'month', 'concat','User Query', 'Bot Response','Intent Recognized']]
df_Final_Dec.head(2)
df_Final_Dec.shape

(735179, 9)

,User ID,Time1,User Query,Intent Recognized,Bot Response,Date_str,month
3,12012384226.0,2022-12-30 22:44:00,Hi,Hi,"Hi! I&rsquo;m Maya, your virtual assistant fro...",2022-12-30 22:44:00,12.0
2,12012384226.0,2022-12-30 22:44:00,Main Menu,Greetings,"Hi! I&rsquo;m Maya, your virtual assistant fro...",2022-12-30 22:44:00,12.0
1,12012384226.0,2022-12-30 22:44:00,Update Accounts,Update Account,Choose one from the following,2022-12-30 22:44:00,12.0
0,12012384226.0,2022-12-30 22:44:00,LiveChat Service for WhatsApp,Chat with our expert,nan,2022-12-30 22:44:00,12.0
6,12012384226.0,2022-12-30 22:45:00,unidentified client,LiveChat Service for WhatsApp,nan,2022-12-30 22:45:00,12.0

,User ID,Time1,User Query,Intent Recognized,Bot Response,Date_str,month,Time,diffs,break,sessions
3,12012384226.0,2022-12-30 22:44:00,Hi,Hi,"Hi! I&rsquo;m Maya, your virtual assistant fro...",2022-12-30 22:44:00,12.0,2022-12-30 22:44:00,NaT,False,session_1
2,12012384226.0,2022-12-30 22:44:00,Main Menu,Greetings,"Hi! I&rsquo;m Maya, your virtual assistant fro...",2022-12-30 22:44:00,12.0,2022-12-30 22:44:00,0 days,False,session_1

,User ID,Date_str2,concat,month,sessions
3,12012384226.0,2022-12-30 22:44:00,12012384226.02022-12-30 22:44:00session_1,12.0,session_1
6,12012384226.0,2022-12-30 22:45:00,12012384226.02022-12-30 22:45:00session_1,12.0,session_1
8,12012384226.0,2022-12-30 22:46:00,12012384226.02022-12-30 22:46:00session_1,12.0,session_1
14,12012384226.0,2022-12-30 22:47:00,12012384226.02022-12-30 22:47:00session_1,12.0,session_1
16,12012891146.0,2022-12-22 18:41:00,12012891146.02022-12-22 18:41:00session_1,12.0,session_1

(251304, 5)

,User ID,sessions,month,concat,User Query
0,12012384226.0,session_1,12.0,12012384226.02022-12-30 22:44:00session_1,hi > main menu > update accounts > livechat se...
1,12012384226.0,session_1,12.0,12012384226.02022-12-30 22:45:00session_1,unidentified client > talk to cse > want to en...
2,12012384226.0,session_1,12.0,12012384226.02022-12-30 22:46:00session_1,atlg3 > yes
3,12012384226.0,session_1,12.0,12012384226.02022-12-30 22:47:00session_1,1 > livechat service for whatsapp > unidentifi...
4,12012891146.0,session_1,12.0,12012891146.02022-12-22 18:41:00session_1,new client > available funds

,User ID,sessions,month,concat,Bot Response
0,12012384226.0,session_1,12.0,12012384226.02022-12-30 22:44:00session_1,"hi! i&rsquo;m maya, your virtual assistant fro..."
1,12012384226.0,session_1,12.0,12012384226.02022-12-30 22:45:00session_1,nan > your whatsapp number is not registered w...
2,12012384226.0,session_1,12.0,12012384226.02022-12-30 22:46:00session_1,do you wish to self-authenticate? > client acc...
3,12012384226.0,session_1,12.0,12012384226.02022-12-30 22:47:00session_1,i&#39;m not sure if i can help you with your q...
4,12012891146.0,session_1,12.0,12012891146.02022-12-22 18:41:00session_1,nan > your whatsapp mobile number is not regis...

,User ID,sessions,month,concat,Intent Recognized
0,12012384226.0,session_1,12.0,12012384226.02022-12-30 22:44:00session_1,hi > greetings > update account > chat with ou...
1,12012384226.0,session_1,12.0,12012384226.02022-12-30 22:45:00session_1,livechat service for whatsapp > nan > nan
2,12012384226.0,session_1,12.0,12012384226.02022-12-30 22:46:00session_1,nan > nan
3,12012384226.0,session_1,12.0,12012384226.02022-12-30 22:47:00session_1,nan > chat with our expert > livechat service ...
4,12012891146.0,session_1,12.0,12012891146.02022-12-22 18:41:00session_1,wa self service authentication > nan

,User ID_x,Date_str2,concat_x,month_x,sessions_x,key1,User ID_y,sessions_y,month_y,concat_y,User Query
0,12012384226.0,2022-12-30 22:44:00,12012384226.02022-12-30 22:44:00session_1,12.0,session_1,12012384226.02022-12-30 22:44:00session_1,12012384226.0,session_1,12.0,12012384226.02022-12-30 22:44:00session_1,hi > main menu > update accounts > livechat se...
1,12012384226.0,2022-12-30 22:45:00,12012384226.02022-12-30 22:45:00session_1,12.0,session_1,12012384226.02022-12-30 22:45:00session_1,12012384226.0,session_1,12.0,12012384226.02022-12-30 22:45:00session_1,unidentified client > talk to cse > want to en...
2,12012384226.0,2022-12-30 22:46:00,12012384226.02022-12-30 22:46:00session_1,12.0,session_1,12012384226.02022-12-30 22:46:00session_1,12012384226.0,session_1,12.0,12012384226.02022-12-30 22:46:00session_1,atlg3 > yes
3,12012384226.0,2022-12-30 22:47:00,12012384226.02022-12-30 22:47:00session_1,12.0,session_1,12012384226.02022-12-30 22:47:00session_1,12012384226.0,session_1,12.0,12012384226.02022-12-30 22:47:00session_1,1 > livechat service for whatsapp > unidentifi...
4,12012891146.0,2022-12-22 18:41:00,12012891146.02022-12-22 18:41:00session_1,12.0,session_1,12012891146.02022-12-22 18:41:00session_1,12012891146.0,session_1,12.0,12012891146.02022-12-22 18:41:00session_1,new client > available funds

Index(['User ID_x', 'Date_str2', 'concat_x', 'month_x', 'sessions_x', 'key1',
       'User ID_y', 'sessions_y', 'month_y', 'concat_y', 'User Query'],
      dtype='object')

,User ID_x,Date_str2,concat_x,month_x,sessions_x,User Query
0,12012384226.0,2022-12-30 22:44:00,12012384226.02022-12-30 22:44:00session_1,12.0,session_1,hi > main menu > update accounts > livechat se...
1,12012384226.0,2022-12-30 22:45:00,12012384226.02022-12-30 22:45:00session_1,12.0,session_1,unidentified client > talk to cse > want to en...

,User ID_x,Date_str2,concat_x,month_x,sessions_x,User Query,key1,User ID,sessions,month,concat,Bot Response
0,12012384226.0,2022-12-30 22:44:00,12012384226.02022-12-30 22:44:00session_1,12.0,session_1,hi > main menu > update accounts > livechat se...,12012384226.02022-12-30 22:44:00session_1,12012384226.0,session_1,12.0,12012384226.02022-12-30 22:44:00session_1,"hi! i&rsquo;m maya, your virtual assistant fro..."
1,12012384226.0,2022-12-30 22:45:00,12012384226.02022-12-30 22:45:00session_1,12.0,session_1,unidentified client > talk to cse > want to en...,12012384226.02022-12-30 22:45:00session_1,12012384226.0,session_1,12.0,12012384226.02022-12-30 22:45:00session_1,nan > your whatsapp number is not registered w...
2,12012384226.0,2022-12-30 22:46:00,12012384226.02022-12-30 22:46:00session_1,12.0,session_1,atlg3 > yes,12012384226.02022-12-30 22:46:00session_1,12012384226.0,session_1,12.0,12012384226.02022-12-30 22:46:00session_1,do you wish to self-authenticate? > client acc...
3,12012384226.0,2022-12-30 22:47:00,12012384226.02022-12-30 22:47:00session_1,12.0,session_1,1 > livechat service for whatsapp > unidentifi...,12012384226.02022-12-30 22:47:00session_1,12012384226.0,session_1,12.0,12012384226.02022-12-30 22:47:00session_1,i&#39;m not sure if i can help you with your q...
4,12012891146.0,2022-12-22 18:41:00,12012891146.02022-12-22 18:41:00session_1,12.0,session_1,new client > available funds,12012891146.02022-12-22 18:41:00session_1,12012891146.0,session_1,12.0,12012891146.02022-12-22 18:41:00session_1,nan > your whatsapp mobile number is not regis...

,Date_str2,User Query,User ID,sessions,month,concat,Bot Response
0,2022-12-30 22:44:00,hi > main menu > update accounts > livechat se...,12012384226.0,session_1,12.0,12012384226.02022-12-30 22:44:00session_1,"hi! i&rsquo;m maya, your virtual assistant fro..."
1,2022-12-30 22:45:00,unidentified client > talk to cse > want to en...,12012384226.0,session_1,12.0,12012384226.02022-12-30 22:45:00session_1,nan > your whatsapp number is not registered w...

,Date_str2,User Query,User ID_x,sessions_x,month_x,concat_x,Bot Response,key1,User ID_y,sessions_y,month_y,concat_y,Intent Recognized
0,2022-12-30 22:44:00,hi > main menu > update accounts > livechat se...,12012384226.0,session_1,12.0,12012384226.02022-12-30 22:44:00session_1,"hi! i&rsquo;m maya, your virtual assistant fro...",12012384226.02022-12-30 22:44:00session_1,12012384226.0,session_1,12.0,12012384226.02022-12-30 22:44:00session_1,hi > greetings > update account > chat with ou...
1,2022-12-30 22:45:00,unidentified client > talk to cse > want to en...,12012384226.0,session_1,12.0,12012384226.02022-12-30 22:45:00session_1,nan > your whatsapp number is not registered w...,12012384226.02022-12-30 22:45:00session_1,12012384226.0,session_1,12.0,12012384226.02022-12-30 22:45:00session_1,livechat service for whatsapp > nan > nan
2,2022-12-30 22:46:00,atlg3 > yes,12012384226.0,session_1,12.0,12012384226.02022-12-30 22:46:00session_1,do you wish to self-authenticate? > client acc...,12012384226.02022-12-30 22:46:00session_1,12012384226.0,session_1,12.0,12012384226.02022-12-30 22:46:00session_1,nan > nan
3,2022-12-30 22:47:00,1 > livechat service for whatsapp > unidentifi...,12012384226.0,session_1,12.0,12012384226.02022-12-30 22:47:00session_1,i&#39;m not sure if i can help you with your q...,12012384226.02022-12-30 22:47:00session_1,12012384226.0,session_1,12.0,12012384226.02022-12-30 22:47:00session_1,nan > chat with our expert > livechat service ...
4,2022-12-22 18:41:00,new client > available funds,12012891146.0,session_1,12.0,12012891146.02022-12-22 18:41:00session_1,nan > your whatsapp mobile number is not regis...,12012891146.02022-12-22 18:41:00session_1,12012891146.0,session_1,12.0,12012891146.02022-12-22 18:41:00session_1,wa self service authentication > nan

,Date_str2,User Query,Bot Response,User ID_y,sessions_y,month_y,concat_y,Intent Recognized
0,2022-12-30 22:44:00,hi > main menu > update accounts > livechat se...,"hi! i&rsquo;m maya, your virtual assistant fro...",12012384226.0,session_1,12.0,12012384226.02022-12-30 22:44:00session_1,hi > greetings > update account > chat with ou...
1,2022-12-30 22:45:00,unidentified client > talk to cse > want to en...,nan > your whatsapp number is not registered w...,12012384226.0,session_1,12.0,12012384226.02022-12-30 22:45:00session_1,livechat service for whatsapp > nan > nan

,Date_str2,User Query,Bot Response,ID,sessions,month,concat,Intent Recognized
0,2022-12-30 22:44:00,hi > main menu > update accounts > livechat se...,"hi! i&rsquo;m maya, your virtual assistant fro...",12012384226.0,session_1,12.0,12012384226.02022-12-30 22:44:00session_1,hi > greetings > update account > chat with ou...
1,2022-12-30 22:45:00,unidentified client > talk to cse > want to en...,nan > your whatsapp number is not registered w...,12012384226.0,session_1,12.0,12012384226.02022-12-30 22:45:00session_1,livechat service for whatsapp > nan > nan
2,2022-12-30 22:46:00,atlg3 > yes,do you wish to self-authenticate? > client acc...,12012384226.0,session_1,12.0,12012384226.02022-12-30 22:46:00session_1,nan > nan
3,2022-12-30 22:47:00,1 > livechat service for whatsapp > unidentifi...,i&#39;m not sure if i can help you with your q...,12012384226.0,session_1,12.0,12012384226.02022-12-30 22:47:00session_1,nan > chat with our expert > livechat service ...
4,2022-12-22 18:41:00,new client > available funds,nan > your whatsapp mobile number is not regis...,12012891146.0,session_1,12.0,12012891146.02022-12-22 18:41:00session_1,wa self service authentication > nan

,ID,sessions,month,concat,User Query,Bot Response,Intent Recognized
0,12012384226.0,session_1,12.0,12012384226.02022-12-30 22:44:00session_1,hi > main menu > update accounts > livechat se...,"hi! i&rsquo;m maya, your virtual assistant fro...",hi > greetings > update account > chat with ou...
1,12012384226.0,session_1,12.0,12012384226.02022-12-30 22:45:00session_1,unidentified client > talk to cse > want to en...,nan > your whatsapp number is not registered w...,livechat service for whatsapp > nan > nan

(251304, 7)

In [39]:
df2 = pd.concat([df_Final_Jul,df_Final_Aug,df_Final_Sept,df_Final_Oct,df_Final_Nov,df_Final_Dec])
df2.shape
df2.head()

(757260, 7)

,ID,sessions,month,concat,User Query,Bot Response,Intent Recognized
0,12014064675,session_1,1,120140646752022-01-14session_1,chat with our expert > unidentified client > d...,dear customer your whatsapp number is not regi...,nan > chat with our expert > nan > nan > nan >...
1,12019562030,session_1,1,120195620302022-01-25session_1,can i get a holding cum transaction valuation ...,absolutely. to get your holding cum transactio...,can i get a holding cum transaction valuation ...
2,12019562030,session_2,1,120195620302022-01-25session_2,chat with our expert > identidfied client > 1,your livechat request has been registered with...,nan > chat with our expert > nan
3,12019562030,session_3,1,120195620302022-01-27session_3,none of above. > what is the customer service ...,i&#39;m not sure if i can help you with your q...,nan > what is the customer service number for ...
4,12019562030,session_4,1,120195620302022-01-28session_4,can i get a holding cum transaction valuation ...,absolutely. to get your holding cum transactio...,can i get a holding cum transaction valuation ...

In [40]:
df2.fillna(0,inplace=True)

In [41]:
df2.columns

Index(['ID', 'sessions', 'month', 'concat', 'User Query', 'Bot Response',
       'Intent Recognized'],
      dtype='object')

In [42]:
df2.dtypes

ID                   object
sessions             object
month                 int64
concat               object
User Query           object
Bot Response         object
Intent Recognized    object
dtype: object

In [43]:
df2.loc[df2['User Query'].str.contains('expert|cse|agent|experts|livechat',na=False),'user_live_chat_raised_flag'] = 1
df2.loc[df2['User Query'].str.contains('existing client',na=False),'existing_client_flag'] = 1
df2.loc[df2['Bot Response'].str.contains('successfully authenticated',na=False),'Existing Client_N'] = 1
df2.loc[df2['User Query'].str.contains('new client',na=False),'new_client_flag'] = 1
df2.loc[df2['Bot Response'].str.contains('your livechat request has been registered with us',na=False),'Livechat_Raised_BOT'] = 1
df2.loc[df2['Bot Response'].str.contains('one of our livechat agents will get in touch with you shortly',na=False),'Livechat_agent_shortly_BOT'] = 1
df2.tail()

,ID,sessions,month,concat,User Query,Bot Response,Intent Recognized,user_live_chat_raised_flag,existing_client_flag,Existing Client_N,new_client_flag
66483,9779824006495,session_1,10,97798240064952022-10-04session_1,available funds > new client,your whatsapp mobile number is not registered ...,nan > wa self service authentication,NaN,NaN,NaN,1.0
66484,9779828725416,session_1,10,97798287254162022-10-25session_1,hi,"hi! i&rsquo;m maya, your virtual assistant fro...",hi,NaN,NaN,NaN,NaN
66485,9779851032744,session_1,10,97798510327442022-10-24session_1,funds related > want to talk to agent directly...,"due to high chat volumes, there may be a delay...",nan > nan > nan > livechat service for whatsap...,1.0,NaN,NaN,NaN
66486,9779866622462,session_1,10,97798666224622022-10-25session_1,hi,"hi! i&rsquo;m maya, your virtual assistant fro...",hi,NaN,NaN,NaN,NaN
66487,994502300424,session_1,10,9945023004242022-10-08session_1,hi,"hi! i&rsquo;m maya, your virtual assistant fro...",hi,NaN,NaN,NaN,NaN

In [44]:
df2.loc[df2['User Query'].str.contains('change address|update address',na=False),'acccount_updation_flag-address change'] = 1
df2.loc[df2['User Query'].str.contains('nominee updation|nominee updation',na=False),'acccount_updation_flag-nominee updation'] = 1
df2.loc[df2['User Query'].str.contains('activate segments|activate segment',na=False),'acccount_updation_flag-segment activation'] = 1
df2.loc[df2['User Query'].str.contains('gstin update|update gst number',na=False),'acccount_updation_flag-gstin update'] = 1
df2.loc[df2['User Query'].str.contains('offline to online|offline to online a/c conversion|convert to online',na=False),'acccount_updation_flag-convert to online'] = 1
df2.loc[df2['User Query'].str.contains('bank updation',na=False),'acccount_updation_flag-bank updation'] = 1
df2.loc[df2['User Query'].str.contains('convert account to neo|convert to neo|convert_to_neo|switch to neo|switch account to neo|switch_to_neo|switch to neo wh',na=False),'acccount_updation_flag-switch to neo'] = 1
df2.loc[df2['User Query'].str.contains('convert account to nest|convert to nest|convert_to_nest|switch to nest|switch account to nest|switch_to_nest|start nest wh',na=False),'acccount_updation_flag-switch to nest'] = 1
df2.loc[df2['User Query'].str.contains('change email id|email updation',na=False),'acccount_updation_flag-email id update'] = 1
df2.loc[df2['User Query'].str.contains('change mobile number|contact number updation',na=False),'acccount_updation_flag-mobile change'] = 1
df2.loc[df2['User Query'].str.contains('potential dormant activation',na=False),'acccount_updation_flag-potential dormant activation'] = 1

df2.loc[df2['User Query'].str.contains('account statements',na=False),'requests_flag-account statements'] = 1
df2.loc[df2['User Query'].str.contains('dis request',na=False),'requests_flag-dis request'] = 1
df2.loc[df2['User Query'].str.contains('account closure',na=False),'requests_flag-account closure'] = 1

df2.loc[df2['User Query'].str.contains('ipo allotment status|allotment status',na=False),'ipo_mf_related_flag-ipo allotment  status'] = 1
df2.loc[df2['User Query'].str.contains('apply ipo|apply for ipo',na=False),'ipo_mf_related_flag-apply ipo'] = 1
df2.loc[df2['User Query'].str.contains('apply for mutual fund',na=False),'ipo_mf_related_flag-apply for mf'] = 1

df2.loc[df2['User Query'].str.contains('available funds',na=False),'funds_payout_related_flag-available funds-available funds'] = 1
df2.loc[df2['User Query'].str.contains('available margin',na=False),'funds_payout_related_flag-available margin'] = 1
df2.loc[df2['User Query'].str.contains('funds payout',na=False),'funds_payout_related_flag-new payout request'] = 1
df2.loc[df2['User Query'].str.contains('payout status',na=False),'funds_payout_related_flag-payout status'] = 1

df2.loc[df2['User Query'].str.contains('portfolio valuation',na=False),'others_flag-portfolio valuation'] = 1
df2.loc[df2['User Query'].str.contains('forgot password',na=False),'others_flag-forgot password'] = 1


df2.fillna(0, inplace=True)
df2.replace(0, '', inplace=True)
df2

,ID,sessions,month,concat,User Query,Bot Response,Intent Recognized,user_live_chat_raised_flag,existing_client_flag,Existing Client_N,new_client_flag,acccount_updation_flag-address change,acccount_updation_flag-nominee updation,acccount_updation_flag-segment activation,acccount_updation_flag-gstin update,acccount_updation_flag-convert to online,acccount_updation_flag-bank updation,acccount_updation_flag-switch to neo,acccount_updation_flag-switch to nest,acccount_updation_flag-email id update,acccount_updation_flag-mobile change,acccount_updation_flag-potential dormant activation,requests_flag-account statements,requests_flag-dis request,requests_flag-account closure,ipo_mf_related_flag-ipo allotment status,ipo_mf_related_flag-apply ipo,ipo_mf_related_flag-apply for mf,funds_payout_related_flag-available funds-available funds,funds_payout_related_flag-available margin,funds_payout_related_flag-new payout request,funds_payout_related_flag-payout status,others_flag-portfolio valuation,others_flag-forgot password
0,12014064675,session_1,1,120140646752022-01-14session_1,chat with our expert > unidentified client > d...,dear customer your whatsapp number is not regi...,nan > chat with our expert > nan > nan > nan >...,1.0,,,,,,,,,,,,,,,,,,,,,,,,,,
1,12019562030,session_1,1,120195620302022-01-25session_1,can i get a holding cum transaction valuation ...,absolutely. to get your holding cum transactio...,can i get a holding cum transaction valuation ...,1.0,,,,,,,,,,,,,,,,,,,,,,,,,,
2,12019562030,session_2,1,120195620302022-01-25session_2,chat with our expert > identidfied client > 1,your livechat request has been registered with...,nan > chat with our expert > nan,1.0,,,,,,,,,,,,,,,,,,,,,,,,,,
3,12019562030,session_3,1,120195620302022-01-27session_3,none of above. > what is the customer service ...,i&#39;m not sure if i can help you with your q...,nan > what is the customer service number for ...,,,,,,,,,,,,,,,,,,,,,,,,,,,
4,12019562030,session_4,1,120195620302022-01-28session_4,can i get a holding cum transaction valuation ...,absolutely. to get your holding cum transactio...,can i get a holding cum transaction valuation ...,1.0,,,,,,,,,,,,,,,,,,,,,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66483,9779824006495,session_1,10,97798240064952022-10-04session_1,available funds > new client,your whatsapp mobile number is not registered ...,nan > wa self service authentication,,,,1.0,,,,,,,,,,,,,,,,,,1.0,,,,,
66484,9779828725416,session_1,10,97798287254162022-10-25session_1,hi,"hi! i&rsquo;m maya, your virtual assistant fro...",hi,,,,,,,,,,,,,,,,,,,,,,,,,,,
66485,9779851032744,session_1,10,97798510327442022-10-24session_1,funds related > want to talk to agent directly...,"due to high chat volumes, there may be a delay...",nan > nan > nan > livechat service for whatsap...,1.0,,,,,,,,,,,,,,,,,,,,,,,,,,
66486,9779866622462,session_1,10,97798666224622022-10-25session_1,hi,"hi! i&rsquo;m maya, your virtual assistant fro...",hi,,,,,,,,,,,,,,,,,,,,,,,,,,,
66487,994502300424,session_1,10,9945023004242022-10-08session_1,hi,"hi! i&rsquo;m maya, your virtual assistant fro...",hi,,,,,,,,,,,,,,,,,,,,,,,,,,,

In [62]:
#Account Updation
df2.loc[df2['Bot Response'].str.contains('update address template message was sent'),'address_update_flag'] = 1
df2.loc[df2['Bot Response'].str.contains('nominee updation template message was sent'),'nominee_updation_flag'] = 1
df2.loc[df2['Bot Response'].str.contains('activate segments template message was sent'),'activate_segments_flag'] = 1
df2.loc[df2['Bot Response'].str.contains('gst number updation template message was sent'),'gst_updation_flag'] = 1
df2.loc[df2['Bot Response'].str.contains('thank you for your request to convert your account into an online account| your account is already an'),'offline_to_online_flag'] = 1
df2.loc[df2['Bot Response'].str.contains('bank updation template message was sent'),'bank_updation_flag'] = 1
df2.loc[df2['Bot Response'].str.contains('thank you for the request to convert your account to neo|we see that your account is already converted to neo'),'Switch_to_neo_flag'] = 1
df2.loc[df2['Bot Response'].str.contains('thank you for your interest in nest trader terminal|thank you for the request to convert your account to nest|we see that your account is already converted to neo'),'Switch_to_nest_flag'] = 1
df2.loc[df2['Bot Response'].str.contains('update email id template message was sent'),'email_updation_flag'] = 1
df2.loc[df2['Bot Response'].str.contains('update mobile number template message was sent'),'mobile_updation_flag'] = 1

#Requests Related
df2.loc[df2['Bot Response'].str.contains('your request has been captured and we will send the statement on your registered email id'),'stmt_flag'] = 1
df2.loc[df2['Bot Response'].str.contains('dis request template message was sent'),'dis_request_flag'] = 1
df2.loc[df2['Bot Response'].str.contains('account closure template message was sent'),'Account_closure_flag'] = 1

#IPO & MF Related
df2.loc[df2['Bot Response'].str.contains('ipo template message was sent'),'apply_ipo_flag'] = 1
df2.loc[df2['Bot Response'].str.contains('please click on the below link to check the status of ipo'),'ipo_allotment_status_flag'] = 1
df2.loc[df2['Bot Response'].str.contains('apply mutual fund template message was sent'),'place_order_in_MF_flag'] = 1

#Funds & Payout related
df2.loc[df2['Bot Response'].str.contains('has following margin information'),'available_margin_flag'] = 1
df2.loc[df2['Bot Response'].str.contains('your amount available is'),'available_funds_flag'] = 1
df2.loc[df2['Bot Response'].str.contains('your request has been accepted|sorry, the transfer cannot go through due to insufficient balance in your trading account'),'new_payout_request_flag'] = 1
df2.loc[df2['Bot Response'].str.contains('your payout request for'),'payout_status_flag'] = 1

#Others
df2.loc[df2['Bot Response'].str.contains('hello, your portfolio value is'),'portfolio_valuation_flag'] = 1
df2.loc[df2['Bot Response'].str.contains('temporary password has been sent'),'forgot_password_flag'] = 1

#Additional
df2.loc[df2['Bot Response'].str.contains('your livechat request'),'bot_live_chat_flag'] = 1
#(this flag of bot live chat is not available in excel;but still have we created it for output purposes)

# df2.update(df2[['available_margin_flag','available_funds_flag','new_payout_request_flag','payout_status_flag','address_update_flag','activate_segments_flag','nominee_updation_flag','bank_updation_flag','']].fillna(0))
df2.fillna(0, inplace=True)
df2

,ID,sessions,month,concat,User Query,Bot Response,Intent Recognized,user_live_chat_raised_flag,existing_client_flag,Existing Client_N,new_client_flag,acccount_updation_flag-address change,acccount_updation_flag-nominee updation,acccount_updation_flag-segment activation,acccount_updation_flag-gstin update,acccount_updation_flag-convert to online,acccount_updation_flag-bank updation,acccount_updation_flag-switch to neo,acccount_updation_flag-switch to nest,acccount_updation_flag-email id update,acccount_updation_flag-mobile change,acccount_updation_flag-potential dormant activation,requests_flag-account statements,requests_flag-dis request,requests_flag-account closure,ipo_mf_related_flag-ipo allotment status,ipo_mf_related_flag-apply ipo,ipo_mf_related_flag-apply for mf,funds_payout_related_flag-available funds-available funds,funds_payout_related_flag-available margin,funds_payout_related_flag-new payout request,funds_payout_related_flag-payout status,others_flag-portfolio valuation,others_flag-forgot password,address_update_flag,nominee_updation_flag,activate_segments_flag,gst_updation_flag,offline_to_online_flag,bank_updation_flag,Switch_to_neo_flag,Switch_to_nest_flag,email_updation_flag,mobile_updation_flag,stmt_flag,dis_request_flag,Account_closure_flag,apply_ipo_flag,ipo_allotment_status_flag,place_order_in_MF_flag,available_margin_flag,available_funds_flag,new_payout_request_flag,payout_status_flag,portfolio_valuation_flag,forgot_password_flag,bot_live_chat_flag
0,12014064675,session_1,1,120140646752022-01-14session_1,chat with our expert > unidentified client > d...,dear customer your whatsapp number is not regi...,nan > chat with our expert > nan > nan > nan >...,1.0,,,,,,,,,,,,,,,,,,,,,,,,,,,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,12019562030,session_1,1,120195620302022-01-25session_1,can i get a holding cum transaction valuation ...,absolutely. to get your holding cum transactio...,can i get a holding cum transaction valuation ...,1.0,,,,,,,,,,,,,,,,,,,,,,,,,,,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,12019562030,session_2,1,120195620302022-01-25session_2,chat with our expert > identidfied client > 1,your livechat request has been registered with...,nan > chat with our expert > nan,1.0,,,,,,,,,,,,,,,,,,,,,,,,,,,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,12019562030,session_3,1,120195620302022-01-27session_3,none of above. > what is the customer service ...,i39m not sure if i can help you with your quer...,nan > what is the customer service number for ...,,,,,,,,,,,,,,,,,,,,,,,,,,,,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,12019562030,session_4,1,120195620302022-01-28session_4,can i get a holding cum transaction valuation ...,absolutely. to get your holding cum transactio...,can i get a holding cum transaction valuation ...,1.0,,,,,,,,,,,,,,,,,,,,,,,,,,,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66483,9779824006495,session_1,10,97798240064952022-10-04session_1,available funds > new client,your whatsapp mobile number is not registered ...,nan > wa self service authentication,,,,1.0,,,,,,,,,,,,,,,,,,1.0,,,,,,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
66484,9779828725416,session_1,10,97798287254162022-10-25session_1,hi,hi irsquom maya your virtual assistant from ko...,hi,,,,,,,,,,,,,,,,,,,,,,,,,,,,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
66485,9779851032744,session_1,10,97798510327442022-10-24session_1,funds related > want to talk to agent directly...,due to high chat volumes there may be a delay ...,nan > nan > nan > livechat service for whatsap...,1.0,,,,,,,,,,,,,,,,,,,,,,,,,,,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
66486,9779866622462,session_1,10,97798666224622022-10-25session_1,hi,hi irsquom maya your virtual assistant from ko...,hi,,,,,,,,,,,,,,,,,,,,,,,,,,,,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
66487,994502300424,session_1,10,9945023004242022-10-08session_1,hi,hi irsquom maya your virtual assistant from ko...,hi,,,,,,,,,,,,,,,,,,,,,,,,,,,,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [63]:
df2.replace(regex=True,inplace=True,to_replace=r"[#!$&*+@%,;'']",value=r'')
df2.head()

,ID,sessions,month,concat,User Query,Bot Response,Intent Recognized,user_live_chat_raised_flag,existing_client_flag,Existing Client_N,new_client_flag,acccount_updation_flag-address change,acccount_updation_flag-nominee updation,acccount_updation_flag-segment activation,acccount_updation_flag-gstin update,acccount_updation_flag-convert to online,acccount_updation_flag-bank updation,acccount_updation_flag-switch to neo,acccount_updation_flag-switch to nest,acccount_updation_flag-email id update,acccount_updation_flag-mobile change,acccount_updation_flag-potential dormant activation,requests_flag-account statements,requests_flag-dis request,requests_flag-account closure,ipo_mf_related_flag-ipo allotment status,ipo_mf_related_flag-apply ipo,ipo_mf_related_flag-apply for mf,funds_payout_related_flag-available funds-available funds,funds_payout_related_flag-available margin,funds_payout_related_flag-new payout request,funds_payout_related_flag-payout status,others_flag-portfolio valuation,others_flag-forgot password,address_update_flag,nominee_updation_flag,activate_segments_flag,gst_updation_flag,offline_to_online_flag,bank_updation_flag,Switch_to_neo_flag,Switch_to_nest_flag,email_updation_flag,mobile_updation_flag,stmt_flag,dis_request_flag,Account_closure_flag,apply_ipo_flag,ipo_allotment_status_flag,place_order_in_MF_flag,available_margin_flag,available_funds_flag,new_payout_request_flag,payout_status_flag,portfolio_valuation_flag,forgot_password_flag,bot_live_chat_flag
0,12014064675,session_1,1,120140646752022-01-14session_1,chat with our expert > unidentified client > d...,dear customer your whatsapp number is not regi...,nan > chat with our expert > nan > nan > nan >...,1.0,,,,,,,,,,,,,,,,,,,,,,,,,,,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,12019562030,session_1,1,120195620302022-01-25session_1,can i get a holding cum transaction valuation ...,absolutely. to get your holding cum transactio...,can i get a holding cum transaction valuation ...,1.0,,,,,,,,,,,,,,,,,,,,,,,,,,,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,12019562030,session_2,1,120195620302022-01-25session_2,chat with our expert > identidfied client > 1,your livechat request has been registered with...,nan > chat with our expert > nan,1.0,,,,,,,,,,,,,,,,,,,,,,,,,,,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,12019562030,session_3,1,120195620302022-01-27session_3,none of above. > what is the customer service ...,i39m not sure if i can help you with your quer...,nan > what is the customer service number for ...,,,,,,,,,,,,,,,,,,,,,,,,,,,,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,12019562030,session_4,1,120195620302022-01-28session_4,can i get a holding cum transaction valuation ...,absolutely. to get your holding cum transactio...,can i get a holding cum transaction valuation ...,1.0,,,,,,,,,,,,,,,,,,,,,,,,,,,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [64]:
df2.fillna(0, inplace=True)

In [65]:
df2.columns

Index(['ID', 'sessions', 'month', 'concat', 'User Query', 'Bot Response',
       'Intent Recognized', 'user_live_chat_raised_flag',
       'existing_client_flag', 'Existing Client_N', 'new_client_flag',
       'acccount_updation_flag-address change',
       'acccount_updation_flag-nominee updation',
       'acccount_updation_flag-segment activation',
       'acccount_updation_flag-gstin update',
       'acccount_updation_flag-convert to online',
       'acccount_updation_flag-bank updation',
       'acccount_updation_flag-switch to neo',
       'acccount_updation_flag-switch to nest',
       'acccount_updation_flag-email id update',
       'acccount_updation_flag-mobile change',
       'acccount_updation_flag-potential dormant activation',
       'requests_flag-account statements', 'requests_flag-dis request',
       'requests_flag-account closure',
       'ipo_mf_related_flag-ipo allotment  status',
       'ipo_mf_related_flag-apply ipo', 'ipo_mf_related_flag-apply for mf',
       'funds_payout_related_flag-available funds-available funds',
       'funds_payout_related_flag-available margin',
       'funds_payout_related_flag-new payout request',
       'funds_payout_related_flag-payout status',
       'others_flag-portfolio valuation', 'others_flag-forgot password',
       'address_update_flag', 'nominee_updation_flag',
       'activate_segments_flag', 'gst_updation_flag', 'offline_to_online_flag',
       'bank_updation_flag', 'Switch_to_neo_flag', 'Switch_to_nest_flag',
       'email_updation_flag', 'mobile_updation_flag', 'stmt_flag',
       'dis_request_flag', 'Account_closure_flag', 'apply_ipo_flag',
       'ipo_allotment_status_flag', 'place_order_in_MF_flag',
       'available_margin_flag', 'available_funds_flag',
       'new_payout_request_flag', 'payout_status_flag',
       'portfolio_valuation_flag', 'forgot_password_flag',
       'bot_live_chat_flag'],
      dtype='object')

In [67]:
df2.head()
df2.shape

,ID,sessions,month,concat,User Query,Bot Response,Intent Recognized,user_live_chat_raised_flag,existing_client_flag,Existing Client_N,new_client_flag,acccount_updation_flag-address change,acccount_updation_flag-nominee updation,acccount_updation_flag-segment activation,acccount_updation_flag-gstin update,acccount_updation_flag-convert to online,acccount_updation_flag-bank updation,acccount_updation_flag-switch to neo,acccount_updation_flag-switch to nest,acccount_updation_flag-email id update,acccount_updation_flag-mobile change,acccount_updation_flag-potential dormant activation,requests_flag-account statements,requests_flag-dis request,requests_flag-account closure,ipo_mf_related_flag-ipo allotment status,ipo_mf_related_flag-apply ipo,ipo_mf_related_flag-apply for mf,funds_payout_related_flag-available funds-available funds,funds_payout_related_flag-available margin,funds_payout_related_flag-new payout request,funds_payout_related_flag-payout status,others_flag-portfolio valuation,others_flag-forgot password,address_update_flag,nominee_updation_flag,activate_segments_flag,gst_updation_flag,offline_to_online_flag,bank_updation_flag,Switch_to_neo_flag,Switch_to_nest_flag,email_updation_flag,mobile_updation_flag,stmt_flag,dis_request_flag,Account_closure_flag,apply_ipo_flag,ipo_allotment_status_flag,place_order_in_MF_flag,available_margin_flag,available_funds_flag,new_payout_request_flag,payout_status_flag,portfolio_valuation_flag,forgot_password_flag,bot_live_chat_flag
0,12014064675,session_1,1,120140646752022-01-14session_1,chat with our expert > unidentified client > d...,dear customer your whatsapp number is not regi...,nan > chat with our expert > nan > nan > nan >...,1.0,,,,,,,,,,,,,,,,,,,,,,,,,,,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,12019562030,session_1,1,120195620302022-01-25session_1,can i get a holding cum transaction valuation ...,absolutely. to get your holding cum transactio...,can i get a holding cum transaction valuation ...,1.0,,,,,,,,,,,,,,,,,,,,,,,,,,,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,12019562030,session_2,1,120195620302022-01-25session_2,chat with our expert > identidfied client > 1,your livechat request has been registered with...,nan > chat with our expert > nan,1.0,,,,,,,,,,,,,,,,,,,,,,,,,,,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,12019562030,session_3,1,120195620302022-01-27session_3,none of above. > what is the customer service ...,i39m not sure if i can help you with your quer...,nan > what is the customer service number for ...,,,,,,,,,,,,,,,,,,,,,,,,,,,,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,12019562030,session_4,1,120195620302022-01-28session_4,can i get a holding cum transaction valuation ...,absolutely. to get your holding cum transactio...,can i get a holding cum transaction valuation ...,1.0,,,,,,,,,,,,,,,,,,,,,,,,,,,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

(757260, 57)

In [68]:
df2['User Query']

0        chat with our expert > unidentified client > d...
1        can i get a holding cum transaction valuation ...
2            chat with our expert > identidfied client > 1
3        none of above. > what is the customer service ...
4        can i get a holding cum transaction valuation ...
                               ...
66483                         available funds > new client
66484                                                   hi
66485    funds related > want to talk to agent directly...
66486                                                   hi
66487                                                   hi
Name: User Query, Length: 757260, dtype: object

In [208]:
df3=df2.copy()

In [209]:
df3.head()
df3.shape

,ID,sessions,month,concat,User Query,Bot Response,Intent Recognized,user_live_chat_raised_flag,existing_client_flag,Existing Client_N,new_client_flag,acccount_updation_flag-address change,acccount_updation_flag-nominee updation,acccount_updation_flag-segment activation,acccount_updation_flag-gstin update,acccount_updation_flag-convert to online,acccount_updation_flag-bank updation,acccount_updation_flag-switch to neo,acccount_updation_flag-switch to nest,acccount_updation_flag-email id update,acccount_updation_flag-mobile change,acccount_updation_flag-potential dormant activation,requests_flag-account statements,requests_flag-dis request,requests_flag-account closure,ipo_mf_related_flag-ipo allotment status,ipo_mf_related_flag-apply ipo,ipo_mf_related_flag-apply for mf,funds_payout_related_flag-available funds-available funds,funds_payout_related_flag-available margin,funds_payout_related_flag-new payout request,funds_payout_related_flag-payout status,others_flag-portfolio valuation,others_flag-forgot password,address_update_flag,nominee_updation_flag,activate_segments_flag,gst_updation_flag,offline_to_online_flag,bank_updation_flag,Switch_to_neo_flag,Switch_to_nest_flag,email_updation_flag,mobile_updation_flag,stmt_flag,dis_request_flag,Account_closure_flag,apply_ipo_flag,ipo_allotment_status_flag,place_order_in_MF_flag,available_margin_flag,available_funds_flag,new_payout_request_flag,payout_status_flag,portfolio_valuation_flag,forgot_password_flag,bot_live_chat_flag
0,12014064675,session_1,1,120140646752022-01-14session_1,chat with our expert > unidentified client > d...,dear customer your whatsapp number is not regi...,nan > chat with our expert > nan > nan > nan >...,1.0,,,,,,,,,,,,,,,,,,,,,,,,,,,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,12019562030,session_1,1,120195620302022-01-25session_1,can i get a holding cum transaction valuation ...,absolutely. to get your holding cum transactio...,can i get a holding cum transaction valuation ...,1.0,,,,,,,,,,,,,,,,,,,,,,,,,,,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,12019562030,session_2,1,120195620302022-01-25session_2,chat with our expert > identidfied client > 1,your livechat request has been registered with...,nan > chat with our expert > nan,1.0,,,,,,,,,,,,,,,,,,,,,,,,,,,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,12019562030,session_3,1,120195620302022-01-27session_3,none of above. > what is the customer service ...,i39m not sure if i can help you with your quer...,nan > what is the customer service number for ...,,,,,,,,,,,,,,,,,,,,,,,,,,,,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,12019562030,session_4,1,120195620302022-01-28session_4,can i get a holding cum transaction valuation ...,absolutely. to get your holding cum transactio...,can i get a holding cum transaction valuation ...,1.0,,,,,,,,,,,,,,,,,,,,,,,,,,,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

(757260, 57)

In [211]:
df3['Event_User1']=df3['User Query'].str.split(">",expand = True)[0]
df3.head()

,ID,sessions,month,concat,User Query,Bot Response,Intent Recognized,user_live_chat_raised_flag,existing_client_flag,Existing Client_N,new_client_flag,acccount_updation_flag-address change,acccount_updation_flag-nominee updation,acccount_updation_flag-segment activation,acccount_updation_flag-gstin update,acccount_updation_flag-convert to online,acccount_updation_flag-bank updation,acccount_updation_flag-switch to neo,acccount_updation_flag-switch to nest,acccount_updation_flag-email id update,acccount_updation_flag-mobile change,acccount_updation_flag-potential dormant activation,requests_flag-account statements,requests_flag-dis request,requests_flag-account closure,ipo_mf_related_flag-ipo allotment status,ipo_mf_related_flag-apply ipo,ipo_mf_related_flag-apply for mf,funds_payout_related_flag-available funds-available funds,funds_payout_related_flag-available margin,funds_payout_related_flag-new payout request,funds_payout_related_flag-payout status,others_flag-portfolio valuation,others_flag-forgot password,address_update_flag,nominee_updation_flag,activate_segments_flag,gst_updation_flag,offline_to_online_flag,bank_updation_flag,Switch_to_neo_flag,Switch_to_nest_flag,email_updation_flag,mobile_updation_flag,stmt_flag,dis_request_flag,Account_closure_flag,apply_ipo_flag,ipo_allotment_status_flag,place_order_in_MF_flag,available_margin_flag,available_funds_flag,new_payout_request_flag,payout_status_flag,portfolio_valuation_flag,forgot_password_flag,bot_live_chat_flag,Event_User1
0,12014064675,session_1,1,120140646752022-01-14session_1,chat with our expert > unidentified client > d...,dear customer your whatsapp number is not regi...,nan > chat with our expert > nan > nan > nan >...,1.0,,,,,,,,,,,,,,,,,,,,,,,,,,,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,chat with our expert
1,12019562030,session_1,1,120195620302022-01-25session_1,can i get a holding cum transaction valuation ...,absolutely. to get your holding cum transactio...,can i get a holding cum transaction valuation ...,1.0,,,,,,,,,,,,,,,,,,,,,,,,,,,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,can i get a holding cum transaction valuation ...
2,12019562030,session_2,1,120195620302022-01-25session_2,chat with our expert > identidfied client > 1,your livechat request has been registered with...,nan > chat with our expert > nan,1.0,,,,,,,,,,,,,,,,,,,,,,,,,,,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,chat with our expert
3,12019562030,session_3,1,120195620302022-01-27session_3,none of above. > what is the customer service ...,i39m not sure if i can help you with your quer...,nan > what is the customer service number for ...,,,,,,,,,,,,,,,,,,,,,,,,,,,,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,none of above.
4,12019562030,session_4,1,120195620302022-01-28session_4,can i get a holding cum transaction valuation ...,absolutely. to get your holding cum transactio...,can i get a holding cum transaction valuation ...,1.0,,,,,,,,,,,,,,,,,,,,,,,,,,,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,can i get a holding cum transaction valuation ...

In [212]:
df3['Event_str']=df3['Event_User1'].astype('str')

In [213]:
df3['Event_str'].fillna(0, inplace=True)

In [214]:
df3.loc[df3['Event_str'].str.contains('expert|experts|cse|agent|livechat'),'expert/livechat_flag_start'] = 1

In [215]:
df3.shape

(757260, 60)

In [216]:
df3.head()

,ID,sessions,month,concat,User Query,Bot Response,Intent Recognized,user_live_chat_raised_flag,existing_client_flag,Existing Client_N,new_client_flag,acccount_updation_flag-address change,acccount_updation_flag-nominee updation,acccount_updation_flag-segment activation,acccount_updation_flag-gstin update,acccount_updation_flag-convert to online,acccount_updation_flag-bank updation,acccount_updation_flag-switch to neo,acccount_updation_flag-switch to nest,acccount_updation_flag-email id update,acccount_updation_flag-mobile change,acccount_updation_flag-potential dormant activation,requests_flag-account statements,requests_flag-dis request,requests_flag-account closure,ipo_mf_related_flag-ipo allotment status,ipo_mf_related_flag-apply ipo,ipo_mf_related_flag-apply for mf,funds_payout_related_flag-available funds-available funds,funds_payout_related_flag-available margin,funds_payout_related_flag-new payout request,funds_payout_related_flag-payout status,others_flag-portfolio valuation,others_flag-forgot password,address_update_flag,nominee_updation_flag,activate_segments_flag,gst_updation_flag,offline_to_online_flag,bank_updation_flag,Switch_to_neo_flag,Switch_to_nest_flag,email_updation_flag,mobile_updation_flag,stmt_flag,dis_request_flag,Account_closure_flag,apply_ipo_flag,ipo_allotment_status_flag,place_order_in_MF_flag,available_margin_flag,available_funds_flag,new_payout_request_flag,payout_status_flag,portfolio_valuation_flag,forgot_password_flag,bot_live_chat_flag,Event_User1,Event_str,expert/livechat_flag_start
0,12014064675,session_1,1,120140646752022-01-14session_1,chat with our expert > unidentified client > d...,dear customer your whatsapp number is not regi...,nan > chat with our expert > nan > nan > nan >...,1.0,,,,,,,,,,,,,,,,,,,,,,,,,,,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,chat with our expert,chat with our expert,1.0
1,12019562030,session_1,1,120195620302022-01-25session_1,can i get a holding cum transaction valuation ...,absolutely. to get your holding cum transactio...,can i get a holding cum transaction valuation ...,1.0,,,,,,,,,,,,,,,,,,,,,,,,,,,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,can i get a holding cum transaction valuation ...,can i get a holding cum transaction valuation ...,NaN
2,12019562030,session_2,1,120195620302022-01-25session_2,chat with our expert > identidfied client > 1,your livechat request has been registered with...,nan > chat with our expert > nan,1.0,,,,,,,,,,,,,,,,,,,,,,,,,,,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,chat with our expert,chat with our expert,1.0
3,12019562030,session_3,1,120195620302022-01-27session_3,none of above. > what is the customer service ...,i39m not sure if i can help you with your quer...,nan > what is the customer service number for ...,,,,,,,,,,,,,,,,,,,,,,,,,,,,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,none of above.,none of above.,NaN
4,12019562030,session_4,1,120195620302022-01-28session_4,can i get a holding cum transaction valuation ...,absolutely. to get your holding cum transactio...,can i get a holding cum transaction valuation ...,1.0,,,,,,,,,,,,,,,,,,,,,,,,,,,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,can i get a holding cum transaction valuation ...,can i get a holding cum transaction valuation ...,NaN

In [218]:
df3.loc[df3['Bot Response'].str.contains('one of our livechat agents will get in touch with you shortly',na=False),'Livechat_agent_shortly_BOT'] = 1

       expert/livechat_flag_start
month
1                          8875.0
2                          9114.0
3                          9214.0
4                          8612.0
5                          6960.0
6                          4548.0
7                          5618.0
8                          6050.0
9                          5768.0
10                         4424.0

In [ ]:
newdf = df3["User Query"].str.split("want to talk to agent directly|chat with our expert|chat with an expert", n = 1, expand = True)

In [ ]:
df3["First"]= newdf[0]

In [ ]:
df3["Last"]= newdf[1]

In [ ]:
df3.head(5)
df3.shape

In [ ]:
df3.to_csv(r"E:\Analytics_Shared\Devika Patawari\Bot Analysis\Output\Trials for october\Whatsapp_July_Dec_2022.csv",index=False)

# END

#### Creating new flag of livechat on Bot query (to find how many requests were recieved/captured by BOT)

In [7]:
df= pd.read_excel(r"\\10.6.103.60\Analytics_Shared\Devika Patawari\Bot Analysis\Output\WhatsappChat_FinalTill_Octv1.xlsx", sheet_name= 'WhatsappChat_FinalTill_Octv1')

NameError: name 'df3' is not defined

In [8]:
df.head(5)
df.shape

,ID,Mobile no.,sessions,month,concat,User Query,Bot Response,Intent Recognized,user_live_chat_raised_flag,expert/livechat_flag_start,existing_client_flag,Existing Client_N,Existing Client_Flag,new_client_flag,bot_live_chat_flag,live chat flag,Event_User1,Event_str,acccount_updation_flag-address change,acccount_updation_flag-nominee updation,acccount_updation_flag-segment activation,acccount_updation_flag-gstin update,acccount_updation_flag-convert to online,acccount_updation_flag-bank updation,acccount_updation_flag-switch to neo,acccount_updation_flag-switch to nest,acccount_updation_flag-email id update,acccount_updation_flag-mobile change,acccount_updation_flag-potential dormant activation,requests_flag-account statements,requests_flag-dis request,requests_flag-account closure,ipo_mf_related_flag-ipo allotment status,ipo_mf_related_flag-apply ipo,ipo_mf_related_flag-apply for mf,funds_payout_related_flag-available funds-available funds,funds_payout_related_flag-available margin,funds_payout_related_flag-new payout request,funds_payout_related_flag-payout status,others_flag-portfolio valuation,others_flag-forgot password,self_service_sum,self_service_flag,address_update_flag,nominee_updation_flag,activate_segments_flag,gst_updation_flag,offline_to_online_flag,bank_updation_flag,Switch_to_neo_flag,Switch_to_nest_flag,email_updation_flag,mobile_updation_flag,stmt_flag,dis_request_flag,Account_closure_flag,apply_ipo_flag,ipo_allotment_status_flag,place_order_in_MF_flag,available_margin_flag,available_funds_flag,new_payout_request_flag,payout_status_flag,portfolio_valuation_flag,forgot_password_flag,End_resolution,end-msg_flag
0,12014064675,2014064675,session_1,1.0,120140646752022-01-14session_1,chat with our expert > unidentified client > d...,dear customer your whatsapp number is not regi...,nan > chat with our expert > nan > nan > nan >...,1.0,1.0,NaN,NaN,0,NaN,1.0,1,chat with our expert,chat with our expert,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0.0,0,0
1,12019562030,2019562030,session_1,1.0,120195620302022-01-25session_1,can i get a holding cum transaction valuation ...,absolutely. to get your holding cum transactio...,can i get a holding cum transaction valuation ...,1.0,NaN,NaN,NaN,0,NaN,1.0,1,can i get a holding cum transaction valuation ...,can i get a holding cum transaction valuation ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0.0,0,0
2,12019562030,2019562030,session_2,1.0,120195620302022-01-25session_2,chat with our expert > identidfied client > 1,your livechat request has been registered with...,nan > chat with our expert > nan,1.0,1.0,NaN,NaN,0,NaN,1.0,1,chat with our expert,chat with our expert,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0.0,0,0
3,12019562030,2019562030,session_3,1.0,120195620302022-01-27session_3,none of above. > what is the customer service ...,i39m not sure if i can help you with your quer...,nan > what is the customer service number for ...,NaN,NaN,NaN,NaN,0,NaN,0.0,0,none of above.,none of above.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0.0,0,0
4,12019562030,2019562030,session_4,1.0,120195620302022-01-28session_4,can i get a holding cum transaction valuation ...,absolutely. to get your holding cum transactio...,can i get a holding cum transaction valuation ...,1.0,NaN,NaN,NaN,0,NaN,1.0,1,can i get a holding cum transaction valuation ...,can i get a holding cum transaction valuation ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0.0,0,0

(757269, 67)

In [9]:
df.loc[df['Bot Response'].str.contains('your livechat request has been registered with us',na=False),'Livechat_Raised_BOT'] = 1

In [10]:
df.head(10)

,ID,Mobile no.,sessions,month,concat,User Query,Bot Response,Intent Recognized,user_live_chat_raised_flag,expert/livechat_flag_start,existing_client_flag,Existing Client_N,Existing Client_Flag,new_client_flag,bot_live_chat_flag,live chat flag,Event_User1,Event_str,acccount_updation_flag-address change,acccount_updation_flag-nominee updation,acccount_updation_flag-segment activation,acccount_updation_flag-gstin update,acccount_updation_flag-convert to online,acccount_updation_flag-bank updation,acccount_updation_flag-switch to neo,acccount_updation_flag-switch to nest,acccount_updation_flag-email id update,acccount_updation_flag-mobile change,acccount_updation_flag-potential dormant activation,requests_flag-account statements,requests_flag-dis request,requests_flag-account closure,ipo_mf_related_flag-ipo allotment status,ipo_mf_related_flag-apply ipo,ipo_mf_related_flag-apply for mf,funds_payout_related_flag-available funds-available funds,funds_payout_related_flag-available margin,funds_payout_related_flag-new payout request,funds_payout_related_flag-payout status,others_flag-portfolio valuation,others_flag-forgot password,self_service_sum,self_service_flag,address_update_flag,nominee_updation_flag,activate_segments_flag,gst_updation_flag,offline_to_online_flag,bank_updation_flag,Switch_to_neo_flag,Switch_to_nest_flag,email_updation_flag,mobile_updation_flag,stmt_flag,dis_request_flag,Account_closure_flag,apply_ipo_flag,ipo_allotment_status_flag,place_order_in_MF_flag,available_margin_flag,available_funds_flag,new_payout_request_flag,payout_status_flag,portfolio_valuation_flag,forgot_password_flag,End_resolution,end-msg_flag,Livechat_Raised_BOT
0,12014064675,2014064675,session_1,1.0,120140646752022-01-14session_1,chat with our expert > unidentified client > d...,dear customer your whatsapp number is not regi...,nan > chat with our expert > nan > nan > nan >...,1.0,1.0,NaN,NaN,0,NaN,1.0,1,chat with our expert,chat with our expert,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0.0,0,0,1.0
1,12019562030,2019562030,session_1,1.0,120195620302022-01-25session_1,can i get a holding cum transaction valuation ...,absolutely. to get your holding cum transactio...,can i get a holding cum transaction valuation ...,1.0,NaN,NaN,NaN,0,NaN,1.0,1,can i get a holding cum transaction valuation ...,can i get a holding cum transaction valuation ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0.0,0,0,1.0
2,12019562030,2019562030,session_2,1.0,120195620302022-01-25session_2,chat with our expert > identidfied client > 1,your livechat request has been registered with...,nan > chat with our expert > nan,1.0,1.0,NaN,NaN,0,NaN,1.0,1,chat with our expert,chat with our expert,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0.0,0,0,1.0
3,12019562030,2019562030,session_3,1.0,120195620302022-01-27session_3,none of above. > what is the customer service ...,i39m not sure if i can help you with your quer...,nan > what is the customer service number for ...,NaN,NaN,NaN,NaN,0,NaN,0.0,0,none of above.,none of above.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0.0,0,0,NaN
4,12019562030,2019562030,session_4,1.0,120195620302022-01-28session_4,can i get a holding cum transaction valuation ...,absolutely. to get your holding cum transactio...,can i get a holding cum transaction valuation ...,1.0,NaN,NaN,NaN,0,NaN,1.0,1,can i get a holding cum transaction valuation ...,can i get a holding cum transaction valuation ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0.0,0,0,1.0
5,12019562030,2019562030,session_5,1.0,120195620302022-01-28session_5,chat with our expert > identidfied client > ca...,your livechat request has been registered with...,nan > chat with our expert > can i get a holdi...,1.0,1.0,NaN,NaN,0,NaN,1.0,1,chat with our expert,chat with our expert,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0.0,0,0,1.0
6,12019562030,2019562030,session_6,1.0,120195620302022-01-28session_6,chat with our expert > identidfied client > ca...,your livechat request has been registered with...,nan > chat with our expert > can i get a holdi...,1.0,1.0,NaN,NaN,0,NaN,1.0,1,chat with our expert,chat with our expert,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0.0,0,0,1.0
7,12046983231,2046983231,session_1,1.0,120469832312022-01-18session_1,hi > ask mob number or code > chat with our ex...,hi i39m maya. how may i help you today? > kind...,greetings > nan > nan > chat with our expert >...,1.0,NaN,NaN,NaN,0,NaN,1.0,1,hi,hi,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0.0,0,0,1.0
8,12063120434,2063120434,session_1,1.0,120631204342022-01-25session_1,hi > apply ipo > new client > allotment status...,hi i39m maya. how may i help you today? > dear...,greetings > nan > wa self service authenticati...,NaN,NaN,NaN,NaN,0,1.0,0.0,0,hi,hi,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0,0,0.0,0.0,1,1,NaN
9,12063120434,2063120434,session_2,1.0,120631204342022-01-26session_2,allotment status > ipo > main menu,please click on the below link to check the st...,allotments status > ipo > greetings,NaN,NaN,NaN,NaN,0,NaN,0.0,0,allotment status,allotment status,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0,0,0.0,0.0,1,1,NaN

In [13]:
df.to_excel(r"\\10.6.103.60\Analytics_Shared\Devika Patawari\Bot Analysis\Output\WhatsappChat_FinalTill_Octv2.xlsx",index=False)

### Doing on only Oct Data

In [14]:
df= pd.read_excel(r"\\10.6.103.60\Analytics_Shared\Devika Patawari\Bot Analysis\Output\Trials for october\October_Data.xlsx")
df.head(5)
df.shape

,ID,Mobile no.,sessions,month,concat,User Query,Bot Response,Intent Recognized,user_live_chat_raised_flag,expert/livechat_flag_start,existing_client_flag,Existing Client_N,Existing Client_Flag,new_client_flag,bot_live_chat_flag,live chat flag,Event_User1,Event_str,acccount_updation_flag-address change,acccount_updation_flag-nominee updation,acccount_updation_flag-segment activation,acccount_updation_flag-gstin update,acccount_updation_flag-convert to online,acccount_updation_flag-bank updation,acccount_updation_flag-switch to neo,acccount_updation_flag-switch to nest,acccount_updation_flag-email id update,acccount_updation_flag-mobile change,acccount_updation_flag-potential dormant activation,requests_flag-account statements,requests_flag-dis request,requests_flag-account closure,ipo_mf_related_flag-ipo allotment status,ipo_mf_related_flag-apply ipo,ipo_mf_related_flag-apply for mf,funds_payout_related_flag-available funds-available funds,funds_payout_related_flag-available margin,funds_payout_related_flag-new payout request,funds_payout_related_flag-payout status,others_flag-portfolio valuation,others_flag-forgot password,self_service_sum,self_service_flag,address_update_flag,nominee_updation_flag,activate_segments_flag,gst_updation_flag,offline_to_online_flag,bank_updation_flag,Switch_to_neo_flag,Switch_to_nest_flag,email_updation_flag,mobile_updation_flag,stmt_flag,dis_request_flag,Account_closure_flag,apply_ipo_flag,ipo_allotment_status_flag,place_order_in_MF_flag,available_margin_flag,available_funds_flag,new_payout_request_flag,payout_status_flag,portfolio_valuation_flag,forgot_password_flag,End_resolution,end-msg_flag
0,994502300424,4502300424,session_1,10,9945023004242022-10-08session_1,hi,hi irsquom maya your virtual assistant from ko...,hi,NaN,NaN,NaN,NaN,0,NaN,0.0,0,hi,hi,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0
1,9779866622462,9866622462,session_1,10,97798666224622022-10-25session_1,hi,hi irsquom maya your virtual assistant from ko...,hi,NaN,NaN,NaN,NaN,0,NaN,0.0,0,hi,hi,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0
2,9779851032744,9851032744,session_1,10,97798510327442022-10-24session_1,funds related > want to talk to agent directly...,due to high chat volumes there may be a delay ...,nan > nan > nan > livechat service for whatsap...,1.0,NaN,NaN,NaN,0,NaN,1.0,1,funds related,funds related,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0
3,9779828725416,9828725416,session_1,10,97798287254162022-10-25session_1,hi,hi irsquom maya your virtual assistant from ko...,hi,NaN,NaN,NaN,NaN,0,NaN,0.0,0,hi,hi,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0
4,9779824006495,9824006495,session_1,10,97798240064952022-10-04session_1,available funds > new client,your whatsapp mobile number is not registered ...,nan > wa self service authentication,NaN,NaN,NaN,NaN,0,1.0,0.0,0,available funds,available funds,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0

(66488, 67)

In [15]:
df.loc[df['Bot Response'].str.contains('your livechat request has been registered with us',na=False),'Livechat_Raised_BOT'] = 1

In [17]:
df.head(5)

,ID,Mobile no.,sessions,month,concat,User Query,Bot Response,Intent Recognized,user_live_chat_raised_flag,expert/livechat_flag_start,existing_client_flag,Existing Client_N,Existing Client_Flag,new_client_flag,bot_live_chat_flag,live chat flag,Event_User1,Event_str,acccount_updation_flag-address change,acccount_updation_flag-nominee updation,acccount_updation_flag-segment activation,acccount_updation_flag-gstin update,acccount_updation_flag-convert to online,acccount_updation_flag-bank updation,acccount_updation_flag-switch to neo,acccount_updation_flag-switch to nest,acccount_updation_flag-email id update,acccount_updation_flag-mobile change,acccount_updation_flag-potential dormant activation,requests_flag-account statements,requests_flag-dis request,requests_flag-account closure,ipo_mf_related_flag-ipo allotment status,ipo_mf_related_flag-apply ipo,ipo_mf_related_flag-apply for mf,funds_payout_related_flag-available funds-available funds,funds_payout_related_flag-available margin,funds_payout_related_flag-new payout request,funds_payout_related_flag-payout status,others_flag-portfolio valuation,others_flag-forgot password,self_service_sum,self_service_flag,address_update_flag,nominee_updation_flag,activate_segments_flag,gst_updation_flag,offline_to_online_flag,bank_updation_flag,Switch_to_neo_flag,Switch_to_nest_flag,email_updation_flag,mobile_updation_flag,stmt_flag,dis_request_flag,Account_closure_flag,apply_ipo_flag,ipo_allotment_status_flag,place_order_in_MF_flag,available_margin_flag,available_funds_flag,new_payout_request_flag,payout_status_flag,portfolio_valuation_flag,forgot_password_flag,End_resolution,end-msg_flag,Livechat_Raised_BOT
0,994502300424,4502300424,session_1,10,9945023004242022-10-08session_1,hi,hi irsquom maya your virtual assistant from ko...,hi,NaN,NaN,NaN,NaN,0,NaN,0.0,0,hi,hi,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,NaN
1,9779866622462,9866622462,session_1,10,97798666224622022-10-25session_1,hi,hi irsquom maya your virtual assistant from ko...,hi,NaN,NaN,NaN,NaN,0,NaN,0.0,0,hi,hi,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,NaN
2,9779851032744,9851032744,session_1,10,97798510327442022-10-24session_1,funds related > want to talk to agent directly...,due to high chat volumes there may be a delay ...,nan > nan > nan > livechat service for whatsap...,1.0,NaN,NaN,NaN,0,NaN,1.0,1,funds related,funds related,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,1.0
3,9779828725416,9828725416,session_1,10,97798287254162022-10-25session_1,hi,hi irsquom maya your virtual assistant from ko...,hi,NaN,NaN,NaN,NaN,0,NaN,0.0,0,hi,hi,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,NaN
4,9779824006495,9824006495,session_1,10,97798240064952022-10-04session_1,available funds > new client,your whatsapp mobile number is not registered ...,nan > wa self service authentication,NaN,NaN,NaN,NaN,0,1.0,0.0,0,available funds,available funds,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,NaN

In [18]:
df.to_excel(r"\\10.6.103.60\Analytics_Shared\Devika Patawari\Bot Analysis\Output\Trials for october\October_chat.xlsx",index=False)

#### To find all the things that customer says before raising livechat request

In [12]:
df= pd.read_excel(r"\\10.6.103.60\Analytics_Shared\Devika Patawari\Bot Analysis\Output\Trials for october\October_chat.xlsx", sheet_name="user_live_chat_raised_flag")
df.head(5)
df.shape

,ID,Mobile no.,sessions,month,concat,User Query,Bot Response,Intent Recognized,user_live_chat_raised_flag,expert/livechat_flag_start,existing_client_flag,Existing Client_N,Existing Client_Flag,new_client_flag,bot_live_chat_flag,live chat flag,Event_User1,Event_str,acccount_updation_flag-address change,acccount_updation_flag-nominee updation,acccount_updation_flag-segment activation,acccount_updation_flag-gstin update,acccount_updation_flag-convert to online,acccount_updation_flag-bank updation,acccount_updation_flag-switch to neo,acccount_updation_flag-switch to nest,acccount_updation_flag-email id update,acccount_updation_flag-mobile change,acccount_updation_flag-potential dormant activation,requests_flag-account statements,requests_flag-dis request,requests_flag-account closure,ipo_mf_related_flag-ipo allotment status,ipo_mf_related_flag-apply ipo,ipo_mf_related_flag-apply for mf,funds_payout_related_flag-available funds-available funds,funds_payout_related_flag-available margin,funds_payout_related_flag-new payout request,funds_payout_related_flag-payout status,others_flag-portfolio valuation,others_flag-forgot password,self_service_sum,self_service_flag,address_update_flag,nominee_updation_flag,activate_segments_flag,gst_updation_flag,offline_to_online_flag,bank_updation_flag,Switch_to_neo_flag,Switch_to_nest_flag,email_updation_flag,mobile_updation_flag,stmt_flag,dis_request_flag,Account_closure_flag,apply_ipo_flag,ipo_allotment_status_flag,place_order_in_MF_flag,available_margin_flag,available_funds_flag,new_payout_request_flag,payout_status_flag,portfolio_valuation_flag,forgot_password_flag,End_resolution,end-msg_flag,Livechat_Raised_BOT
0,9779851032744,9851032744,session_1,10,97798510327442022-10-24session_1,funds related > want to talk to agent directly...,due to high chat volumes there may be a delay ...,nan > nan > nan > livechat service for whatsap...,1,NaN,NaN,NaN,0,NaN,1,1,funds related,funds related,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1.0
1,97470549618,7470549618,session_2,10,974705496182022-10-01session_2,chat with our expert > unidentified client > l...,your whatsapp number is not registered with us...,nan > livechat service for whatsapp > chat wit...,1,1.0,NaN,NaN,0,NaN,0,1,chat with our expert,chat with our expert,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN
2,97470487790,7470487790,session_1,10,974704877902022-10-29session_1,others > no > chat with an expert > identified...,due to high chat volumes there may be a delay ...,nan > nan > nan > livechat service for whatsap...,1,NaN,NaN,NaN,0,NaN,1,1,others,others,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1.0
3,97466587455,7466587455,session_1,10,974665874552022-10-28session_1,hi > good morning ms. maya > query no. 4444240...,hi irsquom maya your virtual assistant from ko...,hi > nan > nan > nan > nan > nan > livechat se...,1,NaN,NaN,NaN,0,NaN,1,1,hi,hi,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1.0
4,97455864627,7455864627,session_2,10,974558646272022-10-26session_2,gm > ddb864c1c54f1ea0549df30a31a3b402f494b58da...,i39m not sure if i can help you with your quer...,nan > nan > nan > nan > livechat service for w...,1,NaN,NaN,NaN,0,NaN,0,1,gm,gm,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN

(30145, 68)

In [31]:
newdf = df["User Query"].str.split("want to talk to agent directly|chat with our expert|chat with an expert", n = 1, expand = True)

In [14]:
df["First"]= newdf[0]

In [15]:
df["Last"]= newdf[1]

In [16]:
df.head(5)

,ID,Mobile no.,sessions,month,concat,User Query,Bot Response,Intent Recognized,user_live_chat_raised_flag,expert/livechat_flag_start,existing_client_flag,Existing Client_N,Existing Client_Flag,new_client_flag,bot_live_chat_flag,live chat flag,Event_User1,Event_str,acccount_updation_flag-address change,acccount_updation_flag-nominee updation,acccount_updation_flag-segment activation,acccount_updation_flag-gstin update,acccount_updation_flag-convert to online,acccount_updation_flag-bank updation,acccount_updation_flag-switch to neo,acccount_updation_flag-switch to nest,acccount_updation_flag-email id update,acccount_updation_flag-mobile change,acccount_updation_flag-potential dormant activation,requests_flag-account statements,requests_flag-dis request,requests_flag-account closure,ipo_mf_related_flag-ipo allotment status,ipo_mf_related_flag-apply ipo,ipo_mf_related_flag-apply for mf,funds_payout_related_flag-available funds-available funds,funds_payout_related_flag-available margin,funds_payout_related_flag-new payout request,funds_payout_related_flag-payout status,others_flag-portfolio valuation,others_flag-forgot password,self_service_sum,self_service_flag,address_update_flag,nominee_updation_flag,activate_segments_flag,gst_updation_flag,offline_to_online_flag,bank_updation_flag,Switch_to_neo_flag,Switch_to_nest_flag,email_updation_flag,mobile_updation_flag,stmt_flag,dis_request_flag,Account_closure_flag,apply_ipo_flag,ipo_allotment_status_flag,place_order_in_MF_flag,available_margin_flag,available_funds_flag,new_payout_request_flag,payout_status_flag,portfolio_valuation_flag,forgot_password_flag,End_resolution,end-msg_flag,Livechat_Raised_BOT,First,Last
0,9779851032744,9851032744,session_1,10,97798510327442022-10-24session_1,funds related > want to talk to agent directly...,due to high chat volumes there may be a delay ...,nan > nan > nan > livechat service for whatsap...,1,NaN,NaN,NaN,0,NaN,1,1,funds related,funds related,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1.0,funds related > want to talk to agent directly...,None
1,97470549618,7470549618,session_2,10,974705496182022-10-01session_2,chat with our expert > unidentified client > l...,your whatsapp number is not registered with us...,nan > livechat service for whatsapp > chat wit...,1,1.0,NaN,NaN,0,NaN,0,1,chat with our expert,chat with our expert,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,,> unidentified client > livechat service for ...
2,97470487790,7470487790,session_1,10,974704877902022-10-29session_1,others > no > chat with an expert > identified...,due to high chat volumes there may be a delay ...,nan > nan > nan > livechat service for whatsap...,1,NaN,NaN,NaN,0,NaN,1,1,others,others,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1.0,others > no > chat with an expert > identified...,None
3,97466587455,7466587455,session_1,10,974665874552022-10-28session_1,hi > good morning ms. maya > query no. 4444240...,hi irsquom maya your virtual assistant from ko...,hi > nan > nan > nan > nan > nan > livechat se...,1,NaN,NaN,NaN,0,NaN,1,1,hi,hi,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1.0,hi > good morning ms. maya > query no. 4444240...,> unidentified client > livechat service for ...
4,97455864627,7455864627,session_2,10,974558646272022-10-26session_2,gm > ddb864c1c54f1ea0549df30a31a3b402f494b58da...,i39m not sure if i can help you with your quer...,nan > nan > nan > nan > livechat service for w...,1,NaN,NaN,NaN,0,NaN,0,1,gm,gm,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,gm > ddb864c1c54f1ea0549df30a31a3b402f494b58da...,> identified client single client code > live...

In [17]:
df.to_excel(r"\\10.6.103.60\Analytics_Shared\Devika Patawari\Bot Analysis\Output\Trials for october\October_livechat_flag_split.xlsx",index=False)

### New logic of sessions

Trial for october month

In [5]:
df= pd.read_excel(r"E:\Analytics_Shared\Devika Patawari\Bot Analysis\Output\Trials for october\October_chat.xlsx", sheet_name="Sheet1")
df.head(5)
df.shape

,ID,Mobile no.,sessions,month,concat,User Query,Bot Response,Intent Recognized,user_live_chat_raised_flag,expert/livechat_flag_start,existing_client_flag,Existing Client_N,Existing Client_Flag,new_client_flag,bot_live_chat_flag,live chat flag,Event_User1,Event_str,acccount_updation_flag-address change,acccount_updation_flag-nominee updation,acccount_updation_flag-segment activation,acccount_updation_flag-gstin update,acccount_updation_flag-convert to online,acccount_updation_flag-bank updation,acccount_updation_flag-switch to neo,acccount_updation_flag-switch to nest,acccount_updation_flag-email id update,acccount_updation_flag-mobile change,acccount_updation_flag-potential dormant activation,requests_flag-account statements,requests_flag-dis request,requests_flag-account closure,ipo_mf_related_flag-ipo allotment status,ipo_mf_related_flag-apply ipo,ipo_mf_related_flag-apply for mf,funds_payout_related_flag-available funds-available funds,funds_payout_related_flag-available margin,funds_payout_related_flag-new payout request,funds_payout_related_flag-payout status,others_flag-portfolio valuation,others_flag-forgot password,self_service_sum,self_service_flag,address_update_flag,nominee_updation_flag,activate_segments_flag,gst_updation_flag,offline_to_online_flag,bank_updation_flag,Switch_to_neo_flag,Switch_to_nest_flag,email_updation_flag,mobile_updation_flag,stmt_flag,dis_request_flag,Account_closure_flag,apply_ipo_flag,ipo_allotment_status_flag,place_order_in_MF_flag,available_margin_flag,available_funds_flag,new_payout_request_flag,payout_status_flag,portfolio_valuation_flag,forgot_password_flag,End_resolution,end-msg_flag,Livechat_Raised_BOT
0,994502300424,4502300424,session_1,10,9945023004242022-10-08session_1,hi,hi irsquom maya your virtual assistant from ko...,hi,NaN,NaN,NaN,NaN,0,NaN,0.0,0,hi,hi,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,NaN
1,9779866622462,9866622462,session_1,10,97798666224622022-10-25session_1,hi,hi irsquom maya your virtual assistant from ko...,hi,NaN,NaN,NaN,NaN,0,NaN,0.0,0,hi,hi,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,NaN
2,9779851032744,9851032744,session_1,10,97798510327442022-10-24session_1,funds related > want to talk to agent directly...,due to high chat volumes there may be a delay ...,nan > nan > nan > livechat service for whatsap...,1.0,NaN,NaN,NaN,0,NaN,1.0,1,funds related,funds related,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,1.0
3,9779828725416,9828725416,session_1,10,97798287254162022-10-25session_1,hi,hi irsquom maya your virtual assistant from ko...,hi,NaN,NaN,NaN,NaN,0,NaN,0.0,0,hi,hi,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,NaN
4,9779824006495,9824006495,session_1,10,97798240064952022-10-04session_1,available funds > new client,your whatsapp mobile number is not registered ...,nan > wa self service authentication,NaN,NaN,NaN,NaN,0,1.0,0.0,0,available funds,available funds,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,NaN

(66488, 68)

In [6]:
df.loc[df['Bot Response'].str.contains('one of our livechat agents will get in touch with you shortly',na=False),'Livechat_agent_shortly_BOT'] = 1

In [7]:
df.head()

,ID,Mobile no.,sessions,month,concat,User Query,Bot Response,Intent Recognized,user_live_chat_raised_flag,expert/livechat_flag_start,existing_client_flag,Existing Client_N,Existing Client_Flag,new_client_flag,bot_live_chat_flag,live chat flag,Event_User1,Event_str,acccount_updation_flag-address change,acccount_updation_flag-nominee updation,acccount_updation_flag-segment activation,acccount_updation_flag-gstin update,acccount_updation_flag-convert to online,acccount_updation_flag-bank updation,acccount_updation_flag-switch to neo,acccount_updation_flag-switch to nest,acccount_updation_flag-email id update,acccount_updation_flag-mobile change,acccount_updation_flag-potential dormant activation,requests_flag-account statements,requests_flag-dis request,requests_flag-account closure,ipo_mf_related_flag-ipo allotment status,ipo_mf_related_flag-apply ipo,ipo_mf_related_flag-apply for mf,funds_payout_related_flag-available funds-available funds,funds_payout_related_flag-available margin,funds_payout_related_flag-new payout request,funds_payout_related_flag-payout status,others_flag-portfolio valuation,others_flag-forgot password,self_service_sum,self_service_flag,address_update_flag,nominee_updation_flag,activate_segments_flag,gst_updation_flag,offline_to_online_flag,bank_updation_flag,Switch_to_neo_flag,Switch_to_nest_flag,email_updation_flag,mobile_updation_flag,stmt_flag,dis_request_flag,Account_closure_flag,apply_ipo_flag,ipo_allotment_status_flag,place_order_in_MF_flag,available_margin_flag,available_funds_flag,new_payout_request_flag,payout_status_flag,portfolio_valuation_flag,forgot_password_flag,End_resolution,end-msg_flag,Livechat_Raised_BOT,Livechat_agent_shortly_BOT
0,994502300424,4502300424,session_1,10,9945023004242022-10-08session_1,hi,hi irsquom maya your virtual assistant from ko...,hi,NaN,NaN,NaN,NaN,0,NaN,0.0,0,hi,hi,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,NaN,NaN
1,9779866622462,9866622462,session_1,10,97798666224622022-10-25session_1,hi,hi irsquom maya your virtual assistant from ko...,hi,NaN,NaN,NaN,NaN,0,NaN,0.0,0,hi,hi,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,NaN,NaN
2,9779851032744,9851032744,session_1,10,97798510327442022-10-24session_1,funds related > want to talk to agent directly...,due to high chat volumes there may be a delay ...,nan > nan > nan > livechat service for whatsap...,1.0,NaN,NaN,NaN,0,NaN,1.0,1,funds related,funds related,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,1.0,1.0
3,9779828725416,9828725416,session_1,10,97798287254162022-10-25session_1,hi,hi irsquom maya your virtual assistant from ko...,hi,NaN,NaN,NaN,NaN,0,NaN,0.0,0,hi,hi,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,NaN,NaN
4,9779824006495,9824006495,session_1,10,97798240064952022-10-04session_1,available funds > new client,your whatsapp mobile number is not registered ...,nan > wa self service authentication,NaN,NaN,NaN,NaN,0,1.0,0.0,0,available funds,available funds,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,NaN,NaN

In [8]:
df.to_excel(r"E:\Analytics_Shared\Devika Patawari\Bot Analysis\Output\Trials for october\October_chat.xlsx",index=False)

###################

In [18]:
df= pd.read_excel(r"E:\Analytics_Shared\Devika Patawari\Bot Analysis\Output\Trials for october\October_livechat_flag_split.xlsx", sheet_name="Sheet2")
df.head(5)
df.shape

,Number,User Query,Bot Response,Time,Intent Recognized,User ID,Channel,User Feedback,Intent Feedback,Sentiment,Date,Time.1,Date & Time,&,T/F,Diff,Count
0,1,Main Menu,"Hi! I&rsquo;m Maya, your virtual assistant fro...",Oct 14 2022 02:26 PM,Greetings,919999514359,WhatsApp,NaN,NaN,Positive,2022-10-14,14:26:00,2022-10-14 14:26:00,WhatsApp91999951435910/14/2022 14:26:00,False,##############################################...,1
1,2,Hi,"Hi! I&rsquo;m Maya, your virtual assistant fro...",Oct 14 2022 02:26 PM,Hi,919999514359,WhatsApp,NaN,NaN,Neutral,2022-10-14,14:26:00,2022-10-14 14:26:00,WhatsApp91999951435910/14/2022 14:26:00,True,00:00:00,0
2,3,Yes,Client Account is Suspended/Deactivated,Oct 14 2022 02:28 PM,NaN,919999514359,WhatsApp,NaN,NaN,Neutral,2022-10-14,14:28:00,2022-10-14 14:28:00,WhatsApp91999951435910/14/2022 14:28:00,True,00:02:00,0
3,4,Talk to CSE,Do you wish to self-authenticate?,Oct 14 2022 02:28 PM,NaN,919999514359,WhatsApp,NaN,NaN,Neutral,2022-10-14,14:28:00,2022-10-14 14:28:00,WhatsApp91999951435910/14/2022 14:28:00,True,00:00:00,0
4,5,identified client single client code,NaN,Oct 14 2022 02:28 PM,LiveChat Service for WhatsApp,919999514359,WhatsApp,NaN,NaN,Negative,2022-10-14,14:28:00,2022-10-14 14:28:00,WhatsApp91999951435910/14/2022 14:28:00,True,00:00:00,0

(34, 17)

In [19]:
df['Time1'] = pd.to_datetime(df['Time'])

In [20]:
df.head(5)

,Number,User Query,Bot Response,Time,Intent Recognized,User ID,Channel,User Feedback,Intent Feedback,Sentiment,Date,Time.1,Date & Time,&,T/F,Diff,Count,Time1
0,1,Main Menu,"Hi! I&rsquo;m Maya, your virtual assistant fro...",Oct 14 2022 02:26 PM,Greetings,919999514359,WhatsApp,NaN,NaN,Positive,2022-10-14,14:26:00,2022-10-14 14:26:00,WhatsApp91999951435910/14/2022 14:26:00,False,##############################################...,1,2022-10-14 14:26:00
1,2,Hi,"Hi! I&rsquo;m Maya, your virtual assistant fro...",Oct 14 2022 02:26 PM,Hi,919999514359,WhatsApp,NaN,NaN,Neutral,2022-10-14,14:26:00,2022-10-14 14:26:00,WhatsApp91999951435910/14/2022 14:26:00,True,00:00:00,0,2022-10-14 14:26:00
2,3,Yes,Client Account is Suspended/Deactivated,Oct 14 2022 02:28 PM,NaN,919999514359,WhatsApp,NaN,NaN,Neutral,2022-10-14,14:28:00,2022-10-14 14:28:00,WhatsApp91999951435910/14/2022 14:28:00,True,00:02:00,0,2022-10-14 14:28:00
3,4,Talk to CSE,Do you wish to self-authenticate?,Oct 14 2022 02:28 PM,NaN,919999514359,WhatsApp,NaN,NaN,Neutral,2022-10-14,14:28:00,2022-10-14 14:28:00,WhatsApp91999951435910/14/2022 14:28:00,True,00:00:00,0,2022-10-14 14:28:00
4,5,identified client single client code,NaN,Oct 14 2022 02:28 PM,LiveChat Service for WhatsApp,919999514359,WhatsApp,NaN,NaN,Negative,2022-10-14,14:28:00,2022-10-14 14:28:00,WhatsApp91999951435910/14/2022 14:28:00,True,00:00:00,0,2022-10-14 14:28:00

In [22]:
df.sort_values(by=['User ID','Time1','Number'], ascending=[1,1,0])

,Number,User Query,Bot Response,Time,Intent Recognized,User ID,Channel,User Feedback,Intent Feedback,Sentiment,Date,Time.1,Date & Time,&,T/F,Diff,Count,Time1
1,2,Hi,"Hi! I&rsquo;m Maya, your virtual assistant fro...",Oct 14 2022 02:26 PM,Hi,919999514359,WhatsApp,NaN,NaN,Neutral,2022-10-14,14:26:00,2022-10-14 14:26:00,WhatsApp91999951435910/14/2022 14:26:00,True,00:00:00,0,2022-10-14 14:26:00
0,1,Main Menu,"Hi! I&rsquo;m Maya, your virtual assistant fro...",Oct 14 2022 02:26 PM,Greetings,919999514359,WhatsApp,NaN,NaN,Positive,2022-10-14,14:26:00,2022-10-14 14:26:00,WhatsApp91999951435910/14/2022 14:26:00,False,##############################################...,1,2022-10-14 14:26:00
6,7,Update Accounts,Choose one from the following,Oct 14 2022 02:28 PM,Update Account,919999514359,WhatsApp,NaN,NaN,Neutral,2022-10-14,14:28:00,2022-10-14 14:28:00,WhatsApp91999951435910/14/2022 14:28:00,True,00:00:00,0,2022-10-14 14:28:00
5,6,LiveChat Service for WhatsApp,NaN,Oct 14 2022 02:28 PM,Chat with our expert,919999514359,WhatsApp,NaN,NaN,Neutral,2022-10-14,14:28:00,2022-10-14 14:28:00,WhatsApp91999951435910/14/2022 14:28:00,True,00:00:00,0,2022-10-14 14:28:00
4,5,identified client single client code,NaN,Oct 14 2022 02:28 PM,LiveChat Service for WhatsApp,919999514359,WhatsApp,NaN,NaN,Negative,2022-10-14,14:28:00,2022-10-14 14:28:00,WhatsApp91999951435910/14/2022 14:28:00,True,00:00:00,0,2022-10-14 14:28:00
3,4,Talk to CSE,Do you wish to self-authenticate?,Oct 14 2022 02:28 PM,NaN,919999514359,WhatsApp,NaN,NaN,Neutral,2022-10-14,14:28:00,2022-10-14 14:28:00,WhatsApp91999951435910/14/2022 14:28:00,True,00:00:00,0,2022-10-14 14:28:00
2,3,Yes,Client Account is Suspended/Deactivated,Oct 14 2022 02:28 PM,NaN,919999514359,WhatsApp,NaN,NaN,Neutral,2022-10-14,14:28:00,2022-10-14 14:28:00,WhatsApp91999951435910/14/2022 14:28:00,True,00:02:00,0,2022-10-14 14:28:00
7,8,Most used services,Choose one from the following:,Oct 14 2022 02:29 PM,Most used services,919999514359,WhatsApp,NaN,NaN,Positive,2022-10-14,14:29:00,2022-10-14 14:29:00,WhatsApp91999951435910/14/2022 14:29:00,True,00:01:00,0,2022-10-14 14:29:00
9,10,Existing Client,NaN,Oct 14 2022 02:30 PM,WA Self Service Authentication,919999514359,WhatsApp,NaN,NaN,Neutral,2022-10-14,14:30:00,2022-10-14 14:30:00,WhatsApp91999951435910/14/2022 14:30:00,True,00:00:00,0,2022-10-14 14:30:00
8,9,Activate segments,Client Account is Suspended/Deactivated,Oct 14 2022 02:30 PM,NaN,919999514359,WhatsApp,NaN,NaN,Neutral,2022-10-14,14:30:00,2022-10-14 14:30:00,WhatsApp91999951435910/14/2022 14:30:00,True,00:01:00,0,2022-10-14 14:30:00
11,12,Hi,"Hi! I&rsquo;m Maya, your virtual assistant fro...",Oct 15 2022 01:23 PM,Hi,919999514359,WhatsApp,NaN,NaN,Neutral,2022-10-15,13:23:00,2022-10-15 13:23:00,WhatsApp91999951435910/15/2022 13:23:00,True,00:00:00,0,2022-10-15 13:23:00
10,11,Main Menu,"Hi! I&rsquo;m Maya, your virtual assistant fro...",Oct 15 2022 01:23 PM,Greetings,919999514359,WhatsApp,NaN,NaN,Positive,2022-10-15,13:23:00,2022-10-15 13:23:00,WhatsApp91999951435910/15/2022 13:23:00,True,22:53:00,1,2022-10-15 13:23:00
13,14,Hi,"Hi! I&rsquo;m Maya, your virtual assistant fro...",Oct 15 2022 01:24 PM,Hi,919999514359,WhatsApp,NaN,NaN,Neutral,2022-10-15,13:24:00,2022-10-15 13:24:00,WhatsApp91999951435910/15/2022 13:24:00,True,00:00:00,0,2022-10-15 13:24:00
12,13,Main Menu,"Hi! I&rsquo;m Maya, your virtual assistant fro...",Oct 15 2022 01:24 PM,Greetings,919999514359,WhatsApp,NaN,NaN,Positive,2022-10-15,13:24:00,2022-10-15 13:24:00,WhatsApp91999951435910/15/2022 13:24:00,True,00:01:00,0,2022-10-15 13:24:00
23,24,FAQs,"Sure, let me help you with that. Please select...",Oct 15 2022 01:25 PM,FAQs,919999514359,WhatsApp,NaN,NaN,Neutral,2022-10-15,13:25:00,2022-10-15 13:25:00,WhatsApp91999951435910/15/2022 13:25:00,True,00:00:00,0,2022-10-15 13:25:00
22,23,Dormant a/c Reactivation,Please select one of the following options or ...,Oct 15 2022 01:25 PM,Dormant account reactivation,919999514359,WhatsApp,NaN,NaN,Neutral,2022-10-15,13:25:00,2022-10-15 13:25:00,WhatsApp91999951435910/15/2022 13:25:00,True,00:00:00,0,2022-10-15 13:25:00
21,22,LiveChat Service for WhatsApp,NaN,Oct 15 2022 01:25 PM,Chat with our expert,919999514359,WhatsApp,NaN,NaN,Neutral,2022-10-15,13:25:00,2022-10-15 13:25:00,WhatsApp91999951435910/15/2022 13:25:00,True,00:00:00,0,2022-10-15 13:25:00
20,21,identified client single client code,NaN,Oct 15 2022 01:25 PM,LiveChat Service for WhatsApp,919999514359,WhatsApp,NaN,NaN,Negative,2022-10-15,13:25:00,2022-10-15 13:25:00,WhatsApp91999951435910/15/2022 13:25:00,True,00:00:00,0,2022-10-15 13:25:00
19,20,Chat with our expert to reactivate account,Do you wish to self-authenticate?,Oct 15 2022 01:25 PM,NaN,919999514359,WhatsApp,NaN,NaN,Neutral,2022-10-15,13:25:00,2022-10-15 13:25:00,WhatsApp91999951435910/15/2022 13:25:00,True,00:00:00,0,2022-10-15 13:25:00
18,19,Yes,Client Account is Suspended/Deactivated,Oct 15 2022 01:25 PM,NaN,919999514359,WhatsApp,NaN,NaN,Neutral,2022-10-15,13:25:00,2022-10-15 13:25:00,WhatsApp91999951435910/15/2022 13:25:00,True,00:00:00,0,2022-10-15 13:25:00
17,18,No,I&#39;m not sure if I can help you with your q...,Oct 15 2022 01:25 PM,NaN,919999514359,WhatsApp,NaN,NaN,Neutral,2022-10-15,13:25:00,2022-10-15 13:25:00,WhatsApp91999951435910/15/2022 13:25:00,True,00:00:00,0,2022-10-15 13:25:00
16,17,LiveChat Service for WhatsApp,NaN,Oct 15 2022 01:25 PM,Chat with our expert,919999514359,WhatsApp,NaN,NaN,Neutral,2022-10-15,13:25:00,2022-10-15 13:25:00,WhatsApp91999951435910/15/2022 13:25:00,True,00:00:00,0,2022-10-15 13:25:00
15,16,identified client single client code,NaN,Oct 15 2022 01:25 PM,LiveChat Service for WhatsApp,919999514359,WhatsApp,NaN,NaN,Negative,2022-10-15,13:25:00,2022-10-15 13:25:00,WhatsApp91999951435910/15/2022 13:25:00,True,00:00:00,0,2022-10-15 13:25:00
14,15,Chat with our Expert,Do you wish to self-authenticate?,Oct 15 2022 01:25 PM,NaN,919999514359,WhatsApp,NaN,NaN,Neutral,2022-10-15,13:25:00,2022-10-15 13:25:00,WhatsApp91999951435910/15/2022 13:25:00,True,00:01:00,0,2022-10-15 13:25:00
29,30,Yes,Client Account is Suspended/Deactivated,Oct 15 2022 01:26 PM,NaN,919999514359,WhatsApp,NaN,NaN,Neutral,2022-10-15,13:26:00,2022-10-15 13:26:00,WhatsApp91999951435910/15/2022 13:26:00,True,00:00:00,0,2022-10-15 13:26:00
28,29,No,I&#39;m not sure if I can help you with your q...,Oct 15 2022 01:26 PM,NaN,919999514359,WhatsApp,NaN,NaN,Neutral,2022-10-15,13:26:00,2022-10-15 13:26:00,WhatsApp91999951435910/15/2022 13:26:00,True,00:00:00,0,2022-10-15 13:26:00
27,28,LiveChat Service for WhatsApp,NaN,Oct 15 2022 01:26 PM,Chat with our expert,919999514359,WhatsApp,NaN,NaN,Neutral,2022-10-15,13:26:00,2022-10-15 13:26:00,WhatsApp91999951435910/15/2022 13:26:00,True,00:00:00,0,2022-10-15 13:26:00
26,27,identified client single client code,NaN,Oct 15 2022 01:26 PM,LiveChat Service for WhatsApp,919999514359,WhatsApp,NaN,NaN,Negative,2022-10-15,13:26:00,2022-10-15 13:26:00,WhatsApp91999951435910/15/2022 13:26:00,True,00:00:00,0,2022-10-15 13:26:00
25,26,Chat with our Expert,Do you wish to self-authenticate?,Oct 15 2022 01:26 PM,NaN,919999514359,WhatsApp,NaN,NaN,Neutral,2022-10-15,13:26:00,2022-10-15 13:26:00,WhatsApp91999951435910/15/2022 13:26:00,True,00:00:00,0,2022-10-15 13:26:00
24,25,No,"Due to high chat volumes, there may be a delay...",Oct 15 2022 01:26 PM,NaN,919999514359,WhatsApp,NaN,NaN,Neutral,2022-10-15,13:26:00,2022-10-15 13:26:00,WhatsApp91999951435910/15/2022 13:26:00,True,00:01:00,0,2022-10-15 13:26:00
30,31,Wait,"Take your time, I'll be waiting",Oct 15 2022 01:42 PM,Hold on.,919999514359,WhatsApp,NaN,NaN,Neutral,2022-10-15,13:42:00,2022-10-15 13:42:00,WhatsApp91999951435910/15/2022 13:42:00,True,00:16:00,1,2022-10-15 13:42:00
32,33,attachment,Sorry! I am still learning to process attachme...,Oct 15 2022 01:45 PM,Attachment,919999514359,WhatsApp,NaN,NaN,Neutral,2022-10-15,13:45:00,2022-10-15 13:45:00,WhatsApp91999951435910/15/2022 13:45:00,True,00:00:00,0,2022-10-15 13:45:00
31,32,Collect User Attachment,"Dear User, please provide the reason from opti...",Oct 15 2022 01:45 PM,Collect User Attachment,919999514359,WhatsApp,NaN,NaN,Neutral,2022-10-15,13:45:00,2022-10-15 13:45:00,WhatsApp91999951435910/15/2022 13:45:00,True,00:03:00,0,2022-10-15 13:45:00
33,34,Dormant account activation sending video,We have received your attachment.One of our Li...,Oct 15 2022 01:46 PM,NaN,919999514359,WhatsApp,NaN,Helpful,Neutral,2022-10-15,13:46:00,2022-10-15 13:46:00,WhatsApp91999951435910/15/2022 13:46:00,True,00:01:00,0,2022-10-15 13:46:00