In [1]:
import pandas as pd
import numpy as np
import pymysql as py

In [2]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"
#pd.set_option('display.max_rows', 20)

In [3]:
df1=pd.read_csv(r"D:\Python dataset\Email Source Dump\May 21.csv",encoding='cp1252')

In [4]:
# df_queries = pd.concat([df1,df2,df3,df4])
# df_queries.shape

df1 = df1.drop_duplicates()

df1.shape
df=df1

(498596, 32)

In [5]:
list(df.head())

['Query Id',
 'User Id',
 'User Name',
 'Call Type Name',
 'Sub Call Type Name',
 'Client Code',
 'Creation Date',
 'Creation time',
 'Last updated Date',
 'Last updated time',
 'Source Description',
 'Product Description',
 'Status Description',
 'SR Nature Name',
 'Last updated by name',
 'Last Updated By Id',
 'First Updated Date',
 'First Updated time',
 'Followup TAT Minutes',
 'Followup TAT Minutes on Assigned Date',
 'Resolved TAT Minutes',
 'FTR Days Count',
 'FTR Days Count With Source',
 'Time Taken for Assigning',
 'Assigned Date',
 'Assigned Time',
 'Emailed Recieved Date',
 'Emailed Recieved Time',
 'InProcess Date',
 'Inprocess Time',
 'TAT in Hours',
 'Teams']

In [6]:
# df_queries = df_queries[['User Id','Query Id', 'Created Date','Client Code', 'SRNature', 'Severity','Escalation Level'
#                     ,'Product', 'CallType Name', 'SubCallType Name', 'Source','TAT', 'Last Updated DateTime', 'Month','Status', 'Source2']]

In [7]:
df['Source Description'] = df['Source Description'].str.strip()
df['Teams'] = df['Teams'].str.strip()
df.rename(columns = {'Source Description':'Source_Description'}, inplace = True)
df.rename(columns = {'SR Nature Name':'SR_Nature'}, inplace = True)
                     
# df.Teams.rename({"PCG Service":"PCG_Service","Email Write Back":"Email_Write_Back",
#                     "Team Manager - Voice":"Team_Manager_Voice","Mobile App and Web issue":"Mobile_App_and_Web_issue",'Call & Trade':'Call&Trade',
#                     'Branch Emails':'Branch_Emails','Escalation Inbound':'Escalation_Inbound','GOB - IT Helpdesk':'GOB_IT_Helpdesk','Brokerage And Charges':'Brokerage&Charges',
#                     'Team Coach - Emails':'Team_Coach_Emails',"Statement and Ledger":"Statement&Ledger",'Social Media':'Social_Media','Funds and Payout':'Funds&Payout','Account Closure':'Account_Closure',
#                     'Team Manager - Escalation':'Team_Manager-Escalation','Team Manager - Platinum Desk':'Team_Manager-Platinum_Desk','Platinum Desk':'Platinum_Desk',
#                     'Team Coach - Voice':'Team_Coach-Voice','Team Manager - Chat':'TeamManager-Chat','Reactivation and Login Help':'Reactivation&Login_Help',
#                     'FNO Calling':'FNO_Calling','Neo CT':'Neo_CT','Branch Service Manager':'Branch_Service_Manager',
#                     'Team Coach - GOB':'Team_Coach-GOB','Team Coach - Outbound':'Team_Coach-Outbound','Support Function':'Support_Function',
#                     'Team Coach - Voice OJT Batch':'Team_Coach-Voice_OJT_Batch','Quality Analyst(CS)':'Quality_Analyst-CS',
#                     'Process Excellence':'Process_Excellence','Leadership Team':'Leadership_Team'}, inplace = True)

In [8]:
df.Teams.unique()

array(['Others', 'PCG Service', 'Derivatives', 'Email Write Back',
       'Team MaOthersger - Voice', 'Emails', 'Chat', 'DOCS',
       'Mobile App and Web issue', 'Call & Trade', 'Branch Emails', 'OJT',
       'Privy', 'Escalation', 'Updation', 'Escalation Inbound', 'Neo',
       'GOB - IT Helpdesk', 'CS-Retention', 'Brokerage And Charges',
       'Team Coach - Emails', 'Statement and Ledger', 'Social Media',
       'Funds and Payout', 'Team MaOthersger - Escalation',
       'Account Closure', 'Team MaOthersger - Platinum Desk',
       'Platinum Desk', 'Team Coach - Voice', 'Team MaOthersger - Chat',
       'Reactivation and Login Help', 'FNO Calling', 'GOB', 'Neo CT',
       'GI', 'NPS', 'Branch Service MaOthersger', 'Trainer',
       'Team Coach - GOB', 'Team Coach - Outbound', 'Support Function',
       'Team Coach - Voice OJT Batch', 'K-Tool', 'Training',
       'Quality AOtherslyst(CS)', 'Process Excellence', 'Leadership Team'],
      dtype=object)

In [12]:
df['FinalSource'] = np.where(df['Source_Description'].isin(['ESCALATION']), 'Include', 'Exclude')
# df['FinalTeam'] = np.where(df['Teams'].isin(['NA']), 'Exclude', 'Include')
df['FinalSrNature'] = np.where(df['SR_Nature'].isin(['Complaint','Escalation']), 'Include', 'Exclude')

# df['FinalRaw'] = np.where(df['FinalSource'].isin(['ESCALATION']), 'Include',
#                    np.where(df['FinalTeam'].isin(['Include']), 'Include',
#                    np.where(df['FinalSrNature'].isin(['Complaint']), 'Include', 'Exclude')))

In [14]:
pd.DataFrame(df['Teams'].value_counts())

                                   Teams
Others                            300109
Emails                             32099
Chat                               31209
PCG Service                        13025
Call & Trade                       12389
Neo                                12369
Privy                              10426
Mobile App and Web issue            8777
Derivatives                         7962
Funds and Payout                    7376
CS-Retention                        6685
Brokerage And Charges               6202
Statement and Ledger                5620
GOB                                 5607
Escalation Inbound                  5317
Platinum Desk                       4488
Updation                            4194
Account Closure                     3402
OJT                                 2897
Reactivation and Login Help         2027
GOB - IT Helpdesk                   1987
FNO Calling                         1968
Team Coach - Voice                  1800
Branch Emails                       1656
DOCS                                1656
GI                                  1395
NPS                                 1323
Escalation                          1171
Email Write Back                    1027
Neo CT                               829
Social Media                         415
Training                             381
Quality AOtherslyst(CS)              210
Team MaOthersger - Voice             146
Branch Service MaOthersger            98
Trainer                               70
Team MaOthersger - Platinum Desk      65
Team MaOthersger - Chat               57
Team Coach - Emails                   54
Team Coach - GOB                      45
Team MaOthersger - Escalation         20
Team Coach - Voice OJT Batch          17
Support Function                       8
Process Excellence                     8
Team Coach - Outbound                  5
Leadership Team                        4
K-Tool                                 1

In [15]:
pd.pivot_table(df, index={"Teams","FinalSrNature"},values="Query Id", aggfunc=np.count_nonzero)

                                             Query Id
FinalSrNature Teams
Exclude       Account Closure                    3288
              Branch Emails                      1655
              Branch Service MaOthersger           95
              Brokerage And Charges              6119
              CS-Retention                       6671
...                                               ...
Include       Team MaOthersger - Chat               4
              Team MaOthersger - Escalation         5
              Team MaOthersger - Voice              4
              Training                             11
              Updation                            148

[79 rows x 1 columns]

In [17]:
pd.pivot_table(df, index="FinalSource",values="Query Id", aggfunc=np.count_nonzero)
# pd.pivot_table(df, index="FinalTeam",values="Query Id", aggfunc=np.count_nonzero)
pd.pivot_table(df, index="FinalSrNature",values="Query Id", aggfunc=np.count_nonzero)

             Query Id
FinalSource
Exclude        497278
Include          1318

               Query Id
FinalSrNature
Exclude          494495
Include            4101